import Mathlib.CategoryTheory.Category.Basic
import Mathlib.Order.Defs.PartialOrder

/-!
# Graph-Structured Lambda Theories (Abstract)

This file formalizes the abstract definition of a Graph-Structured Lambda Theory
(GSLT) as a triple S = (T, E, R) following Meredith's "Computation, Causality,
and Consciousness" (2026), Definition 2.1.

## Main Definitions

* `GSLT` — A graph-structured lambda theory: grammar + equations + rewrite rules
* `GSLT.Morphism` — Bisimilarity-preserving maps between GSLTs (Definition 2.2)
* `GSLT.RewritePath` — Finite sequences of rewrite steps
* `GSLT.Bisimilar` — Strong bisimilarity induced by the LTS

## Design Decisions

We parameterize over an abstract term type.
The equations are given as a `Setoid` (equivalence relation) on terms.
Rewrite rules are given as a relation on terms that respects equations.

This is deliberately abstract — specific GSLTs (λ-calculus, π-calculus, ρ-calculus)
are obtained by instantiating the term type and rules.

## References

- Meredith, "Computation, Causality, and Consciousness" (2026), Part I, §2
- Bucciarelli & Salibra, "Graph Lambda Theories" (2008)
-/

namespace Mettapedia.GSLT

/-! ## The GSLT Structure -/

/-- A Graph-Structured Lambda Theory.

    Definition 2.1 (Meredith 2026): A GSLT is a triple S = (T, E, R) where:
    - T is a grammar of terms (here: a type `Term`)
    - E is a set of equations (here: a `Setoid` on `Term`)
    - R is a set of rewrite rules (here: a relation on `Term`)

    The reduction relation R operates on equivalence classes T/≡.
-/
structure GSLT where
  /-- The type of terms generated by the grammar T -/
  Term : Type*
  /-- The equations E: an equivalence relation ≡ on terms
      (e.g., α-equivalence, structural congruence) -/
  equations : Setoid Term
  /-- The rewrite rules R: a one-step reduction relation on terms.
      Must respect the equations: if t ≡ t' and t → u, then t' → u' for some u ≡ u'. -/
  rewrites : Term → Term → Prop
  /-- Rewrite rules respect equations on the left -/
  rewrites_resp_left : ∀ {t t' u}, equations.r t t' → rewrites t u →
    ∃ u', rewrites t' u' ∧ equations.r u u'
  /-- Rewrite rules respect equations on the right -/
  rewrites_resp_right : ∀ {t u u'}, rewrites t u → equations.r u u' →
    rewrites t u'

namespace GSLT

variable (S : GSLT)

/-- t ≡ₛ t' for equational equivalence -/
def Equiv (t t' : S.Term) : Prop := S.equations.r t t'

/-- t →ₛ t' for one-step reduction -/
def Step (t t' : S.Term) : Prop := S.rewrites t t'

/-- A term is a redex if it can take a step -/
def IsRedex (t : S.Term) : Prop := ∃ t', S.Step t t'

/-- A term is in normal form if it cannot take a step -/
def IsNormalForm (t : S.Term) : Prop := ¬ S.IsRedex t

/-- Multi-step reduction: reflexive-transitive closure of →ₛ -/
inductive MultiStep : S.Term → S.Term → Prop where
  | refl (t : S.Term) : MultiStep t t
  | step {t u v : S.Term} : S.Step t u → MultiStep u v → MultiStep t v

/-- A rewrite path is a list of intermediate terms witnessing multi-step reduction -/
inductive RewritePath : S.Term → S.Term → Type where
  | nil (t : S.Term) : RewritePath t t
  | cons {t u v : S.Term} : S.Step t u → RewritePath u v → RewritePath t v

/-- Length of a rewrite path -/
def RewritePath.length : {t u : S.Term} → S.RewritePath t u → Nat
  | _, _, .nil _ => 0
  | _, _, .cons _ rest => 1 + rest.length

/-- A labeled rewrite step records which terms are involved -/
structure LabeledStep where
  /-- Source term -/
  source : S.Term
  /-- Target term -/
  target : S.Term
  /-- Proof that this is a valid step -/
  step : S.Step source target

/-! ## Bisimilarity

    Strong bisimilarity is the largest symmetric relation R such that:
    if R(t, u) and t → t', then ∃ u', u → u' ∧ R(t', u')
-/

/-- A relation is a bisimulation if it is closed under steps in both directions -/
def IsBisimulation (R : S.Term → S.Term → Prop) : Prop :=
  (∀ {t u}, R t u → ∀ {t'}, S.Step t t' → ∃ u', S.Step u u' ∧ R t' u') ∧
  (∀ {t u}, R t u → ∀ {u'}, S.Step u u' → ∃ t', S.Step t t' ∧ R t' u')

/-- Strong bisimilarity: the union of all bisimulations -/
def Bisimilar (t u : S.Term) : Prop :=
  ∃ R, S.IsBisimulation R ∧ R t u

theorem bisimilar_refl (t : S.Term) : S.Bisimilar t t := by
  refine ⟨Eq, ⟨?_, ?_⟩, rfl⟩
  · intro a b hab t' hs; subst hab; exact ⟨t', hs, rfl⟩
  · intro a b hab u' hs; subst hab; exact ⟨u', hs, rfl⟩

theorem bisimilar_symm {t u : S.Term} (h : S.Bisimilar t u) : S.Bisimilar u t := by
  obtain ⟨R, ⟨hfwd, hbwd⟩, hr⟩ := h
  exact ⟨fun a b => R b a, ⟨hbwd, hfwd⟩, hr⟩

theorem bisimilar_trans {t u v : S.Term}
    (h1 : S.Bisimilar t u) (h2 : S.Bisimilar u v) : S.Bisimilar t v := by
  obtain ⟨R1, ⟨hfwd1, hbwd1⟩, hr1⟩ := h1
  obtain ⟨R2, ⟨hfwd2, hbwd2⟩, hr2⟩ := h2
  refine ⟨fun a c => ∃ b, R1 a b ∧ R2 b c, ?_, u, hr1, hr2⟩
  constructor
  · intro a c ⟨b, hab, hbc⟩ a' hstep
    obtain ⟨b', hstep', hab'⟩ := hfwd1 hab hstep
    obtain ⟨c', hstep'', hbc'⟩ := hfwd2 hbc hstep'
    exact ⟨c', hstep'', b', hab', hbc'⟩
  · intro a c ⟨b, hab, hbc⟩ c' hstep
    obtain ⟨b', hstep', hbc'⟩ := hbwd2 hbc hstep
    obtain ⟨a', hstep'', hab'⟩ := hbwd1 hab hstep'
    exact ⟨a', hstep'', b', hab', hbc'⟩

/-- Bisimilarity forms a setoid -/
def bisimSetoid : Setoid S.Term where
  r := S.Bisimilar
  iseqv := ⟨S.bisimilar_refl, fun h => S.bisimilar_symm h, fun h1 h2 => S.bisimilar_trans h1 h2⟩

end GSLT

/-! ## Morphisms of GSLTs

    Definition 2.2 (Meredith 2026): A morphism f : S → S' is a map on terms
    that preserves bisimilarity.
-/

/-- A morphism between GSLTs preserves bisimilarity.

    Definition 2.2 (Meredith 2026): f : S → S' is a morphism if
    u₁ ∼ u₂ ⟹ f(u₁) ∼ f(u₂).
-/
structure GSLT.Morphism (S S' : GSLT) where
  /-- The underlying map on terms -/
  toFun : S.Term → S'.Term
  /-- Preserves bisimilarity -/
  preserves_bisim : ∀ {t u}, S.Bisimilar t u → S'.Bisimilar (toFun t) (toFun u)

namespace GSLT.Morphism

/-- Identity morphism -/
def id (S : GSLT) : Morphism S S where
  toFun := _root_.id
  preserves_bisim := _root_.id

/-- Composition of morphisms -/
def comp {S S' S'' : GSLT} (g : Morphism S' S'') (f : Morphism S S') :
    Morphism S S'' where
  toFun := g.toFun ∘ f.toFun
  preserves_bisim := fun h => g.preserves_bisim (f.preserves_bisim h)

/-- Identity is left-neutral for composition -/
theorem id_comp {S S' : GSLT} (f : Morphism S S') :
    comp (id S') f = f := by
  rfl

/-- Identity is right-neutral for composition -/
theorem comp_id {S S' : GSLT} (f : Morphism S S') :
    comp f (id S) = f := by
  rfl

end GSLT.Morphism

/-! ## Summary

This file establishes the abstract GSLT framework:

1. **GSLT**: Triple (T, E, R) — terms, equations, rewrite rules
2. **Step/MultiStep/RewritePath**: One-step and multi-step reduction with paths
3. **Bisimilarity**: Largest bisimulation relation, proven to be an equivalence
4. **Morphism**: Bisimilarity-preserving maps, with identity and composition

**Paper Coverage**: Definitions 2.1, 2.2; Remark 2.1

**No sorry statements** — everything is fully proven.

**Next**: `Causality/Trace.lean` (Definition 3.1)
-/

end Mettapedia.GSLT
