import Mettapedia.CategoryTheory.DeFinettiExports

/-! # De Finetti Smoke Test
Type-checks that headline aliases and key API theorems resolve correctly. -/

namespace Mettapedia.CategoryTheory

-- Headline aliases
#check @deFinetti_kleisliGiry
#check @deFinetti_measure
#check @deFinettiExport_markovMixture_to_kleisliGiryFactorization
#check @deFinettiExport_markovMixture_to_kleisliGirySequenceCylinderFactorization
#check @deFinettiExport_categoricalMarkovDeFinettiFactorization_iff_kleisliGiry
#check @deFinettiExport_categoricalMarkovSequenceCylinderFactorization_iff_prefixLaw
#check @deFinettiExport_kleisliGiryMarkovSequenceCylinderFactorization_iff_prefixLaw
#check @deFinettiExport_kleisliGiryMarkovDeFinettiFactorization_iff_nonempty_markovMixture
#check @deFinettiExport_kleisliGiryMarkovSequenceCylinderFactorization_iff_nonempty_markovMixture
#check @deFinettiExport_borelMarkovSequenceMixture_prob
#check @deFinettiExport_borelMarkovSequenceMixture_cylinder_eq
#check @deFinettiExport_borelMarkovCylinderWeightViaProbMarkov_eq_momentMapWord
#check @deFinettiExport_categoricalBorelMarkovSequenceKernelFactorization_iff_prefixLaw
#check @deFinettiExport_categoricalBorelMarkovSequenceKernelFactorization_iff_exists_borelMarkovSequenceMixture
#check @deFinettiExport_categoricalBorelMarkovSequenceKernelFactorization_iff_nonempty_borelMarkovMixture
#check @deFinettiExport_categoricalMarkovDeFinettiFactorization_of_categoricalBorel
#check @deFinettiExport_markovMixture_of_borelMarkovMixture
#check @deFinettiExport_nonempty_markovMixture_of_nonempty_borelMarkovMixture
#check @deFinettiExport_not_injective_borelMomentMapWord_fin2
#check @deFinettiExport_deadRowPrefixMeasure_has_two_distinct_borelMarkovMixtures

-- Negative results
#check @deFinettiExport_not_allSourcesKleisli_unrestricted
#check @deFinettiExport_not_commutesToMarkovBridge_unrestricted
#check @deFinettiExport_not_defaultAllSourcesKernel_to_allSourcesKleisli_unrestricted_strengthening

-- Finite-mass equivalence
#check @deFinettiExport_allSourcesKleisli_finiteMass_iff_markovOnly

-- Cone-level API
#check @deFinettiExport_globalIIDConeMediatorUnique_finiteMass_of_globalFinitaryInvariance_and_defaultAllSourcesKernel
#check @deFinettiExport_globalIIDConeMediatorUnique_markovOnly_of_finiteMass

-- Solomonoff bridge
#check @deFinettiExport_restrictedSolomonoff_prefixLaw_implies_unique_latentThetaMediator

-- Categorical ↔ PLN bridge
#check @deFinettiExport_categorical_pln_sufficiency
#check @deFinettiExport_categoricalProductPMF_fin2_eq_bernoulliProductPMF

end Mettapedia.CategoryTheory
