import Mettapedia.ProbabilityTheory.KnuthSkilling.Core.Algebra
import Mettapedia.ProbabilityTheory.KnuthSkilling.Additive.Proofs.GridInduction.CredalSets
import Mettapedia.ProbabilityTheory.Hypercube.KnuthSkilling.SequentialSemantics
import Mettapedia.ProbabilityTheory.Hypercube.KnuthSkilling.ScaleDichotomy
import Mettapedia.ProbabilityTheory.Hypercube.Basic
import Mettapedia.ProbabilityTheory.Hypercube.ThetaSemantics
import Mathlib.Order.ConditionallyCompleteLattice.Basic

/-!
# Knuth–Skilling Slice: Neighbor Analysis inside the Full Hypercube

This file systematically explores all "neighbors" of the classical K&S representation
theorem inside the **full** probability hypercube defined in
`Mettapedia/ProbabilityTheory/Hypercube/Basic.lean`.

## Full Hypercube vs K&S Slice

The project has exactly one "master" hypercube: the multi-axis `ProbabilityVertex` in
`Mettapedia.ProbabilityTheory.Hypercube.Basic`.

This file is a **K&S-focused slice**:
- it fixes the master hypercube coordinates to the semantic K&S vertex `knuthSkilling`, and
- it studies a small family of additional *model-properties* (order-theoretic and “sandwiching”
  assumptions) that control which representation theorems you can actually prove.

These “slice parameters” are not new axes of `ProbabilityVertex`; they are proof-relevant
assumptions on the *value scale* underlying a K&S model.

## Slice parameters (4-way case split)

1. **Commutativity**: Does x ⊕ y = y ⊕ x hold?
2. **Completeness**: Is α Dedekind complete?
3. **Separation**: Does KSSeparation hold?
4. **Density**: Is α densely ordered?

## The 16 Vertices

Each combination of (±Comm, ±Complete, ±Sep, ±Dense) gives a vertex.
Not all are consistent - some collapse, others are empty.

## Main Results

1. **Classification theorem**: Which vertices are non-empty?
2. **Collapse theorems**: Which vertices are equivalent?
3. **Representation theorems**: What Θ exists at each vertex?
4. **Inference properties**: What can you compute at each vertex?
-/

namespace Mettapedia.ProbabilityTheory.Hypercube.KnuthSkilling.Neighbors

open Classical
open Mettapedia.ProbabilityTheory.KnuthSkilling
open Mettapedia.ProbabilityTheory.KnuthSkilling.Additive
open KnuthSkillingAlgebra

/-!
## §1: Vertex Classification

| # | Comm | Complete | Sep | Dense | Status | Name |
|---|------|----------|-----|-------|--------|------|
| 0 | - | - | - | - | EXISTS | Free monoid |
| 1 | - | - | - | + | EXISTS | Dense free monoid |
| 2 | - | - | + | - | EMPTY | Sep ⇒ Comm |
| 3 | - | - | + | + | EMPTY | Sep ⇒ Comm |
| 4 | - | + | - | - | EXISTS | Complete non-comm |
| 5 | - | + | - | + | EXISTS | Complete dense non-comm |
| 6 | - | + | + | - | EMPTY | Sep ⇒ Comm |
| 7 | - | + | + | + | EMPTY | Sep ⇒ Comm |
| 8 | + | - | - | - | EXISTS | Comm Archimedean (ℤ) |
| 9 | + | - | - | + | EXISTS | Comm dense (ℚ-like) |
| 10 | + | - | + | - | EXISTS | KSSep incomplete discrete |
| 11 | + | - | + | + | EXISTS | Imprecise prob (ℚ) |
| 12 | + | + | - | - | EXISTS | Complete comm discrete |
| 13 | + | + | - | + | EXISTS | Complete comm dense |
| 14 | + | + | + | - | EXISTS | KSSep complete discrete |
| 15 | + | + | + | + | EXISTS | Classical K&S (ℝ) |
-/

/-- Vertices 2,3,6,7 are empty: KSSeparation implies commutativity.
See `Mettapedia.ProbabilityTheory.KnuthSkilling.Additive.Proofs.GridInduction.Core.op_comm_of_KSSeparation`
for the proof. -/
theorem sep_implies_comm_collapse_doc : True := trivial

/-!
## §2: Non-Commutative Vertices (V₀, V₁, V₄, V₅)

These have NO additive ℝ-representation.
-/

/-- Non-commutative algebras have no additive ℝ-representation.

**Proof sketch**: If Θ(x ⊕ y) = Θ(x) + Θ(y) and Θ is injective (from order embedding),
then commutativity of + forces x ⊕ y = y ⊕ x.

This is a fundamental obstruction: the real numbers are commutative,
so any additive representation must preserve commutativity. -/
theorem no_real_rep_of_noncomm_doc : True := trivial

/-!
Even though these vertices have no commutative/additive real semantics, they are not “nothing”:
they admit a *sequential/process* semantics where `x ⊕ y` composes effects and order matters.

See `Mettapedia/ProbabilityTheory/Hypercube/KnuthSkilling/SequentialSemantics.lean`.
-/

/-!
## §3: Density Collapse

If α is densely ordered and has KSSeparation, then KSSeparationStrict holds.
-/

/-- Density + KSSeparation implies KSSeparationStrict -/
theorem dense_sep_implies_strict_sep_doc : True := trivial

/-!
## §3.1: Discrete-vs-Dense Scale Dichotomy (inside ℝ)

Whenever a K&S representation `Θ : α → ℝ` exists, the additive subgroup of `ℝ` generated by the
range of `Θ` is either:
- dense in `ℝ` (ℚ-like scale), or
- cyclic (ℤ-like step size).

This is formalized in `Mettapedia/ProbabilityTheory/Hypercube/KnuthSkilling/ScaleDichotomy.lean`.
-/

/-!
## §4: Inference Capabilities at Each Vertex
-/

/-- Inference capability levels -/
inductive InferenceLevel
  | None       -- No probabilistic inference (non-commutative)
  | Discrete   -- Exact but finite (ℤ-like)
  | Imprecise  -- Interval bounds (ℚ-like)
  | Classical  -- Full measure theory (ℝ)
  deriving DecidableEq, Repr

/-- What inference is possible at each level -/
def inferenceDescription : InferenceLevel → String
  | .None => "Combine only (no conditioning, no expectations)"
  | .Discrete => "Exact finite operations (no limits)"
  | .Imprecise => "Interval-valued operations (robust bounds)"
  | .Classical => "Full measure theory (all operations)"

/-!
## §4.1: “Weaker ⇒ Imprecise” is Not Automatic (but Canonical)

A common misconception is that dropping K&S-style “separation/density” *automatically* yields
Walley-style imprecise probability.

The correct steelman is:

1. Weaker axioms often admit **multiple point-valued completions** (multiple candidates `Θ`).
2. The canonical semantics of such a theory is the **set of all completion-values**.
3. For real-valued completions, this induces an **interval** `[sInf, sSup]` for each term.

This is formalized (for the K&S value scale, independent of event lattices) in
`Mettapedia/ProbabilityTheory/KnuthSkilling/Additive/Proofs/GridInduction/CredalSets.lean`:
- `CredalSets.IntervalAddSemantics.ofThetaFamily` (family of completions ⇒ interval semantics)
- `CredalSets.intervalOf_unique` (singleton family ⇒ precise interval)
- `CredalSets.IntervalAddSemantics.width_subadditive` (imprecision accumulates subadditively)
-/

section CanonicalIntervals

variable {α : Type*}

/-- From any nonempty family of additive real-valued completions `Θ`, we get an interval semantics
for `op` satisfying Minkowski containment. -/
noncomputable def intervalSemantics_ofThetaFamily (op : α → α → α)
    (ι : Type*) [Nonempty ι]
    (Θ : ι → α → ℝ)
    (hAssoc : ∀ x y z, op (op x y) z = op x (op y z))
    (hAdd : ∀ i x y, Θ i (op x y) = Θ i x + Θ i y)
    (hBddBelow : ∀ x, BddBelow (Set.range fun i => Θ i x))
    (hBddAbove : ∀ x, BddAbove (Set.range fun i => Θ i x)) :
    CredalSets.IntervalAddSemantics α :=
  CredalSets.IntervalAddSemantics.ofThetaFamily op ι Θ hAssoc hAdd hBddBelow hBddAbove

/-- A concrete “imprecise” consequence: widths are subadditive for the canonical interval semantics
induced by any family of additive completions. -/
theorem intervalSemantics_width_subadditive (op : α → α → α)
    (ι : Type*) [Nonempty ι]
    (Θ : ι → α → ℝ)
    (hAssoc : ∀ x y z, op (op x y) z = op x (op y z))
    (hAdd : ∀ i x y, Θ i (op x y) = Θ i x + Θ i y)
    (hBddBelow : ∀ x, BddBelow (Set.range fun i => Θ i x))
    (hBddAbove : ∀ x, BddAbove (Set.range fun i => Θ i x))
    (x y : α) :
    ((intervalSemantics_ofThetaFamily op ι Θ hAssoc hAdd hBddBelow hBddAbove).μ (op x y)).width ≤
      ((intervalSemantics_ofThetaFamily op ι Θ hAssoc hAdd hBddBelow hBddAbove).μ x).width +
        ((intervalSemantics_ofThetaFamily op ι Θ hAssoc hAdd hBddBelow hBddAbove).μ y).width := by
  simpa [intervalSemantics_ofThetaFamily] using
    CredalSets.IntervalAddSemantics.width_subadditive
      (S := CredalSets.IntervalAddSemantics.ofThetaFamily op ι Θ hAssoc hAdd hBddBelow hBddAbove) x y

end CanonicalIntervals

/-!
## §4.2: Θ-Families ⇒ Interval Semantics (Complete-Lattice Variant)

`CredalSets`/`CompletionSemantics` work directly over `ℝ` using conditional completeness and explicit
boundedness hypotheses.

For the Hypercube abstraction it is also useful to have a **total** (no extra hypotheses) interval
envelope construction, so we compute envelopes in the complete lattice `WithTop (WithBot ℝ)`
(extended reals `[-∞, +∞]`). When the Θ family is bounded, this agrees with the usual
`sInf`/`sSup` intuition; if it is not bounded, the envelope can legitimately hit `⊥/⊤`.
-/

section ThetaFamilyIntervals

open Mettapedia.ProbabilityTheory.Hypercube
open Mettapedia.ProbabilityTheory.Hypercube.ThetaSemantics

variable {α : Type*}

abbrev ThetaCL : Type := WithTop (WithBot ℝ)

/-- Lift a real-valued completion to the complete lattice `WithTop (WithBot ℝ)`. -/
noncomputable def liftRealCompletion (Θ : α → ℝ) : α → ThetaCL :=
  fun x => ((Θ x : WithBot ℝ) : ThetaCL)

/-- Interval envelope induced by a **set** of real-valued completions, computed in `WithTop ℝ`. -/
noncomputable def intervalOfRealFamily (Θs : Set (α → ℝ)) :
    ThetaSemantics.IntervalSemantics α ThetaCL :=
  ThetaSemantics.intervalOfFamily (β := ThetaCL) (liftRealCompletion '' Θs)

/-- If the real-valued completion family is subsingleton, the induced interval envelope is point-valued. -/
theorem intervalOfRealFamily_lower_eq_upper_of_subsingleton {Θs : Set (α → ℝ)}
    (hsub : Θs.Subsingleton) (hne : Θs.Nonempty) (x : α) :
    (intervalOfRealFamily (α := α) Θs).lower x = (intervalOfRealFamily (α := α) Θs).upper x := by
  classical
  -- Reduce to the complete-lattice lemma on the image family.
  have hsub' : (liftRealCompletion '' Θs).Subsingleton := by
    intro f hf g hg
    rcases hf with ⟨Θf, hΘf, rfl⟩
    rcases hg with ⟨Θg, hΘg, rfl⟩
    have hEq : Θf = Θg := hsub hΘf hΘg
    simp [hEq]
  have hne' : (liftRealCompletion '' Θs).Nonempty := by
    rcases hne with ⟨Θ, hΘ⟩
    exact ⟨liftRealCompletion Θ, ⟨Θ, hΘ, rfl⟩⟩
  simpa [intervalOfRealFamily, ThetaSemantics.intervalOfFamily] using
    (ThetaSemantics.lower_eq_upper_of_subsingleton (Θs := liftRealCompletion '' Θs)
      (hsub := hsub') (hne := hne') x)

end ThetaFamilyIntervals

/-!
## §5: The Key Vertices for Inference

### V₁₁: Imprecise Probability (ℚ)

This is the **honest** probability theory:
- We admit we don't know exact values
- We give interval bounds [P*, P*]
- Conclusions valid for ALL probabilities in the interval
-/

/-- An imprecise probability assignment -/
structure ImpreciseProb where
  lower : ℝ
  upper : ℝ
  valid : lower ≤ upper
  nonneg : 0 ≤ lower
  le_one : upper ≤ 1

/-- Combine independent imprecise probabilities -/
def ImpreciseProb.mul (p q : ImpreciseProb) : ImpreciseProb where
  lower := p.lower * q.lower
  upper := p.upper * q.upper
  valid := by
    apply mul_le_mul p.valid q.valid q.nonneg
    exact le_trans p.nonneg p.valid
  nonneg := mul_nonneg p.nonneg q.nonneg
  le_one := by
    have h1 : p.upper ≤ 1 := p.le_one
    have h2 : q.upper ≤ 1 := q.le_one
    have h3 : 0 ≤ q.upper := le_trans q.nonneg q.valid
    calc p.upper * q.upper ≤ 1 * q.upper := by apply mul_le_mul_of_nonneg_right h1 h3
      _ = q.upper := one_mul _
      _ ≤ 1 := h2

/-- Classical conditioning collapses to a point -/
noncomputable def classicalCondition (pAB pB : ℝ) (_hB : pB ≠ 0) : ℝ := pAB / pB

/-!
### V₁₅: Classical Probability (ℝ)

The K&S theorem gives us this vertex:
- Point-valued probabilities P(A) ∈ [0,1]
- Full conditioning P(A|B) = P(A∩B)/P(B)
- Integration, expectations, limits all work
-/

/-!
## §6: Physical Interpretation

| Vertex | Interpretation | Use Case |
|--------|----------------|----------|
| V₀-V₇ | Order matters | Quantum mechanics |
| V₈,V₁₀,V₁₂,V₁₄ | Finite precision | Combinatorics, CS |
| V₉,V₁₁ | Honest uncertainty | Robust Bayes, AI safety |
| V₁₃,V₁₅ | Idealized precision | Physics, standard stats |
-/

/-!
## §7: The Collapse Hierarchy

```
                    V₁₅ (Classical ℝ)
                    ┌────────┴────────┐
                    │                 │
            +Completeness      -Completeness
                    │                 │
                    ↓                 ↓
               V₁₃ (ℝ no Sep)    V₁₁ (Imprecise ℚ)
                    │                 │
                    │           +KSSeparation
                    │                 │
                    ↓                 ↓
               V₉ (ℚ no Sep)    V₁₀ (Discrete KS)
                    │                 │
                    │            -Density
                    │                 │
                    ↓                 ↓
               V₈ (ℤ) ←───────── V₈ (Discrete)
```

**Key insight**: V₁₁ (Imprecise/ℚ) is the "natural" probability theory.
Classical (V₁₅) requires the extra assumption of completeness.
-/

/-!
## §8: What Each Vertex Tells Us About Inference

### V₀-V₇ (Non-Commutative): NO PROBABILITY

These vertices have no additive representation into ℝ.
They cannot support standard probabilistic inference.

**However**: They might support other kinds of reasoning:
- Quantum logic (V₄, V₅)
- Process algebras (V₀, V₁)
- Non-commutative integration?

### V₈, V₁₀, V₁₂, V₁₄ (Discrete): FINITE PROBABILITY

These support exact probability computations but only for finite structures.
- No limits (can't define P(⋃ᵢ Aᵢ) for infinite unions)
- No integration (only finite sums)
- Perfect for: Combinatorics, computer science, game theory

### V₉, V₁₁ (Imprecise): ROBUST PROBABILITY

These are arguably the MOST IMPORTANT vertices for practical inference!
- Honest about uncertainty: "P ∈ [0.3, 0.4]" not "P = 0.35"
- Robust to misspecification: conclusions valid for all P in interval
- No completeness needed: works over ℚ

**Applications**:
- AI safety (worst-case bounds)
- Robust Bayesian inference
- Adversarial settings
- Constructive mathematics

### V₁₃, V₁₅ (Classical): IDEALIZED PROBABILITY

These require completeness of ℝ (a foundational choice).
- Point-valued probabilities
- Full measure theory
- Countable additivity
- Integration, expectations, everything

**Trade-off**: More powerful operations, but requires idealization.
-/

/-!
## §9: Open Questions

1. **Quantum K&S**: Is there a natural quantum structure at V₄/V₅?
   The non-commutativity suggests a connection to quantum probability.

2. **Constructive K&S**: V₁₁ is constructively valid. What theorems survive?

3. **Tropical K&S**: Replace (ℝ, +, ×) with (ℝ ∪ {∞}, min, +)?
   This gives "cost-based" inference.

4. **Category Theory**: The hypercube as a diagram in Cat?
   Vertices = categories, edges = functors.

5. **Information Geometry**: Each vertex defines a geometry on distributions?
-/

/-!
## §10: Summary

The K&S hypercube reveals that "probability theory" is not unique:

| Feature | Requires |
|---------|----------|
| Basic combination | Associativity only (V₀) |
| Commutativity | KSSeparation (V₁₀+) |
| Point values | Completeness (V₁₃+) |
| Full measure theory | Complete + Dense + Sep (V₁₅) |

**The philosophical takeaway**: Classical probability (V₁₅) requires TWO
assumptions beyond the basic symmetry axioms:
1. Commutativity (derivable from KSSeparation)
2. Completeness of ℝ (a foundational choice)

If you're uncomfortable with (2), work in V₁₁ (imprecise probability).
It's arguably more honest about our actual epistemic state!
-/

end Mettapedia.ProbabilityTheory.Hypercube.KnuthSkilling.Neighbors
