import Mathlib.Topology.Algebra.Order.Archimedean
import Mathlib.Topology.Algebra.Order.Group

import Mettapedia.ProbabilityTheory.Hypercube.ScaleDichotomy
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Main

/-!
# K&S Neighbor Theory: Discrete-vs-Dense Scale Dichotomy

This file provides a small but important background fact used in the K&S-hypercube neighbor
analysis:

> An additive subgroup of an Archimedean linearly ordered additive commutative group is either
> **dense** or **cyclic**.

Specialized to `ℝ`, this yields the familiar “two regimes” for the image of any K&S-style
representation:

- **Discrete / ℤ-like**: the scale is generated by a single step (a cyclic subgroup),
- **Dense / ℚ-like**: the scale is dense in `ℝ`.

Mathlib source:
- `Mathlib/Topology/Algebra/Order/Archimedean.lean` (`AddSubgroup.dense_or_cyclic`).

K&S connection:
- `KnuthSkilling/RepresentationTheorem/Main.lean` produces `Θ : α → ℝ` with `Θ (x ⊕ y) = Θ x + Θ y`.
  The *additive subgroup generated by the range* of `Θ` is therefore an `AddSubgroup ℝ`, so the
  dichotomy applies.
-/

namespace Mettapedia.ProbabilityTheory.Hypercube.KnuthSkilling.ScaleDichotomy

open Classical

/-!
## §2: Applying the dichotomy to K&S-style representations

The K&S representation theorem yields a point-valued `Θ : α → ℝ` with additivity.  Since `α` is a
monoid (not a group), the natural “scale subgroup” is the additive subgroup *generated by* the
range of `Θ`.
-/

/-- The additive subgroup of `ℝ` generated by the values of `Θ`. -/
def scaleSubgroup {α : Type*} (Θ : α → ℝ) : AddSubgroup ℝ :=
  AddSubgroup.closure (Set.range Θ)

/-- The K&S scale subgroup is either dense or cyclic, hence either “dense/ℚ-like” or “discrete/ℤ-like”. -/
theorem scaleSubgroup_dense_or_zmultiples {α : Type*} (Θ : α → ℝ) :
    Dense (scaleSubgroup Θ : Set ℝ) ∨ ∃ r : ℝ, scaleSubgroup Θ = AddSubgroup.zmultiples r := by
  simpa [scaleSubgroup] using
    (Mettapedia.ProbabilityTheory.Hypercube.ScaleDichotomy.dense_or_zmultiples (G := ℝ)
      (S := scaleSubgroup Θ))

/-!
## §3: Easy collapses (dense vs cyclic)

For additive subgroups of `ℝ`, “not dense” collapses to “cyclic” (generated by a single step).
-/

/-- The cyclic subgroup `zmultiples r` is never dense in `ℝ`. -/
theorem not_dense_zmultiples (r : ℝ) : ¬ Dense (AddSubgroup.zmultiples r : Set ℝ) := by
  -- `DenseRange (· • r)` is exactly `Dense (range (· • r))`,
  -- and `range (· • r)` is the carrier of `zmultiples r`.
  simpa [DenseRange, AddSubgroup.coe_zmultiples] using (not_denseRange_zsmul (a := r))

/-- For additive subgroups of `ℝ`, failing density is equivalent to being cyclic. -/
theorem real_addSubgroup_not_dense_iff_exists_zmultiples (S : AddSubgroup ℝ) :
    (¬ Dense (S : Set ℝ)) ↔ ∃ r : ℝ, S = AddSubgroup.zmultiples r := by
  constructor
  · intro hNotDense
    rcases
        (Mettapedia.ProbabilityTheory.Hypercube.ScaleDichotomy.dense_or_zmultiples (G := ℝ)
          (S := S)) with
      hDense | hCyc
    · exact (hNotDense hDense).elim
    · exact hCyc
  · rintro ⟨r, rfl⟩
    exact not_dense_zmultiples r

end Mettapedia.ProbabilityTheory.Hypercube.KnuthSkilling.ScaleDichotomy
