import Mettapedia.GSLT.Logic.ContextHML
import Mettapedia.GSLT.Dynamics.WeightCost
import Mettapedia.GSLT.Causality.Trace

/-!
# Extended HML with Weights and Resources

This file formalizes the extended Hennessy-Milner Logic that combines
context-decorated HML (§5) with the weight/resource structure (§§6–7)
from Meredith's "Computation, Causality, and Consciousness" (2026),
Part I, §8.

## Main Definitions

* `ExtHMLFormula` — Extended HML with weighted diamond and resource guards
* `ExtHMLFormula.satisfies` — Satisfaction relation for extended HML
* `HMLFormula.toExtended` — Embedding plain HML into extended HML
* `WeightBisimilar` — Weighted bisimilarity
* `adequacy_extended` — Statement: weight-bisimilarity ↔ extended HML equivalence

## References

- Meredith, "Computation, Causality, and Consciousness" (2026), §8
- van Glabbeek, "The Linear Time–Branching Time Spectrum"
- Hennessy & Milner, "Algebraic Laws for Nondeterminism and Concurrency"
-/

namespace Mettapedia.GSLT

variable (S : GSLT)

/-! ## Extended HML Formulae

    Definition 8.1 (Meredith 2026): The formulae of extended HML are
    generated by:
    ϕ, ψ ::= ⊤ | ⊥ | ϕ ∧ ψ | ¬ϕ | ⟨K⟩ϕ | ⟨K, w⟩ϕ | [c ≤ b]ϕ | ⟨τ⟩ϕ
-/

inductive ExtHMLFormula (S : GSLT) (W : Type*) (A : Type*) (k : Nat) : Type _ where
  | top : ExtHMLFormula S W A k
  | bot : ExtHMLFormula S W A k
  | conj : ExtHMLFormula S W A k → ExtHMLFormula S W A k → ExtHMLFormula S W A k
  | neg : ExtHMLFormula S W A k → ExtHMLFormula S W A k
  | diamond : GSLTContext S → ExtHMLFormula S W A k → ExtHMLFormula S W A k
  | wdiamond : GSLTContext S → W → ExtHMLFormula S W A k → ExtHMLFormula S W A k
  | resourceGuard : VectorialAccount A k → VectorialAccount A k →
      ExtHMLFormula S W A k → ExtHMLFormula S W A k
  | traceDiamond : ExtHMLFormula S W A k → ExtHMLFormula S W A k

namespace ExtHMLFormula

variable {S : GSLT} {W : Type*} {A : Type*} {k : Nat}

def disj (ϕ ψ : ExtHMLFormula S W A k) : ExtHMLFormula S W A k :=
  .neg (.conj (.neg ϕ) (.neg ψ))

def box (K : GSLTContext S) (ϕ : ExtHMLFormula S W A k) : ExtHMLFormula S W A k :=
  .neg (.diamond K (.neg ϕ))

def wbox (K : GSLTContext S) (w : W) (ϕ : ExtHMLFormula S W A k) :
    ExtHMLFormula S W A k :=
  .neg (.wdiamond K w (.neg ϕ))

/-! ## Satisfaction Relation -/

def satisfies [LE A] (wm : WeightMap S W) :
    S.Term → ExtHMLFormula S W A k → Prop
  | _, .top => True
  | _, .bot => False
  | t, .conj ϕ ψ => satisfies wm t ϕ ∧ satisfies wm t ψ
  | t, .neg ϕ => ¬ satisfies wm t ϕ
  | t, .diamond K ϕ => ∃ t', S.Step (K.plug t) t' ∧ satisfies wm t' ϕ
  | t, .wdiamond K w ϕ =>
      ∃ t', ∃ (h : S.Step (K.plug t) t'), wm.weight h = w ∧ satisfies wm t' ϕ
  | t, .resourceGuard c b ϕ =>
      VectorialAccount.affordable c b → satisfies wm t ϕ
  | t, .traceDiamond ϕ =>
      ∃ t', S.Step t t' ∧ satisfies wm t' ϕ

def hmlEquiv [LE A] (wm : WeightMap S W) (t u : S.Term) : Prop :=
  ∀ ϕ : ExtHMLFormula S W A k, satisfies wm t ϕ ↔ satisfies wm u ϕ

theorem hmlEquiv_refl [LE A] (wm : WeightMap S W) (t : S.Term) :
    hmlEquiv (k := k) wm t t :=
  fun _ => Iff.rfl

theorem hmlEquiv_symm [LE A] {wm : WeightMap S W} {t u : S.Term}
    (h : hmlEquiv (k := k) wm t u) : hmlEquiv (k := k) wm u t :=
  fun ϕ => (h ϕ).symm

theorem hmlEquiv_trans [LE A] {wm : WeightMap S W} {t u v : S.Term}
    (h1 : hmlEquiv (k := k) wm t u) (h2 : hmlEquiv (k := k) wm u v) :
    hmlEquiv (k := k) wm t v :=
  fun ϕ => (h1 ϕ).trans (h2 ϕ)

def hmlSetoid [LE A] (wm : WeightMap S W) : Setoid S.Term where
  r := hmlEquiv (k := k) wm
  iseqv := ⟨hmlEquiv_refl (k := k) wm,
            fun h => hmlEquiv_symm h,
            fun h1 h2 => hmlEquiv_trans h1 h2⟩

end ExtHMLFormula

/-! ## Embedding Plain HML into Extended HML -/

def HMLFormula.toExtended {W : Type*} {A : Type*} {k : Nat} :
    HMLFormula S → ExtHMLFormula S W A k
  | .top => .top
  | .bot => .bot
  | .conj ϕ ψ => .conj (toExtended ϕ) (toExtended ψ)
  | .neg ϕ => .neg (toExtended ϕ)
  | .diamond K ϕ => .diamond K (toExtended ϕ)

theorem HMLFormula.toExtended_satisfies [LE A]
    (wm : WeightMap S W) (t : S.Term) (ϕ : HMLFormula S) :
    ExtHMLFormula.satisfies (k := k) wm t (ϕ.toExtended) ↔
    HMLFormula.satisfies S t ϕ := by
  induction ϕ with
  | top => simp [toExtended, ExtHMLFormula.satisfies, HMLFormula.satisfies]
  | bot => simp [toExtended, ExtHMLFormula.satisfies, HMLFormula.satisfies]
  | conj ϕ ψ ihϕ ihψ =>
    simp only [toExtended, ExtHMLFormula.satisfies, HMLFormula.satisfies]
    exact ⟨fun ⟨h1, h2⟩ => ⟨ihϕ.mp h1, ihψ.mp h2⟩,
           fun ⟨h1, h2⟩ => ⟨ihϕ.mpr h1, ihψ.mpr h2⟩⟩
  | neg ϕ ih =>
    simp only [toExtended, ExtHMLFormula.satisfies, HMLFormula.satisfies]
    exact ⟨fun h hsat => h (ih.mpr hsat), fun h hsat => h (ih.mp hsat)⟩
  | diamond K ϕ ih =>
    simp only [toExtended, ExtHMLFormula.satisfies, HMLFormula.satisfies]
    exact ⟨fun ⟨t', hs, hsat⟩ => ⟨t', hs, ih.mp hsat⟩,
           fun ⟨t', hs, hsat⟩ => ⟨t', hs, ih.mpr hsat⟩⟩

theorem extHML_refines_plainHML [LE A]
    (wm : WeightMap S W) {t u : S.Term}
    (h : ExtHMLFormula.hmlEquiv (k := k) wm t u) :
    HMLFormula.hmlEquiv S t u := by
  intro ϕ
  have := h ϕ.toExtended
  rw [HMLFormula.toExtended_satisfies, HMLFormula.toExtended_satisfies] at this
  exact this

/-! ## Weighted Bisimilarity and Adequacy -/

def WeightBisimilar (wm : WeightMap S W) (t u : S.Term) : Prop :=
  ∃ R : S.Term → S.Term → Prop,
    (∀ {a b}, R a b → ∀ {a'}, (h : S.Step a a') →
      ∃ b', ∃ (h' : S.Step b b'), wm.weight h = wm.weight h' ∧ R a' b') ∧
    (∀ {a b}, R a b → ∀ {b'}, (h : S.Step b b') →
      ∃ a', ∃ (h' : S.Step a a'), wm.weight h' = wm.weight h ∧ R a' b') ∧
    R t u

theorem weightBisimilar_refl (wm : WeightMap S W) (t : S.Term) :
    WeightBisimilar S wm t t := by
  refine ⟨Eq, ⟨?_, ?_⟩, rfl⟩
  · intro a b hab a' hs; subst hab; exact ⟨a', hs, rfl, rfl⟩
  · intro a b hab b' hs; subst hab; exact ⟨b', hs, rfl, rfl⟩

theorem weightBisimilar_symm {wm : WeightMap S W} {t u : S.Term}
    (h : WeightBisimilar S wm t u) : WeightBisimilar S wm u t := by
  obtain ⟨R, ⟨hfwd, hbwd⟩, hr⟩ := h
  exact ⟨fun a b => R b a, ⟨fun hab => hbwd hab, fun hab => hfwd hab⟩, hr⟩

def adequacy_extended_sound (wm : WeightMap S W) : Prop :=
  ∀ {t u : S.Term}, WeightBisimilar S wm t u →
    ExtHMLFormula.hmlEquiv (k := k) wm t u

def adequacy_extended_complete (wm : WeightMap S W) : Prop :=
  ∀ {t u : S.Term}, ExtHMLFormula.hmlEquiv (k := k) wm t u →
    WeightBisimilar S wm t u

def adequacy_extended (wm : WeightMap S W) : Prop :=
  adequacy_extended_sound (k := k) S wm ∧ adequacy_extended_complete (k := k) S wm

/-! ## Summary

This file establishes:

1. **ExtHMLFormula**: Extended HML with weights, resources, traces (Definition 8.1)
2. **satisfies**: Satisfaction relation for extended HML
3. **hmlEquiv**: Extended HML equivalence (proven equivalence relation)
4. **toExtended**: Embedding plain HML → extended HML (satisfaction-preserving)
5. **extHML_refines_plainHML**: Extended equiv refines plain equiv
6. **WeightBisimilar**: Weight-preserving bisimilarity (proven refl + symm)
7. **adequacy_extended**: Statement of Theorem 8.1

**Paper Coverage**: Definition 8.1; Theorem 8.1 (statement)

**No sorry statements** — everything is fully proven or cleanly stated.

**Next**: strengthen `Dynamics/PathIntegral.lean` from finite-support amplitudes
         to explicit summability hypotheses, or move to the Theorem 10.1 layer
-/

end Mettapedia.GSLT
