import Mettapedia.Hyperseed.Regression
import Mettapedia.Logic.ConceptOntology.ConstructionBase

/-!
# Hyperseed Construction-Base Bridge

This module re-expresses Hyperseed's perspective-filtered query discovery in the
`ConstructionBase` vocabulary:

* `Phenomena` are visible queries,
* `Abstract` content is also query-typed,
* `Indexicality` is the budget/cost parameter,
* a visible query `q` is incident to abstract query `a` when `a` lies in the
  rule closure generated from the singleton seed `{q}`.

This does not replace Hyperseed closure. It gives an FCA-style wrapper around
the existing closure/perspective kernel so that `thatsAllAt` / `openWorldAt`
can be read directly on Hyperseed examples.
-/

namespace Mettapedia.Hyperseed

open Mettapedia.Logic
open Mettapedia.Logic.EvidenceClass
open Mettapedia.Logic.PLNWorldModel
open Mettapedia.Logic.PLNWorldModelAdditive
open Mettapedia.Logic.PLNWorldModelFixpointClosure
open Mettapedia.Logic.ConceptOntology

universe u v w

variable {State : Type*} {Query : Type u}
variable {Obs : Type v} {Signal : Type*} {Cost : Type w}
variable [EvidenceType State] [BinaryWorldModel State Query]
variable [Preorder Cost]

/-- Closure generated by a singleton seed query inside one fixed WM state. -/
noncomputable def singletonSeedClosure
    (R : RuleSet State Query) (W : State) (q : Query) : Set Query :=
  leastRuleClosure R W ({q} : Set Query)

/-- Hyperseed available closures re-expressed as a `ConstructionBase`.

The visible phenomena at budget `B` are exactly the Hyperseed queries available
through the current perspective at that budget. The abstract content attached to
one visible query is the rule closure generated from that query as a singleton
seed inside the fixed trace/state `σ`. -/
noncomputable def queryConstructionBaseFromTrace
    (S : SufficientStatisticSurface Obs Query Mettapedia.Logic.EvidenceQuantale.BinaryEvidence)
    (frontier : Obs → Set Query)
    (R : Mettapedia.Hyperseed.RulePool S)
    (σ : Multiset Obs)
    (P : Perspective Query Signal Cost)
    (guard : Set Query) :
    ConstructionBase := by
  letI : EvidenceType (Multiset Obs) :=
    Mettapedia.Logic.PLNWorldModelAdditive.multisetEvidenceType Obs
  letI : BinaryWorldModel (Multiset Obs) Query :=
    Mettapedia.Logic.PLNWorldModelAdditive.worldModelOfAtomicEvidence S.observe
  exact
    { Phenomena := Query
      Abstract := Query
      Indexicality := Cost
      incidence := fun q a => a ∈ singletonSeedClosure R σ q
      visibleAt := fun B => availableClosureFromTrace S frontier R σ P B guard }

@[simp] theorem mem_singletonSeedClosure_iff
    (R : RuleSet State Query) (W : State) (q a : Query) :
    a ∈ singletonSeedClosure R W q ↔
      a ∈ leastRuleClosure R W ({q} : Set Query) :=
  Iff.rfl

@[simp] theorem queryConstructionBaseFromTrace_visibleAt_eq
    (S : SufficientStatisticSurface Obs Query Mettapedia.Logic.EvidenceQuantale.BinaryEvidence)
    (frontier : Obs → Set Query)
    (R : Mettapedia.Hyperseed.RulePool S)
    (σ : Multiset Obs)
    (P : Perspective Query Signal Cost)
    (guard : Set Query)
    (B : Cost) :
    (queryConstructionBaseFromTrace S frontier R σ P guard).visibleAt B =
      availableClosureFromTrace S frontier R σ P B guard := by
  letI : EvidenceType (Multiset Obs) :=
    Mettapedia.Logic.PLNWorldModelAdditive.multisetEvidenceType Obs
  letI : BinaryWorldModel (Multiset Obs) Query :=
    Mettapedia.Logic.PLNWorldModelAdditive.worldModelOfAtomicEvidence S.observe
  rfl

theorem queryConstructionBaseFromTrace_refines_of_le
    (S : SufficientStatisticSurface Obs Query Mettapedia.Logic.EvidenceQuantale.BinaryEvidence)
    (frontier : Obs → Set Query)
    (R : Mettapedia.Hyperseed.RulePool S)
    (σ : Multiset Obs)
    (P : Perspective Query Signal Cost)
    (guard : Set Query)
    {B₁ B₂ : Cost} (hB : B₁ ≤ B₂) :
    (queryConstructionBaseFromTrace S frontier R σ P guard).Refines B₁ B₂ := by
  letI : EvidenceType (Multiset Obs) :=
    Mettapedia.Logic.PLNWorldModelAdditive.multisetEvidenceType Obs
  letI : BinaryWorldModel (Multiset Obs) Query :=
    Mettapedia.Logic.PLNWorldModelAdditive.worldModelOfAtomicEvidence S.observe
  intro q hq
  exact availableClosureFromTrace_mono_budget S frontier R σ P guard hB hq

/-- Stateful Hyperseed available closures re-expressed as a `ConstructionBase`.

The observer's indexicality now includes both the current trace/state and the
budget. Visible phenomena are `(trace, query)` pairs whose query lies in the
state-sensitive available closure of that same trace. -/
noncomputable def statefulQueryConstructionBaseFromTrace
    (S : SufficientStatisticSurface Obs Query Mettapedia.Logic.EvidenceQuantale.BinaryEvidence)
    (frontier : Obs → Set Query)
    (R : Mettapedia.Hyperseed.RulePool S)
    (P : StatefulPerspective (Multiset Obs) Query Signal Cost)
    (guard : Set Query) :
    ConstructionBase := by
  letI : EvidenceType (Multiset Obs) :=
    Mettapedia.Logic.PLNWorldModelAdditive.multisetEvidenceType Obs
  letI : BinaryWorldModel (Multiset Obs) Query :=
    Mettapedia.Logic.PLNWorldModelAdditive.worldModelOfAtomicEvidence S.observe
  exact
    { Phenomena := Multiset Obs × Query
      Abstract := Query
      Indexicality := Multiset Obs × Cost
      incidence := fun w a => a ∈ singletonSeedClosure R w.1 w.2
      visibleAt := fun i =>
        { w | w.1 = i.1 ∧
            w.2 ∈ stateAvailableClosureFromTrace S frontier R i.1 P i.2 guard } }

@[simp] theorem statefulQueryConstructionBaseFromTrace_visibleAt_eq
    (S : SufficientStatisticSurface Obs Query Mettapedia.Logic.EvidenceQuantale.BinaryEvidence)
    (frontier : Obs → Set Query)
    (R : Mettapedia.Hyperseed.RulePool S)
    (P : StatefulPerspective (Multiset Obs) Query Signal Cost)
    (guard : Set Query)
    (σ : Multiset Obs)
    (B : Cost) :
    (statefulQueryConstructionBaseFromTrace S frontier R P guard).visibleAt (σ, B) =
      { w | w.1 = σ ∧
          w.2 ∈ stateAvailableClosureFromTrace S frontier R σ P B guard } := by
  letI : EvidenceType (Multiset Obs) :=
    Mettapedia.Logic.PLNWorldModelAdditive.multisetEvidenceType Obs
  letI : BinaryWorldModel (Multiset Obs) Query :=
    Mettapedia.Logic.PLNWorldModelAdditive.worldModelOfAtomicEvidence S.observe
  rfl

theorem statefulQueryConstructionBaseFromTrace_refines_of_le
    (S : SufficientStatisticSurface Obs Query Mettapedia.Logic.EvidenceQuantale.BinaryEvidence)
    (frontier : Obs → Set Query)
    (R : Mettapedia.Hyperseed.RulePool S)
    (P : StatefulPerspective (Multiset Obs) Query Signal Cost)
    (guard : Set Query)
    (σ : Multiset Obs)
    {B₁ B₂ : Cost} (hB : B₁ ≤ B₂) :
    (statefulQueryConstructionBaseFromTrace S frontier R P guard).Refines (σ, B₁) (σ, B₂) := by
  letI : EvidenceType (Multiset Obs) :=
    Mettapedia.Logic.PLNWorldModelAdditive.multisetEvidenceType Obs
  letI : BinaryWorldModel (Multiset Obs) Query :=
    Mettapedia.Logic.PLNWorldModelAdditive.worldModelOfAtomicEvidence S.observe
  intro w hw
  exact ⟨hw.1, stateAvailableClosureFromTrace_mono_budget S frontier R σ P guard hB hw.2⟩

namespace RegressionBridge

open Regression

/-- One concrete nonempty trace for the Hyperseed regression fixture. -/
def witnessTrace : Multiset AgentObservation := {AgentObservation.pulse}

theorem witnessTrace_nonempty : witnessTrace ≠ 0 := by
  simp [witnessTrace]

/-- Grounded Hyperseed construction base: visible queries are those available
under the grounded perspective at the chosen budget. -/
noncomputable abbrev groundedConstructionBase : ConstructionBase :=
  queryConstructionBaseFromTrace
    agentSurface agentFrontier agentRules witnessTrace groundedQueryPerspective Set.univ

/-- Expansive Hyperseed construction base: the richer perspective exposes the
entire query closure by budget `3`. -/
noncomputable abbrev expansiveConstructionBase : ConstructionBase :=
  queryConstructionBaseFromTrace
    agentSurface agentFrontier agentRules witnessTrace expansiveQueryPerspective Set.univ

/-- Regime-sensitive construction base: the visible query surface depends on
both the current trace and the budget. -/
noncomputable abbrev regimeSensitiveConstructionBase : ConstructionBase :=
  statefulQueryConstructionBaseFromTrace
    agentSurface agentFrontier agentRules regimeSensitiveQueryPerspective Set.univ

/-- Premise focusing on the action-readiness query. -/
def readyToActPremise : Set AgentQuery := {AgentQuery.readyToAct}

theorem sensedSignal_mem_singletonSeedClosure :
    AgentQuery.sensedSignal ∈
      singletonSeedClosure agentRules witnessTrace AgentQuery.sensedSignal := by
  exact
    seed_subset_leastRuleClosure
      (R := agentRules) (W := witnessTrace) (seed := ({AgentQuery.sensedSignal} : Set AgentQuery))
      (by simp)

theorem readyToAct_mem_singletonSeedClosure_sensedSignal :
    AgentQuery.readyToAct ∈
      singletonSeedClosure agentRules witnessTrace AgentQuery.sensedSignal := by
  have hprem : AgentQuery.sensedSignal ∈
      singletonSeedClosure agentRules witnessTrace AgentQuery.sensedSignal :=
    sensedSignal_mem_singletonSeedClosure
  exact
    leastRuleClosure_rule_closed
      (R := agentRules)
      (W := witnessTrace)
      (seed := ({AgentQuery.sensedSignal} : Set AgentQuery))
      sensedSignalToReadyRule_mem_agentRules
      witnessTrace_nonempty
      hprem

theorem awareReady_mem_singletonSeedClosure_sensedSignal :
    AgentQuery.awareReady ∈
      singletonSeedClosure agentRules witnessTrace AgentQuery.sensedSignal := by
  have hprem : AgentQuery.readyToAct ∈
      singletonSeedClosure agentRules witnessTrace AgentQuery.sensedSignal :=
    readyToAct_mem_singletonSeedClosure_sensedSignal
  exact
    leastRuleClosure_rule_closed
      (R := agentRules)
      (W := witnessTrace)
      (seed := ({AgentQuery.sensedSignal} : Set AgentQuery))
      readyToAwareRule_mem_agentRules
      witnessTrace_nonempty
      hprem

theorem readyToAct_mem_singletonSeedClosure_readyToAct :
    AgentQuery.readyToAct ∈
      singletonSeedClosure agentRules witnessTrace AgentQuery.readyToAct := by
  exact
    seed_subset_leastRuleClosure
      (R := agentRules) (W := witnessTrace) (seed := ({AgentQuery.readyToAct} : Set AgentQuery))
      (by simp)

theorem awareReady_mem_singletonSeedClosure_readyToAct :
    AgentQuery.awareReady ∈
      singletonSeedClosure agentRules witnessTrace AgentQuery.readyToAct := by
  have hprem : AgentQuery.readyToAct ∈
      singletonSeedClosure agentRules witnessTrace AgentQuery.readyToAct :=
    readyToAct_mem_singletonSeedClosure_readyToAct
  exact
    leastRuleClosure_rule_closed
      (R := agentRules)
      (W := witnessTrace)
      (seed := ({AgentQuery.readyToAct} : Set AgentQuery))
      readyToAwareRule_mem_agentRules
      witnessTrace_nonempty
      hprem

theorem awareReady_mem_singletonSeedClosure_awareReady
    (σ : Multiset AgentObservation) :
    AgentQuery.awareReady ∈
      singletonSeedClosure agentRules σ AgentQuery.awareReady := by
  exact
    seed_subset_leastRuleClosure
      (R := agentRules) (W := σ) (seed := ({AgentQuery.awareReady} : Set AgentQuery))
      (by simp)

theorem awareReady_not_mem_singletonSeedClosure_readyToAct_empty :
    AgentQuery.awareReady ∉
      singletonSeedClosure agentRules (0 : Multiset AgentObservation) AgentQuery.readyToAct := by
  have hSub :
      singletonSeedClosure agentRules (0 : Multiset AgentObservation) AgentQuery.readyToAct ⊆
        ({AgentQuery.readyToAct} : Set AgentQuery) := by
    exact
      leastRuleClosure_least_of_seed_and_rules
        (R := agentRules)
        (W := (0 : Multiset AgentObservation))
        (seed := ({AgentQuery.readyToAct} : Set AgentQuery))
        (S := ({AgentQuery.readyToAct} : Set AgentQuery))
        (by simp)
        (by
          intro r hr hside hprem
          rcases hr with rfl | rfl <;> simp at hside)
  intro h
  have : AgentQuery.awareReady ∈ ({AgentQuery.readyToAct} : Set AgentQuery) := hSub h
  simp at this

theorem sensedSignal_not_mem_singletonSeedClosure_readyToAct :
    AgentQuery.sensedSignal ∉
      singletonSeedClosure agentRules witnessTrace AgentQuery.readyToAct := by
  have hSub :
      singletonSeedClosure agentRules witnessTrace AgentQuery.readyToAct ⊆
        ({AgentQuery.readyToAct, AgentQuery.awareReady} : Set AgentQuery) := by
    exact
      leastRuleClosure_least_of_seed_and_rules
        (R := agentRules)
        (W := witnessTrace)
        (seed := ({AgentQuery.readyToAct} : Set AgentQuery))
        (S := ({AgentQuery.readyToAct, AgentQuery.awareReady} : Set AgentQuery))
        (by simp)
        (by
          intro r hr hside hprem
          rcases hr with rfl | rfl
          · simp at hprem
          · simp)
  intro h
  have : AgentQuery.sensedSignal ∈ ({AgentQuery.readyToAct, AgentQuery.awareReady} : Set AgentQuery) :=
    hSub h
  simp at this

theorem sensedSignal_mem_visible_grounded_budget1 :
    AgentQuery.sensedSignal ∈
      ((groundedConstructionBase.visibleAt (1 : ℕ)) : Set AgentQuery) := by
  refine ⟨?_, ?_⟩
  · exact sensedSignal_in_closure_of_nonempty witnessTrace_nonempty
  · refine ⟨?_, ?_, by simp⟩
    · exact
        ⟨AgentSignal.surface, by simp [groundedQueryPerspective],
          by simp [groundedQueryPerspective]⟩
    · simp [nearEurycosm, sublevelRegion, groundedQueryPerspective]

theorem readyToAct_not_mem_availableRegion_grounded_budget1 :
    AgentQuery.readyToAct ∉
      availableRegion groundedQueryPerspective 1 Set.univ := by
  intro h
  have hNear :
      AgentQuery.readyToAct ∈ nearEurycosm groundedQueryPerspective 1 := by
    exact availableRegion_subset_nearEurycosm groundedQueryPerspective 1 Set.univ h
  simp [nearEurycosm, sublevelRegion, groundedQueryPerspective] at hNear

theorem readyToAct_not_mem_visible_grounded_budget1 :
    AgentQuery.readyToAct ∉
      ((groundedConstructionBase.visibleAt (1 : ℕ)) : Set AgentQuery) := by
  intro h
  have hAvail :
      AgentQuery.readyToAct ∈
        availableRegion groundedQueryPerspective 1 Set.univ := by
    exact
      availableClosureFromTrace_subset_availableRegion
        agentSurface agentFrontier agentRules witnessTrace groundedQueryPerspective 1 Set.univ h
  exact readyToAct_not_mem_availableRegion_grounded_budget1 hAvail

theorem awareReady_not_mem_visible_grounded_budget1 :
    AgentQuery.awareReady ∉
      ((groundedConstructionBase.visibleAt (1 : ℕ)) : Set AgentQuery) := by
  intro h
  have hMono :
      ((groundedConstructionBase.visibleAt (1 : ℕ)) : Set AgentQuery) ⊆
        ((groundedConstructionBase.visibleAt (2 : ℕ)) : Set AgentQuery) := by
    exact
      queryConstructionBaseFromTrace_refines_of_le
        agentSurface agentFrontier agentRules witnessTrace groundedQueryPerspective Set.univ
        (show (1 : ℕ) ≤ 2 by decide)
  have hTwo : AgentQuery.awareReady ∈
      ((groundedConstructionBase.visibleAt (2 : ℕ)) : Set AgentQuery) := hMono h
  exact awareReady_not_in_availableClosure_grounded_budget2 hTwo

theorem sensedSignal_mem_closureAt_grounded_budget1_readyToAct :
    AgentQuery.sensedSignal ∈
      ((groundedConstructionBase.closureAt (1 : ℕ) readyToActPremise) : Set AgentQuery) := by
  rw [ConstructionBase.mem_closureAt_iff]
  intro x hxVisible hxPrem
  cases x with
  | sensedSignal =>
      simpa [groundedConstructionBase, queryConstructionBaseFromTrace] using
        sensedSignal_mem_singletonSeedClosure
  | readyToAct =>
      exact False.elim (readyToAct_not_mem_visible_grounded_budget1 hxVisible)
  | awareReady =>
      exact False.elim (awareReady_not_mem_visible_grounded_budget1 hxVisible)

theorem sensedSignal_not_mem_fullClosure_readyToAct :
    AgentQuery.sensedSignal ∉
      ((groundedConstructionBase.fullClosure readyToActPremise) : Set AgentQuery) := by
  intro h
  rw [ConstructionBase.mem_fullClosure_iff] at h
  have hPrem : ∀ b, b ∈ readyToActPremise →
      groundedConstructionBase.incidence AgentQuery.readyToAct b := by
    intro b hb
    have hb' : b = AgentQuery.readyToAct := by simpa [readyToActPremise] using hb
    subst hb'
    simpa [groundedConstructionBase, queryConstructionBaseFromTrace] using
      readyToAct_mem_singletonSeedClosure_readyToAct
  have hSense :
      groundedConstructionBase.incidence AgentQuery.readyToAct AgentQuery.sensedSignal :=
    h AgentQuery.readyToAct hPrem
  exact sensedSignal_not_mem_singletonSeedClosure_readyToAct
    (by simpa [groundedConstructionBase, queryConstructionBaseFromTrace] using hSense)

theorem sensedSignal_mem_frontier_grounded_budget1_readyToAct :
    AgentQuery.sensedSignal ∈
      ((groundedConstructionBase.frontierAt (1 : ℕ) readyToActPremise) : Set AgentQuery) := by
  exact
    ⟨sensedSignal_mem_closureAt_grounded_budget1_readyToAct,
      sensedSignal_not_mem_fullClosure_readyToAct⟩

theorem openWorldAt_grounded_budget1_readyToAct :
    groundedConstructionBase.openWorldAt (1 : ℕ) readyToActPremise := by
  intro hEmpty
  have hMember := sensedSignal_mem_frontier_grounded_budget1_readyToAct
  have : AgentQuery.sensedSignal ∈ (∅ : Set AgentQuery) := hEmpty ▸ hMember
  simp at this

theorem sensedSignal_mem_visible_expansive_budget3 :
    AgentQuery.sensedSignal ∈
      ((expansiveConstructionBase.visibleAt (3 : ℕ)) : Set AgentQuery) := by
  show AgentQuery.sensedSignal ∈
    availableClosureFromTrace agentSurface agentFrontier agentRules witnessTrace expansiveQueryPerspective 3 Set.univ
  rw [← closure_eq_availableClosure_expansive_budget3 (σ := witnessTrace)]
  exact sensedSignal_in_closure_of_nonempty witnessTrace_nonempty

theorem readyToAct_mem_visible_expansive_budget3 :
    AgentQuery.readyToAct ∈
      ((expansiveConstructionBase.visibleAt (3 : ℕ)) : Set AgentQuery) := by
  show AgentQuery.readyToAct ∈
    availableClosureFromTrace agentSurface agentFrontier agentRules witnessTrace expansiveQueryPerspective 3 Set.univ
  rw [← closure_eq_availableClosure_expansive_budget3 (σ := witnessTrace)]
  exact readyToAct_in_closure_of_nonempty witnessTrace_nonempty

theorem awareReady_mem_visible_expansive_budget3 :
    AgentQuery.awareReady ∈
      ((expansiveConstructionBase.visibleAt (3 : ℕ)) : Set AgentQuery) := by
  show AgentQuery.awareReady ∈
    availableClosureFromTrace agentSurface agentFrontier agentRules witnessTrace expansiveQueryPerspective 3 Set.univ
  rw [← closure_eq_availableClosure_expansive_budget3 (σ := witnessTrace)]
  exact awareReady_in_closure_of_nonempty witnessTrace_nonempty

theorem visible_expansive_budget3_eq_univ :
    ((expansiveConstructionBase.visibleAt (3 : ℕ)) : Set AgentQuery) = Set.univ := by
  ext q
  constructor
  · intro _hq
    simp
  · intro _hq
    cases q with
    | sensedSignal =>
        exact sensedSignal_mem_visible_expansive_budget3
    | readyToAct =>
        exact readyToAct_mem_visible_expansive_budget3
    | awareReady =>
        exact awareReady_mem_visible_expansive_budget3

theorem thatsAllAt_expansive_budget3_readyToAct :
    expansiveConstructionBase.thatsAllAt (3 : ℕ) readyToActPremise := by
  rw [ConstructionBase.thatsAllAt, ConstructionBase.closureAt,
    ConstructionBase.fullClosure, visible_expansive_budget3_eq_univ]
  simp [fullAttributeClosure]

theorem sensedSignal_mem_visible_regimeSensitive_nonempty_budget3 :
    (witnessTrace, AgentQuery.sensedSignal) ∈
      ((regimeSensitiveConstructionBase.visibleAt (witnessTrace, (3 : ℕ))) :
        Set (Multiset AgentObservation × AgentQuery)) := by
  refine ⟨rfl, ?_⟩
  refine ⟨sensedSignal_in_closure_of_nonempty witnessTrace_nonempty, ?_⟩
  refine ⟨?_, ?_, by simp⟩
  · exact
      ⟨AgentSignal.surface,
        by simp [freezePerspective, regimeSensitiveQueryPerspective, witnessTrace_nonempty],
        by simp [freezePerspective, regimeSensitiveQueryPerspective, witnessTrace_nonempty]⟩
  · simp [nearEurycosm, sublevelRegion,
      freezePerspective, regimeSensitiveQueryPerspective, groundedQueryPerspective]

theorem readyToAct_mem_visible_regimeSensitive_nonempty_budget3 :
    (witnessTrace, AgentQuery.readyToAct) ∈
      ((regimeSensitiveConstructionBase.visibleAt (witnessTrace, (3 : ℕ))) :
        Set (Multiset AgentObservation × AgentQuery)) := by
  refine ⟨rfl, ?_⟩
  refine ⟨readyToAct_in_closure_of_nonempty witnessTrace_nonempty, ?_⟩
  refine ⟨?_, ?_, by simp⟩
  · exact
      ⟨AgentSignal.surface,
        by simp [freezePerspective, regimeSensitiveQueryPerspective, witnessTrace_nonempty],
        by simp [freezePerspective, regimeSensitiveQueryPerspective, witnessTrace_nonempty]⟩
  · simp [nearEurycosm, sublevelRegion,
      freezePerspective, regimeSensitiveQueryPerspective, groundedQueryPerspective]

theorem awareReady_mem_visible_regimeSensitive_nonempty_budget3 :
    (witnessTrace, AgentQuery.awareReady) ∈
      ((regimeSensitiveConstructionBase.visibleAt (witnessTrace, (3 : ℕ))) :
        Set (Multiset AgentObservation × AgentQuery)) := by
  refine ⟨rfl, ?_⟩
  exact awareReady_in_stateAvailableClosure_regimeSensitive_budget3_of_nonempty
    witnessTrace_nonempty

theorem awareReady_mem_closureAt_regimeSensitive_nonempty_budget3_readyToAct :
    AgentQuery.awareReady ∈
      ((regimeSensitiveConstructionBase.closureAt (witnessTrace, (3 : ℕ)) readyToActPremise) :
        Set AgentQuery) := by
  rw [ConstructionBase.mem_closureAt_iff]
  intro w hwVisible _hPrem
  rcases w with ⟨σ, q⟩
  rcases hwVisible with ⟨hσ, hVisible⟩
  subst hσ
  cases q with
  | sensedSignal =>
      exact awareReady_mem_singletonSeedClosure_sensedSignal
  | readyToAct =>
      exact awareReady_mem_singletonSeedClosure_readyToAct
  | awareReady =>
      exact awareReady_mem_singletonSeedClosure_awareReady witnessTrace

theorem awareReady_not_mem_fullClosure_regimeSensitive_readyToAct :
    AgentQuery.awareReady ∉
      ((regimeSensitiveConstructionBase.fullClosure readyToActPremise) : Set AgentQuery) := by
  intro h
  rw [ConstructionBase.mem_fullClosure_iff] at h
  have hPrem :
      ∀ b, b ∈ readyToActPremise →
        regimeSensitiveConstructionBase.incidence
          ((0 : Multiset AgentObservation), AgentQuery.readyToAct) b := by
    intro b hb
    have hb' : b = AgentQuery.readyToAct := by
      simpa [readyToActPremise] using hb
    subst hb'
    exact
      seed_subset_leastRuleClosure
        (R := agentRules)
        (W := (0 : Multiset AgentObservation))
        (seed := ({AgentQuery.readyToAct} : Set AgentQuery))
        (by simp)
  have hAware :
      regimeSensitiveConstructionBase.incidence
        ((0 : Multiset AgentObservation), AgentQuery.readyToAct) AgentQuery.awareReady :=
    h ((0 : Multiset AgentObservation), AgentQuery.readyToAct) hPrem
  exact awareReady_not_mem_singletonSeedClosure_readyToAct_empty hAware

theorem awareReady_mem_frontierAt_regimeSensitive_nonempty_budget3_readyToAct :
    AgentQuery.awareReady ∈
      ((regimeSensitiveConstructionBase.frontierAt (witnessTrace, (3 : ℕ)) readyToActPremise) :
        Set AgentQuery) := by
  exact
    ⟨awareReady_mem_closureAt_regimeSensitive_nonempty_budget3_readyToAct,
      awareReady_not_mem_fullClosure_regimeSensitive_readyToAct⟩

theorem openWorldAt_regimeSensitive_nonempty_budget3_readyToAct :
    regimeSensitiveConstructionBase.openWorldAt (witnessTrace, (3 : ℕ)) readyToActPremise := by
  intro hEmpty
  have hMember :=
    awareReady_mem_frontierAt_regimeSensitive_nonempty_budget3_readyToAct
  have : AgentQuery.awareReady ∈ (∅ : Set AgentQuery) := hEmpty ▸ hMember
  simp at this

end RegressionBridge

end Mettapedia.Hyperseed
