#ifndef CETTA_STATS_H
#define CETTA_STATS_H

#include "atom.h"
#include <stdint.h>

typedef struct Space Space;

typedef enum {
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP = 0,
    CETTA_RUNTIME_COUNTER_BINDINGS_CLONE = 1,
    CETTA_RUNTIME_COUNTER_BINDINGS_ADD = 2,
    CETTA_RUNTIME_COUNTER_BINDINGS_CONSTRAINT_ADD = 3,
    CETTA_RUNTIME_COUNTER_BINDINGS_MERGE = 4,
    CETTA_RUNTIME_COUNTER_RENAME_VARS = 5,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATIONS = 6,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_CANDIDATES = 7,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_LEGACY_CANDIDATES = 8,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_SUBST_CANDIDATES = 9,
    CETTA_RUNTIME_COUNTER_EQ_INDEX_REBUILD = 10,
    CETTA_RUNTIME_COUNTER_TY_INDEX_REBUILD = 11,
    CETTA_RUNTIME_COUNTER_HASHCONS_ATTEMPT = 12,
    CETTA_RUNTIME_COUNTER_HASHCONS_HIT = 13,
    CETTA_RUNTIME_COUNTER_HASHCONS_INSERT = 14,
    CETTA_RUNTIME_COUNTER_HASH_SPACE_EXACT_LOOKUP = 15,
    CETTA_RUNTIME_COUNTER_HASH_SPACE_EXACT_HIT = 16,
    CETTA_RUNTIME_COUNTER_SUBST_QUERY_EXACT_SHORTCUT = 17,
    CETTA_RUNTIME_COUNTER_IMPORTED_BRIDGE_V2_HIT = 18,
    CETTA_RUNTIME_COUNTER_IMPORTED_BRIDGE_V2_FALLBACK = 19,
    CETTA_RUNTIME_COUNTER_SPACE_PUSH = 20,
    CETTA_RUNTIME_COUNTER_SPACE_POP = 21,
    CETTA_RUNTIME_COUNTER_QUEUE_COMPACT = 22,
    CETTA_RUNTIME_COUNTER_REGISTRY_RESOLVE_HIT = 23,
    CETTA_RUNTIME_COUNTER_REGISTRY_RESOLVE_REWRITE = 24,
    CETTA_RUNTIME_COUNTER_REGISTRY_RESOLVE_NOOP = 25,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_SUBST_EMITTED = 26,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_SUBST_CANDIDATE_FALLBACK = 27,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_SUBST_BUCKET_FALLBACK = 28,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY = 29,
    CETTA_RUNTIME_COUNTER_BINDINGS_FREE = 30,
    CETTA_RUNTIME_COUNTER_BINDINGS_NORMALIZE = 31,
    CETTA_RUNTIME_COUNTER_COUNT = 32
} CettaRuntimeCounter;

typedef struct {
    uint64_t counters[CETTA_RUNTIME_COUNTER_COUNT];
} CettaRuntimeStats;

const char *cetta_runtime_counter_name(CettaRuntimeCounter counter);
void cetta_runtime_stats_reset(void);
void cetta_runtime_stats_add(CettaRuntimeCounter counter, uint64_t delta);
void cetta_runtime_stats_snapshot(CettaRuntimeStats *out);
void cetta_runtime_stats_populate_space(Space *space, Arena *a,
                                        const CettaRuntimeStats *stats);

static inline void cetta_runtime_stats_inc(CettaRuntimeCounter counter) {
    cetta_runtime_stats_add(counter, 1);
}

#endif
