import Foet.Theory
import Foet.SumoCore
import Foet.SumoEthicsSig
import Foet.Translation
import Foet.EthicsCore
import Foet.Paradigms
import Foet.UtilitarianToValue
import Foet.VirtueToValue
import Foet.TargetCenteredVirtue
import Foet.ParadigmEquivalence
import Foet.UtilitarianToVirtue
import Foet.Consequentialism
import Foet.HedonisticUtilitarianism
import Foet.ChoicePoint
import Foet.EvaluateTheory
import Foet.EvaluateTheoryParadigms
import Foet.StructuredSentence
import Foet.StructuredParadigms
import Foet.StructuredParadigmEquivalence
import Foet.MoralParadigmEquivalence
import Foet.UtilitarianInDeontology
import Foet.KifKillingStayingStill
import Foet.ExistentialVsSigma
import Foet.GewirthPGC
