import Mettapedia.Logic.HOL.LindenbaumSet

namespace Mettapedia.AutoBooks.Codex.IntuitionisticHOL

open Mettapedia.Logic.HOL

universe u v

variable {Base : Type u} {Const : Ty Base → Type v}

/-!
Typed closed-term equality for the canonical Henkin/Lindenbaum carrier route.

This is intentionally only the quotient core: equality of closed terms at a
fixed type is provability of their HOL equality formula over a closed theory
set.  Higher source interfaces should build on this relation rather than add
new abstract equality assumptions.
-/

/-- Provable equality of closed HOL terms over a closed theory set. -/
def ClosedTermEq (T : ClosedTheorySet Const) {τ : Ty Base}
    (t u : ClosedTerm Const τ) : Prop :=
  ClosedTheorySet.Provable (Const := Const) T (.eq t u)

namespace ClosedTermEq

variable {T : ClosedTheorySet Const}

/-- Package a finite closed-theory derivation as closed-term equality. -/
theorem of_closedTheory {τ : Ty Base} {t u : ClosedTerm Const τ}
    {Δ : ClosedTheory Const}
    (hΔ : ∀ {φ : ClosedFormula Const}, φ ∈ Δ → φ ∈ T)
    (hEq : ExtDerivation Const Δ (.eq t u)) :
    ClosedTermEq (Const := Const) T t u :=
  ClosedTheorySet.provable_of_closedTheory
    (Const := Const) (T := T) (Δ := Δ) hΔ hEq

/-- Reflexivity of provable closed-term equality. -/
theorem refl (T : ClosedTheorySet Const) {τ : Ty Base}
    (t : ClosedTerm Const τ) :
    ClosedTermEq (Const := Const) T t t :=
  of_closedTheory (T := T)
    (Δ := [])
    (by
      intro φ hφ
      cases hφ)
    (.eqRefl t)

/-- Symmetry of provable closed-term equality. -/
theorem symm {τ : Ty Base} {t u : ClosedTerm Const τ} :
    ClosedTermEq (Const := Const) T t u →
      ClosedTermEq (Const := Const) T u t := by
  rintro ⟨Δ, hΔ, hEq⟩
  exact of_closedTheory (T := T) (Δ := Δ)
    (by intro φ hφ; exact hΔ φ hφ)
    (.eqSymm hEq)

/-- Transitivity of provable closed-term equality. -/
theorem trans {τ : Ty Base} {t u w : ClosedTerm Const τ} :
    ClosedTermEq (Const := Const) T t u →
      ClosedTermEq (Const := Const) T u w →
      ClosedTermEq (Const := Const) T t w := by
  rintro ⟨Δ₁, hΔ₁, htu⟩ ⟨Δ₂, hΔ₂, huw⟩
  refine of_closedTheory (T := T) (Δ := Δ₁ ++ Δ₂) ?_ ?_
  · intro φ hφ
    rcases List.mem_append.mp hφ with hφ | hφ
    · exact hΔ₁ φ hφ
    · exact hΔ₂ φ hφ
  · exact
      .eqTrans
        (ExtDerivation.mono
          (Δ := Δ₁) (Δ' := Δ₁ ++ Δ₂) (φ := .eq t u)
          (by
            intro φ hφ
            exact List.mem_append.mpr (.inl hφ))
          htu)
        (ExtDerivation.mono
          (Δ := Δ₂) (Δ' := Δ₁ ++ Δ₂) (φ := .eq u w)
          (by
            intro φ hφ
            exact List.mem_append.mpr (.inr hφ))
          huw)

/-- The per-type closed-term setoid generated by provable equality. -/
def setoid (T : ClosedTheorySet Const) (τ : Ty Base) :
    Setoid (ClosedTerm Const τ) where
  r := ClosedTermEq (Const := Const) T
  iseqv :=
    { refl := refl (Const := Const) T
      symm := symm
      trans := trans }

/-- Closed-term equivalence classes at one HOL type. -/
abbrev Quot (T : ClosedTheorySet Const) (τ : Ty Base) :=
  Quotient (setoid (Const := Const) T τ)

/-- The quotient class of a closed term. -/
def classOf {T : ClosedTheorySet Const} {τ : Ty Base}
    (t : ClosedTerm Const τ) : Quot (Const := Const) T τ :=
  Quotient.mk (setoid (Const := Const) T τ) t

/-- Equality of quotient classes is exactly provable closed-term equality. -/
theorem classOf_eq_iff {τ : Ty Base} {t u : ClosedTerm Const τ} :
    classOf (T := T) t = classOf u ↔
      ClosedTermEq (Const := Const) T t u :=
  Quotient.eq

/-- Equality of closed propositions reflects to the left-to-right implication. -/
theorem prop_imp_left {p q : ClosedFormula Const} :
    ClosedTermEq (Const := Const) T p q →
      ClosedTheorySet.Provable (Const := Const) T (.imp p q) := by
  rintro ⟨Δ, hΔ, hpq⟩
  exact ClosedTheorySet.provable_of_closedTheory
    (Const := Const) (T := T) (Δ := Δ)
    (by intro φ hφ; exact hΔ φ hφ)
    (.eqPropEL hpq)

/-- Equality of closed propositions reflects to the right-to-left implication. -/
theorem prop_imp_right {p q : ClosedFormula Const} :
    ClosedTermEq (Const := Const) T p q →
      ClosedTheorySet.Provable (Const := Const) T (.imp q p) := by
  rintro ⟨Δ, hΔ, hpq⟩
  exact ClosedTheorySet.provable_of_closedTheory
    (Const := Const) (T := T) (Δ := Δ)
    (by intro φ hφ; exact hΔ φ hφ)
    (.eqPropER hpq)

/-- Equality of closed propositions preserves provability/truth in the theory. -/
theorem prop_provable_iff {p q : ClosedFormula Const}
    (hpq : ClosedTermEq (Const := Const) T p q) :
    ClosedTheorySet.Provable (Const := Const) T p ↔
      ClosedTheorySet.Provable (Const := Const) T q := by
  constructor
  · intro hp
    exact ClosedTheorySet.Provable.imp_mp
      (T := T) (φ := p) (ψ := q)
      (prop_imp_left (T := T) hpq) hp
  · intro hq
    exact ClosedTheorySet.Provable.imp_mp
      (T := T) (φ := q) (ψ := p)
      (prop_imp_right (T := T) hpq) hq

/-- The truth predicate induced on the proposition quotient by theory provability. -/
def propTruth {T : ClosedTheorySet Const} :
    Quot (Const := Const) T propTy → Prop :=
  Quotient.lift
    (fun p : ClosedFormula Const =>
      ClosedTheorySet.Provable (Const := Const) T p)
    (by
      intro p q hpq
      exact propext (prop_provable_iff (T := T) hpq))

@[simp] theorem propTruth_classOf {T : ClosedTheorySet Const}
    (p : ClosedFormula Const) :
    propTruth (T := T) (classOf p) =
      ClosedTheorySet.Provable (Const := Const) T p :=
  rfl

/-- Truth of the represented top proposition. -/
theorem propTruth_top_classOf :
    propTruth (T := T) (classOf (.top : ClosedFormula Const)) :=
  ClosedTheorySet.Provable.top T

/-- Canary bridge: truth of proposition classes respects `ClosedTermEq`. -/
theorem propTruth_respects_representatives
    {T : ClosedTheorySet Const} {p q : ClosedFormula Const}
    (hpq : ClosedTermEq (Const := Const) T p q) :
    propTruth (T := T) (classOf p) ↔
      propTruth (T := T) (classOf q) := by
  simpa using prop_provable_iff (T := T) hpq

/-- Equality-formula truth is exactly closed-term equality. -/
theorem propTruth_eq_classOf {τ : Ty Base} {t u : ClosedTerm Const τ} :
    propTruth (T := T) (classOf (.eq t u : ClosedFormula Const)) ↔
      ClosedTermEq (Const := Const) T t u :=
  Iff.rfl

/-- Equality-formula truth is exactly equality of the closed-term quotient
classes.  This is the equality case of the canonical truth lemma. -/
theorem propTruth_eq_iff_classOf_eq {τ : Ty Base} {t u : ClosedTerm Const τ} :
    propTruth (T := T) (classOf (.eq t u : ClosedFormula Const)) ↔
      classOf (T := T) t = classOf u := by
  constructor
  · intro hEq
    exact (classOf_eq_iff (T := T)).2
      ((propTruth_eq_classOf (T := T)).1 hEq)
  · intro hClass
    exact (propTruth_eq_classOf (T := T)).2
      ((classOf_eq_iff (T := T)).1 hClass)

/-- A closed proposition is true exactly when it equals truth in the term quotient. -/
theorem prop_eq_top_iff {p : ClosedFormula Const} :
    ClosedTermEq (Const := Const) T p (.top : ClosedFormula Const) ↔
      ClosedTheorySet.Provable (Const := Const) T p := by
  constructor
  · intro hpTop
    exact (prop_provable_iff (T := T) hpTop).2
      (ClosedTheorySet.Provable.top T)
  · intro hp
    rcases hp with ⟨Δ, hΔ, hp⟩
    refine of_closedTheory (T := T) (Δ := Δ) ?_ ?_
    · intro φ hφ
      exact hΔ φ hφ
    · refine .eqPropI ?_ ?_
      · exact .impI .topI
      · refine .impI ?_
        exact ExtDerivation.mono
          (Δ := Δ) (Δ' := (.top : ClosedFormula Const) :: Δ) (φ := p)
          (by
            intro φ hφ
            exact List.mem_cons_of_mem _ hφ)
          hp

/-- Truth of a represented proposition is equality with the top class. -/
theorem propTruth_classOf_iff_eq_top {p : ClosedFormula Const} :
    propTruth (T := T) (classOf p) ↔
      classOf (T := T) p = classOf (.top : ClosedFormula Const) := by
  constructor
  · intro hp
    exact (classOf_eq_iff (T := T)).2 ((prop_eq_top_iff (T := T)).2 hp)
  · intro hp
    exact (prop_eq_top_iff (T := T)).1 ((classOf_eq_iff (T := T)).1 hp)

/-- Quotient-level truth is equality with the top proposition class. -/
theorem propTruth_iff_eq_top (a : Quot (Const := Const) T propTy) :
    propTruth (T := T) a ↔
      a = classOf (T := T) (.top : ClosedFormula Const) := by
  refine Quotient.inductionOn a ?_
  intro p
  exact propTruth_classOf_iff_eq_top (T := T) (p := p)

/-- Conjunction truth for represented closed propositions. -/
theorem propTruth_and_classOf {p q : ClosedFormula Const} :
    propTruth (T := T) (classOf (.and p q : ClosedFormula Const)) ↔
      propTruth (T := T) (classOf p) ∧
        propTruth (T := T) (classOf q) := by
  constructor
  · intro hpq
    constructor
    · exact ClosedTheorySet.Provable.imp_mp
        (T := T) (φ := .and p q) (ψ := p)
        (ClosedTheorySet.Provable.and_left T p q) hpq
    · exact ClosedTheorySet.Provable.imp_mp
        (T := T) (φ := .and p q) (ψ := q)
        (ClosedTheorySet.Provable.and_right T p q) hpq
  · intro hpq
    exact ClosedTheorySet.provable_and_intro
      (Const := Const) (T := T) hpq.1 hpq.2

/-- Implication truth eliminates against truth of its antecedent. -/
theorem propTruth_imp_elim_classOf {p q : ClosedFormula Const} :
    propTruth (T := T) (classOf (.imp p q : ClosedFormula Const)) →
      propTruth (T := T) (classOf p) →
      propTruth (T := T) (classOf q) := by
  intro hpq hp
  exact ClosedTheorySet.Provable.imp_mp
    (T := T) (φ := p) (ψ := q) hpq hp

/-- Left disjunction introduction for proposition truth. -/
theorem propTruth_or_intro_left_classOf {p q : ClosedFormula Const} :
    propTruth (T := T) (classOf p) →
      propTruth (T := T) (classOf (.or p q : ClosedFormula Const)) := by
  intro hp
  exact ClosedTheorySet.provable_or_intro_left
    (Const := Const) (T := T) (φ := p) (ψ := q) hp

/-- Right disjunction introduction for proposition truth. -/
theorem propTruth_or_intro_right_classOf {p q : ClosedFormula Const} :
    propTruth (T := T) (classOf q) →
      propTruth (T := T) (classOf (.or p q : ClosedFormula Const)) := by
  intro hq
  exact ClosedTheorySet.provable_or_intro_right
    (Const := Const) (T := T) (φ := p) (ψ := q) hq

/-- Negation truth and proposition truth derive bottom truth. -/
theorem propTruth_not_elim_classOf {p : ClosedFormula Const} :
    propTruth (T := T) (classOf (.not p : ClosedFormula Const)) →
      propTruth (T := T) (classOf p) →
      propTruth (T := T) (classOf (.bot : ClosedFormula Const)) := by
  intro hnot hp
  exact ClosedTheorySet.provable_bot_of_not
    (Const := Const) (T := T) (φ := p) hnot hp

/-- Bottom truth proves negation truth for every represented proposition. -/
theorem propTruth_not_of_bot_classOf {p : ClosedFormula Const} :
    propTruth (T := T) (classOf (.bot : ClosedFormula Const)) →
      propTruth (T := T) (classOf (.not p : ClosedFormula Const)) := by
  intro hbot
  exact ClosedTheorySet.provable_not_of_bot
    (Const := Const) (T := T) (φ := p) hbot

/-- In a canonical world, quotient truth of a represented proposition is
membership in the world's saturated carrier. -/
theorem propTruth_world_iff_mem
    (W : ClosedTheorySet.World Const) (p : ClosedFormula Const) :
    propTruth (T := W.carrier) (classOf p) ↔ p ∈ W.carrier := by
  constructor
  · intro hp
    exact ClosedTheorySet.World.mem_of_provable (W := W) hp
  · intro hp
    exact ClosedTheorySet.provable_of_mem (Const := Const) hp

/-- Top is true in every canonical world. -/
theorem propTruth_top_world_classOf (W : ClosedTheorySet.World Const) :
    propTruth
      (T := W.carrier)
      (classOf (.top : ClosedFormula Const)) :=
  propTruth_top_classOf (T := W.carrier)

/-- Top belongs to every canonical world. -/
theorem top_mem_world (W : ClosedTheorySet.World Const) :
    (.top : ClosedFormula Const) ∈ W.carrier :=
  ClosedTheorySet.World.top_mem (W := W)

/-- Consistency of canonical worlds makes bottom false for quotient truth. -/
theorem propTruth_bot_not_world (W : ClosedTheorySet.World Const) :
    ¬ propTruth
      (T := W.carrier)
      (classOf (.bot : ClosedFormula Const)) := by
  intro hbot
  exact ClosedTheorySet.World.bot_not_mem (W := W)
    ((propTruth_world_iff_mem (Const := Const) W (.bot : ClosedFormula Const)).1 hbot)

/-- Bottom truth in a canonical world is equivalent to falsity. -/
theorem propTruth_bot_world_iff_false (W : ClosedTheorySet.World Const) :
    propTruth
        (T := W.carrier)
        (classOf (.bot : ClosedFormula Const)) ↔
      False := by
  constructor
  · intro hbot
    exact propTruth_bot_not_world (Const := Const) W hbot
  · intro hfalse
    cases hfalse

/-- Bottom membership in a canonical world is equivalent to falsity. -/
theorem bot_mem_world_iff_false (W : ClosedTheorySet.World Const) :
    (.bot : ClosedFormula Const) ∈ W.carrier ↔ False := by
  constructor
  · intro hbot
    exact ClosedTheorySet.World.bot_not_mem (W := W) hbot
  · intro hfalse
    cases hfalse

/-- Canonical-world conjunction truth is componentwise truth. -/
theorem propTruth_and_world_classOf
    (W : ClosedTheorySet.World Const) {p q : ClosedFormula Const} :
    propTruth
        (T := W.carrier)
        (classOf (.and p q : ClosedFormula Const)) ↔
      propTruth (T := W.carrier) (classOf p) ∧
        propTruth (T := W.carrier) (classOf q) :=
  propTruth_and_classOf (T := W.carrier)

/-- Canonical-world conjunction membership is componentwise membership. -/
theorem and_mem_world_iff
    (W : ClosedTheorySet.World Const) {p q : ClosedFormula Const} :
    (.and p q : ClosedFormula Const) ∈ W.carrier ↔
      p ∈ W.carrier ∧ q ∈ W.carrier := by
  constructor
  · intro hpq
    exact ⟨ClosedTheorySet.World.and_left_mem (W := W) hpq,
      ClosedTheorySet.World.and_right_mem (W := W) hpq⟩
  · intro hpq
    exact ClosedTheorySet.World.and_mem (W := W) hpq.1 hpq.2

/-- Local implication truth in a canonical world eliminates against local
antecedent truth.  This is the one-world elimination half, not a full Kripke
implication truth clause. -/
theorem propTruth_imp_elim_world_classOf
    (W : ClosedTheorySet.World Const) {p q : ClosedFormula Const} :
    propTruth
        (T := W.carrier)
        (classOf (.imp p q : ClosedFormula Const)) →
      propTruth (T := W.carrier) (classOf p) →
      propTruth (T := W.carrier) (classOf q) :=
  propTruth_imp_elim_classOf (T := W.carrier)

/-- Local implication membership in a canonical world eliminates against local
antecedent membership. -/
theorem imp_mem_world_elim
    (W : ClosedTheorySet.World Const) {p q : ClosedFormula Const} :
    (.imp p q : ClosedFormula Const) ∈ W.carrier →
      p ∈ W.carrier →
      q ∈ W.carrier :=
  ClosedTheorySet.World.mp (W := W)

/-- Canonical-world equality truth is exactly closed-term equality over the
world carrier. -/
theorem propTruth_eq_world_classOf
    (W : ClosedTheorySet.World Const) {τ : Ty Base}
    {t u : ClosedTerm Const τ} :
    propTruth
        (T := W.carrier)
        (classOf (.eq t u : ClosedFormula Const)) ↔
      ClosedTermEq (Const := Const) W.carrier t u :=
  propTruth_eq_classOf (T := W.carrier)

/-- Canonical-world equality truth is exactly equality of closed-term quotient
classes over the world carrier. -/
theorem propTruth_eq_world_iff_classOf_eq
    (W : ClosedTheorySet.World Const) {τ : Ty Base}
    {t u : ClosedTerm Const τ} :
    propTruth
        (T := W.carrier)
        (classOf (.eq t u : ClosedFormula Const)) ↔
      classOf (T := W.carrier) t = classOf u :=
  propTruth_eq_iff_classOf_eq (T := W.carrier)

/-- Equality-formula membership in a canonical world is exactly closed-term
equality over the world carrier. -/
theorem eq_mem_world_iff_closedTermEq
    (W : ClosedTheorySet.World Const) {τ : Ty Base}
    {t u : ClosedTerm Const τ} :
    (.eq t u : ClosedFormula Const) ∈ W.carrier ↔
      ClosedTermEq (Const := Const) W.carrier t u := by
  constructor
  · intro hmem
    exact (propTruth_eq_world_classOf (Const := Const) W).1
      ((propTruth_world_iff_mem (Const := Const) W (.eq t u : ClosedFormula Const)).2 hmem)
  · intro hEq
    exact (propTruth_world_iff_mem (Const := Const) W (.eq t u : ClosedFormula Const)).1
      ((propTruth_eq_world_classOf (Const := Const) W).2 hEq)

/-- Equality-formula membership in a canonical world is exactly equality of
closed-term quotient classes. -/
theorem eq_mem_world_iff_classOf_eq
    (W : ClosedTheorySet.World Const) {τ : Ty Base}
    {t u : ClosedTerm Const τ} :
    (.eq t u : ClosedFormula Const) ∈ W.carrier ↔
      classOf (T := W.carrier) t = classOf u := by
  constructor
  · intro hmem
    exact (propTruth_eq_world_iff_classOf_eq (Const := Const) W).1
      ((propTruth_world_iff_mem (Const := Const) W (.eq t u : ClosedFormula Const)).2 hmem)
  · intro hClass
    exact (propTruth_world_iff_mem (Const := Const) W (.eq t u : ClosedFormula Const)).1
      ((propTruth_eq_world_iff_classOf_eq (Const := Const) W).2 hClass)

/-- Prime canonical worlds reflect disjunction truth to one of its disjuncts. -/
theorem propTruth_or_world_classOf
    (W : ClosedTheorySet.World Const) {p q : ClosedFormula Const} :
    propTruth
        (T := W.carrier)
        (classOf (.or p q : ClosedFormula Const)) ↔
      propTruth (T := W.carrier) (classOf p) ∨
        propTruth (T := W.carrier) (classOf q) := by
  constructor
  · intro hpq
    have hmem :
        (.or p q : ClosedFormula Const) ∈ W.carrier :=
      (propTruth_world_iff_mem (Const := Const) W (.or p q : ClosedFormula Const)).1 hpq
    rcases W.prime_or hmem with hp | hq
    · exact .inl
        ((propTruth_world_iff_mem (Const := Const) W p).2 hp)
    · exact .inr
        ((propTruth_world_iff_mem (Const := Const) W q).2 hq)
  · intro hpq
    rcases hpq with hp | hq
    · exact propTruth_or_intro_left_classOf (T := W.carrier) hp
    · exact propTruth_or_intro_right_classOf (T := W.carrier) hq

/-- Prime canonical-world disjunction membership is componentwise alternative
membership. -/
theorem or_mem_world_iff
    (W : ClosedTheorySet.World Const) {p q : ClosedFormula Const} :
    (.or p q : ClosedFormula Const) ∈ W.carrier ↔
      p ∈ W.carrier ∨ q ∈ W.carrier := by
  constructor
  · intro hpq
    exact W.prime_or hpq
  · intro hpq
    rcases hpq with hp | hq
    · exact ClosedTheorySet.World.or_left_mem (W := W) (ψ := q) hp
    · exact ClosedTheorySet.World.or_right_mem (W := W) (φ := p) hq

/-- Universal truth specializes to any closed instance. -/
theorem propTruth_all_elim_classOf {σ : Ty Base}
    {body : Formula Const [σ]} (t : ClosedTerm Const σ) :
    propTruth (T := T) (classOf (.all body : ClosedFormula Const)) →
      propTruth (T := T) (classOf (instantiate (Base := Base) t body)) := by
  intro hAll
  rcases hAll with ⟨Δ, hΔ, hAll⟩
  exact
    ClosedTheorySet.provable_of_closedTheory
      (Const := Const)
      (T := T)
      (Δ := Δ)
      (by intro φ hφ; exact hΔ φ hφ)
      (.allE t hAll)

/-- Any true closed instance introduces existential truth. -/
theorem propTruth_ex_intro_classOf {σ : Ty Base}
    {body : Formula Const [σ]} (t : ClosedTerm Const σ) :
    propTruth (T := T) (classOf (instantiate (Base := Base) t body)) →
      propTruth (T := T) (classOf (.ex body : ClosedFormula Const)) := by
  intro hInst
  rcases hInst with ⟨Δ, hΔ, hInst⟩
  exact
    ClosedTheorySet.provable_of_closedTheory
      (Const := Const)
      (T := T)
      (Δ := Δ)
      (by intro φ hφ; exact hΔ φ hφ)
      (.exI t hInst)

/-- Henkin canonical worlds reflect existential truth to a closed witness. -/
theorem propTruth_ex_world_classOf
    (W : ClosedTheorySet.World Const) {σ : Ty Base}
    {body : Formula Const [σ]} :
    propTruth
        (T := W.carrier)
        (classOf (.ex body : ClosedFormula Const)) ↔
      ∃ t : ClosedTerm Const σ,
        propTruth
          (T := W.carrier)
          (classOf (instantiate (Base := Base) t body)) := by
  constructor
  · intro hEx
    have hmem :
        (.ex body : ClosedFormula Const) ∈ W.carrier :=
      (propTruth_world_iff_mem (Const := Const) W (.ex body : ClosedFormula Const)).1 hEx
    rcases W.exists_witness hmem with ⟨t, ht⟩
    exact ⟨t, (propTruth_world_iff_mem (Const := Const) W
      (instantiate (Base := Base) t body)).2 ht⟩
  · rintro ⟨t, ht⟩
    exact propTruth_ex_intro_classOf (T := W.carrier) (body := body) t ht

/-- Existential membership in a canonical world is exactly membership of a
closed witness instance. -/
theorem ex_mem_world_iff
    (W : ClosedTheorySet.World Const) {σ : Ty Base}
    {body : Formula Const [σ]} :
    (.ex body : ClosedFormula Const) ∈ W.carrier ↔
      ∃ t : ClosedTerm Const σ,
        instantiate (Base := Base) t body ∈ W.carrier := by
  constructor
  · intro hEx
    exact W.exists_witness hEx
  · rintro ⟨t, ht⟩
    exact (propTruth_world_iff_mem (Const := Const) W (.ex body : ClosedFormula Const)).1
      (propTruth_ex_intro_classOf (T := W.carrier) (body := body) t
        ((propTruth_world_iff_mem (Const := Const) W
          (instantiate (Base := Base) t body)).2 ht))

/-- Henkin canonical worlds turn non-truth of a universal into a closed
counterexample. -/
theorem propTruth_all_counterexample_world_classOf
    (W : ClosedTheorySet.World Const) {σ : Ty Base}
    {body : Formula Const [σ]} :
    ¬ propTruth
        (T := W.carrier)
        (classOf (.all body : ClosedFormula Const)) →
      ∃ t : ClosedTerm Const σ,
        ¬ propTruth
          (T := W.carrier)
          (classOf (instantiate (Base := Base) t body)) := by
  intro hAll
  have hAllMem :
      (.all body : ClosedFormula Const) ∉ W.carrier := by
    intro hmem
    exact hAll
      ((propTruth_world_iff_mem (Const := Const) W (.all body : ClosedFormula Const)).2 hmem)
  rcases W.all_counterexample hAllMem with ⟨t, ht⟩
  refine ⟨t, ?_⟩
  intro hInst
  exact ht
    ((propTruth_world_iff_mem (Const := Const) W
      (instantiate (Base := Base) t body)).1 hInst)

/--
If every closed instance of a universal is true in a canonical world, then
truth of the universal cannot fail.  This is the constructive positive half of
the universal truth-lemma interface; a later stability/classical/topological
layer may turn the double negation into direct truth.
-/
theorem propTruth_all_world_notnot_of_forall_instances
    (W : ClosedTheorySet.World Const) {σ : Ty Base}
    {body : Formula Const [σ]} :
    (∀ t : ClosedTerm Const σ,
      propTruth
        (T := W.carrier)
        (classOf (instantiate (Base := Base) t body))) →
      ¬¬ propTruth
        (T := W.carrier)
        (classOf (.all body : ClosedFormula Const)) := by
  intro hInst hNotAll
  rcases propTruth_all_counterexample_world_classOf
      (Const := Const) W hNotAll with ⟨t, ht⟩
  exact ht (hInst t)

/-- Stable universal truth follows from truth of every closed instance. -/
theorem propTruth_all_world_of_stable_forall_instances
    (W : ClosedTheorySet.World Const) {σ : Ty Base}
    {body : Formula Const [σ]}
    (hStable :
      ¬¬ propTruth
        (T := W.carrier)
        (classOf (.all body : ClosedFormula Const)) →
      propTruth
        (T := W.carrier)
        (classOf (.all body : ClosedFormula Const))) :
    (∀ t : ClosedTerm Const σ,
      propTruth
        (T := W.carrier)
        (classOf (instantiate (Base := Base) t body))) →
      propTruth
        (T := W.carrier)
        (classOf (.all body : ClosedFormula Const)) :=
  fun hInst =>
    hStable
      (propTruth_all_world_notnot_of_forall_instances
        (Const := Const) W hInst)

/-- Universal non-membership in a canonical world is exactly the presence of a
closed counterexample instance outside the world. -/
theorem all_not_mem_world_iff_exists_counterexample
    (W : ClosedTheorySet.World Const) {σ : Ty Base}
    {body : Formula Const [σ]} :
    (.all body : ClosedFormula Const) ∉ W.carrier ↔
      ∃ t : ClosedTerm Const σ,
        instantiate (Base := Base) t body ∉ W.carrier := by
  constructor
  · intro hAll
    exact W.all_counterexample hAll
  · rintro ⟨t, ht⟩ hAllMem
    exact ht
      ((propTruth_world_iff_mem (Const := Const) W
        (instantiate (Base := Base) t body)).1
        (propTruth_all_elim_classOf (T := W.carrier) (body := body) t
          ((propTruth_world_iff_mem (Const := Const) W
            (.all body : ClosedFormula Const)).2 hAllMem)))

/--
If every closed universal instance belongs to a canonical world, then membership
of the universal itself cannot fail.
-/
theorem all_mem_world_notnot_of_forall_instances
    (W : ClosedTheorySet.World Const) {σ : Ty Base}
    {body : Formula Const [σ]} :
    (∀ t : ClosedTerm Const σ,
      instantiate (Base := Base) t body ∈ W.carrier) →
      ¬¬ (.all body : ClosedFormula Const) ∈ W.carrier := by
  intro hInst hNotAll
  rcases W.all_counterexample hNotAll with ⟨t, ht⟩
  exact ht (hInst t)

/-- Stable universal membership follows from membership of every closed
instance. -/
theorem all_mem_world_of_stable_forall_instances
    (W : ClosedTheorySet.World Const) {σ : Ty Base}
    {body : Formula Const [σ]}
    (hStable :
      ¬¬ (.all body : ClosedFormula Const) ∈ W.carrier →
        (.all body : ClosedFormula Const) ∈ W.carrier) :
    (∀ t : ClosedTerm Const σ,
      instantiate (Base := Base) t body ∈ W.carrier) →
      (.all body : ClosedFormula Const) ∈ W.carrier :=
  fun hInst =>
    hStable
      (all_mem_world_notnot_of_forall_instances
        (Const := Const) W hInst)

/-! ### Open formulas under closed environments -/

/-- A closed environment for a context is a typed substitution into the empty
context.  This is the canonical way to close an open HOL formula by choosing a
closed representative for each free variable. -/
abbrev ClosedEnv (Const : Ty Base → Type v) (Γ : Ctx Base) :=
  Subst Const Γ ([] : Ctx Base)

namespace ClosedEnv

/-- Extend a closed environment across one newly bound variable by assigning a
closed witness to the head variable. -/
def extend {Γ : Ctx Base} (ρ : ClosedEnv (Base := Base) Const Γ)
    (t : ClosedTerm Const σ) :
    ClosedEnv (Base := Base) Const (σ :: Γ)
  | _, .vz => t
  | _, .vs v => ρ v

end ClosedEnv

/-- Close an open term by substituting a closed environment for its free
variables. -/
def closeTerm {Γ : Ctx Base} (ρ : ClosedEnv (Base := Base) Const Γ)
    (t : Term Const Γ τ) : ClosedTerm Const τ :=
  subst ρ t

/-- Close an open formula by substituting a closed environment for its free
variables. -/
abbrev closeFormula {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ) (φ : Formula Const Γ) :
    ClosedFormula Const :=
  closeTerm ρ φ

@[simp] theorem closeTerm_var {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ) (v : Var Γ τ) :
    closeTerm ρ (.var v : Term Const Γ τ) = ρ v :=
  rfl

@[simp] theorem closeTerm_app {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ)
    (f : Term Const Γ (σ ⇒ τ)) (t : Term Const Γ σ) :
    closeTerm ρ (.app f t) =
      (.app (closeTerm ρ f) (closeTerm ρ t) : ClosedTerm Const τ) :=
  rfl

@[simp] theorem closeFormula_top {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ) :
    closeFormula ρ (.top : Formula Const Γ) =
      (.top : ClosedFormula Const) :=
  rfl

@[simp] theorem closeFormula_and {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ)
    (φ ψ : Formula Const Γ) :
    closeFormula ρ (.and φ ψ) =
      (.and (closeFormula ρ φ) (closeFormula ρ ψ) : ClosedFormula Const) :=
  rfl

@[simp] theorem closeFormula_or {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ)
    (φ ψ : Formula Const Γ) :
    closeFormula ρ (.or φ ψ) =
      (.or (closeFormula ρ φ) (closeFormula ρ ψ) : ClosedFormula Const) :=
  rfl

@[simp] theorem closeFormula_imp {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ)
    (φ ψ : Formula Const Γ) :
    closeFormula ρ (.imp φ ψ) =
      (.imp (closeFormula ρ φ) (closeFormula ρ ψ) : ClosedFormula Const) :=
  rfl

@[simp] theorem closeFormula_not {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ)
    (φ : Formula Const Γ) :
    closeFormula ρ (.not φ) =
      (.not (closeFormula ρ φ) : ClosedFormula Const) :=
  rfl

@[simp] theorem closeFormula_eq {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ)
    (t u : Term Const Γ τ) :
    closeFormula ρ (.eq t u) =
      (.eq (closeTerm ρ t) (closeTerm ρ u) : ClosedFormula Const) :=
  rfl

/-- Instantiating the closed body obtained by lifting an environment is the
same as closing the original body under the environment extended by the chosen
closed witness. -/
@[simp] theorem instantiate_closeTerm_lift
    {Γ : Ctx Base} (ρ : ClosedEnv (Base := Base) Const Γ)
    (t : ClosedTerm Const σ) (u : Term Const (σ :: Γ) τ) :
    instantiate (Base := Base) t
      (subst (Subst.lift (Base := Base) (Const := Const) ρ) u) =
      closeTerm (ClosedEnv.extend ρ t) u := by
  have hcomp :
      (Subst.comp
        (Subst.single (Base := Base) (Const := Const) t)
        (Subst.lift (Base := Base) (Const := Const) ρ) :
        Subst Const (σ :: Γ) []) =
      (ClosedEnv.extend ρ t :
        Subst Const (σ :: Γ) []) := by
    funext α
    funext v
    cases v with
    | vz =>
        rfl
    | vs v =>
        change
          instantiate (Base := Base) t
            (weaken (Base := Base) (Const := Const) (Γ := []) (ρ v)) =
              ρ v
        exact
          instantiate_weaken
            (Base := Base)
            (Const := Const)
            (t := t)
            (u := ρ v)
  unfold instantiate closeTerm
  calc
    subst
        (Subst.single (Base := Base) (Const := Const) t)
        (subst (Subst.lift (Base := Base) (Const := Const) ρ) u) =
      subst
        (Subst.comp
          (Subst.single (Base := Base) (Const := Const) t)
          (Subst.lift (Base := Base) (Const := Const) ρ))
        u := by
          exact subst_comp
            (Base := Base)
            (Const := Const)
            (τs := Subst.single (Base := Base) (Const := Const) t)
            (σs := Subst.lift (Base := Base) (Const := Const) ρ)
            (t := u)
    _ = subst (ClosedEnv.extend ρ t) u := by
          rw [hcomp]

/-- Quotient truth of an open formula under a closed environment. -/
def envSatisfies {Γ : Ctx Base} (T : ClosedTheorySet Const)
    (ρ : ClosedEnv (Base := Base) Const Γ) (φ : Formula Const Γ) : Prop :=
  propTruth (T := T) (classOf (closeFormula ρ φ))

/-- The top formula is satisfied under every closed environment. -/
theorem envSatisfies_top {Γ : Ctx Base}
    (T : ClosedTheorySet Const)
    (ρ : ClosedEnv (Base := Base) Const Γ) :
    envSatisfies (Const := Const) T ρ (.top : Formula Const Γ) :=
  propTruth_top_classOf (T := T)

/-- Conjunction truth under a closed environment is componentwise. -/
theorem envSatisfies_and {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {φ ψ : Formula Const Γ} :
    envSatisfies (Const := Const) T ρ (.and φ ψ) ↔
      envSatisfies (Const := Const) T ρ φ ∧
        envSatisfies (Const := Const) T ρ ψ :=
  propTruth_and_classOf (T := T)

/-- Implication truth under a closed environment eliminates locally. -/
theorem envSatisfies_imp_elim {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {φ ψ : Formula Const Γ} :
    envSatisfies (Const := Const) T ρ (.imp φ ψ) →
      envSatisfies (Const := Const) T ρ φ →
      envSatisfies (Const := Const) T ρ ψ :=
  propTruth_imp_elim_classOf (T := T)

/-- Left disjunction introduction under a closed environment. -/
theorem envSatisfies_or_intro_left {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {φ ψ : Formula Const Γ} :
    envSatisfies (Const := Const) T ρ φ →
      envSatisfies (Const := Const) T ρ (.or φ ψ) :=
  propTruth_or_intro_left_classOf (T := T)

/-- Right disjunction introduction under a closed environment. -/
theorem envSatisfies_or_intro_right {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {φ ψ : Formula Const Γ} :
    envSatisfies (Const := Const) T ρ ψ →
      envSatisfies (Const := Const) T ρ (.or φ ψ) :=
  propTruth_or_intro_right_classOf (T := T)

/-- Negation truth and proposition truth under the same closed environment
derive bottom truth. -/
theorem envSatisfies_not_elim {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {φ : Formula Const Γ} :
    envSatisfies (Const := Const) T ρ (.not φ) →
      envSatisfies (Const := Const) T ρ φ →
      envSatisfies (Const := Const) T ρ (.bot : Formula Const Γ) :=
  propTruth_not_elim_classOf (T := T)

/-- Bottom truth under a closed environment proves negation truth for any
formula in that environment. -/
theorem envSatisfies_not_of_bot {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {φ : Formula Const Γ} :
    envSatisfies (Const := Const) T ρ (.bot : Formula Const Γ) →
      envSatisfies (Const := Const) T ρ (.not φ) :=
  propTruth_not_of_bot_classOf (T := T)

/-- Equality truth under a closed environment is exactly closed-term equality
of the closed instances. -/
theorem envSatisfies_eq_iff_closedTermEq {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {τ : Ty Base} {t u : Term Const Γ τ} :
    envSatisfies (Const := Const) T ρ (.eq t u) ↔
      ClosedTermEq (Const := Const) T (closeTerm ρ t) (closeTerm ρ u) :=
  propTruth_eq_classOf (T := T)

/-- Equality truth under a closed environment is exactly equality of the
closed-term quotient classes of the two closed instances. -/
theorem envSatisfies_eq_iff_classOf_eq {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {τ : Ty Base} {t u : Term Const Γ τ} :
    envSatisfies (Const := Const) T ρ (.eq t u) ↔
      classOf (T := T) (closeTerm ρ t) = classOf (T := T) (closeTerm ρ u) :=
  propTruth_eq_iff_classOf_eq (T := T)

/-- Universal truth under a closed environment specializes to any closed
witness by extending the environment with that witness. -/
theorem envSatisfies_all_elim {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {σ : Ty Base} {body : Formula Const (σ :: Γ)}
    (t : ClosedTerm Const σ) :
    envSatisfies (Const := Const) T ρ (.all body) →
      envSatisfies (Const := Const) T (ClosedEnv.extend ρ t) body := by
  intro hAll
  have hInst :
      propTruth (T := T)
        (classOf (instantiate (Base := Base) t
          (subst (Subst.lift (Base := Base) (Const := Const) ρ) body))) :=
    propTruth_all_elim_classOf
      (T := T)
      (body := subst (Subst.lift (Base := Base) (Const := Const) ρ) body)
      t
      hAll
  simpa [envSatisfies, closeFormula] using hInst

/-- A true closed witness instance introduces existential truth under the
unextended closed environment. -/
theorem envSatisfies_ex_intro {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {σ : Ty Base} {body : Formula Const (σ :: Γ)}
    (t : ClosedTerm Const σ) :
    envSatisfies (Const := Const) T (ClosedEnv.extend ρ t) body →
      envSatisfies (Const := Const) T ρ (.ex body) := by
  intro hBody
  have hInst :
      propTruth (T := T)
        (classOf (instantiate (Base := Base) t
          (subst (Subst.lift (Base := Base) (Const := Const) ρ) body))) := by
    simpa [envSatisfies, closeFormula] using hBody
  exact
    propTruth_ex_intro_classOf
      (T := T)
      (body := subst (Subst.lift (Base := Base) (Const := Const) ρ) body)
      t
      hInst

/-- In a canonical world, environment truth is exactly membership of the
closed instance in the world's carrier.  This is the open-formula truth-lemma
interface for the closed-term quotient layer. -/
theorem envSatisfies_world_iff_mem
    (W : ClosedTheorySet.World Const) {Γ : Ctx Base}
    (ρ : ClosedEnv (Base := Base) Const Γ) (φ : Formula Const Γ) :
    envSatisfies (Const := Const) W.carrier ρ φ ↔
      closeFormula ρ φ ∈ W.carrier :=
  propTruth_world_iff_mem (Const := Const) W (closeFormula ρ φ)

/-- Prime canonical worlds reflect disjunction truth under closed
environments to one of the disjuncts. -/
theorem envSatisfies_or_world
    (W : ClosedTheorySet.World Const) {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {φ ψ : Formula Const Γ} :
    envSatisfies (Const := Const) W.carrier ρ (.or φ ψ) ↔
      envSatisfies (Const := Const) W.carrier ρ φ ∨
        envSatisfies (Const := Const) W.carrier ρ ψ :=
  propTruth_or_world_classOf (Const := Const) W

/-- Henkin canonical worlds reflect existential truth under a closed
environment to a closed witness extending that environment. -/
theorem envSatisfies_ex_world
    (W : ClosedTheorySet.World Const) {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {σ : Ty Base} {body : Formula Const (σ :: Γ)} :
    envSatisfies (Const := Const) W.carrier ρ (.ex body) ↔
      ∃ t : ClosedTerm Const σ,
        envSatisfies (Const := Const) W.carrier
          (ClosedEnv.extend ρ t) body := by
  constructor
  · intro hEx
    have hWitness :
        ∃ t : ClosedTerm Const σ,
          propTruth
            (T := W.carrier)
            (classOf (instantiate (Base := Base) t
              (subst (Subst.lift (Base := Base) (Const := Const) ρ) body))) :=
      (propTruth_ex_world_classOf
        (Const := Const)
        (W := W)
        (body := subst (Subst.lift (Base := Base) (Const := Const) ρ) body)).1 hEx
    rcases hWitness with ⟨t, ht⟩
    exact ⟨t, by simpa [envSatisfies, closeFormula] using ht⟩
  · rintro ⟨t, ht⟩
    have ht' :
        propTruth
          (T := W.carrier)
          (classOf (instantiate (Base := Base) t
            (subst (Subst.lift (Base := Base) (Const := Const) ρ) body))) := by
      simpa [envSatisfies, closeFormula] using ht
    exact
      (propTruth_ex_world_classOf
        (Const := Const)
        (W := W)
        (body := subst (Subst.lift (Base := Base) (Const := Const) ρ) body)).2
        ⟨t, ht'⟩

/-- Henkin canonical worlds turn failure of universal truth under a closed
environment into a closed counterexample extending that environment. -/
theorem envSatisfies_all_counterexample_world
    (W : ClosedTheorySet.World Const) {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {σ : Ty Base} {body : Formula Const (σ :: Γ)} :
    ¬ envSatisfies (Const := Const) W.carrier ρ (.all body) →
      ∃ t : ClosedTerm Const σ,
        ¬ envSatisfies (Const := Const) W.carrier
          (ClosedEnv.extend ρ t) body := by
  intro hAll
  have hCounter :
      ∃ t : ClosedTerm Const σ,
        ¬ propTruth
          (T := W.carrier)
          (classOf (instantiate (Base := Base) t
            (subst (Subst.lift (Base := Base) (Const := Const) ρ) body))) :=
    propTruth_all_counterexample_world_classOf
      (Const := Const)
      (W := W)
      (body := subst (Subst.lift (Base := Base) (Const := Const) ρ) body)
      hAll
  rcases hCounter with ⟨t, ht⟩
  refine ⟨t, ?_⟩
  intro hBody
  exact ht (by simpa [envSatisfies, closeFormula] using hBody)

/--
If every closed extension of an environment satisfies a universal body, then
the universal cannot fail under the original environment.
-/
theorem envSatisfies_all_world_notnot_of_forall_instances
    (W : ClosedTheorySet.World Const) {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {σ : Ty Base} {body : Formula Const (σ :: Γ)} :
    (∀ t : ClosedTerm Const σ,
      envSatisfies (Const := Const) W.carrier
        (ClosedEnv.extend ρ t) body) →
      ¬¬ envSatisfies (Const := Const) W.carrier ρ (.all body) := by
  intro hInst hNotAll
  rcases envSatisfies_all_counterexample_world
      (Const := Const) W hNotAll with ⟨t, ht⟩
  exact ht (hInst t)

/-- Stable universal satisfaction follows from satisfaction of every closed
instance. -/
theorem envSatisfies_all_world_of_stable_forall_instances
    (W : ClosedTheorySet.World Const) {Γ : Ctx Base}
    {ρ : ClosedEnv (Base := Base) Const Γ}
    {σ : Ty Base} {body : Formula Const (σ :: Γ)}
    (hStable :
      ¬¬ envSatisfies (Const := Const) W.carrier ρ (.all body) →
        envSatisfies (Const := Const) W.carrier ρ (.all body)) :
    (∀ t : ClosedTerm Const σ,
      envSatisfies (Const := Const) W.carrier
        (ClosedEnv.extend ρ t) body) →
      envSatisfies (Const := Const) W.carrier ρ (.all body) :=
  fun hInst =>
    hStable
      (envSatisfies_all_world_notnot_of_forall_instances
        (Const := Const) W hInst)

/-- Function-position compatibility for closed application. -/
theorem app_fun {σ τ : Ty Base}
    {f g : ClosedTerm Const (σ ⇒ τ)} (t : ClosedTerm Const σ) :
    ClosedTermEq (Const := Const) T f g →
      ClosedTermEq (Const := Const) T (.app f t) (.app g t) := by
  rintro ⟨Δ, hΔ, hfg⟩
  exact of_closedTheory (T := T) (Δ := Δ)
    (by intro φ hφ; exact hΔ φ hφ)
    (.eqApp t hfg)

/-- Argument-position compatibility for closed application. -/
theorem app_arg {σ τ : Ty Base}
    (f : ClosedTerm Const (σ ⇒ τ)) {t u : ClosedTerm Const σ} :
    ClosedTermEq (Const := Const) T t u →
      ClosedTermEq (Const := Const) T (.app f t) (.app f u) := by
  rintro ⟨Δ, hΔ, htu⟩
  exact of_closedTheory (T := T) (Δ := Δ)
    (by intro φ hφ; exact hΔ φ hφ)
    (.eqAppArg f htu)

/-- Application respects provable equality of both closed representatives. -/
theorem app_congr {σ τ : Ty Base}
    {f g : ClosedTerm Const (σ ⇒ τ)} {t u : ClosedTerm Const σ} :
    ClosedTermEq (Const := Const) T f g →
      ClosedTermEq (Const := Const) T t u →
      ClosedTermEq (Const := Const) T (.app f t) (.app g u) := by
  rintro ⟨Δ₁, hΔ₁, hfg⟩ ⟨Δ₂, hΔ₂, htu⟩
  refine of_closedTheory (T := T) (Δ := Δ₁ ++ Δ₂) ?_ ?_
  · intro φ hφ
    rcases List.mem_append.mp hφ with hφ | hφ
    · exact hΔ₁ φ hφ
    · exact hΔ₂ φ hφ
  · exact
      ExtDerivation.eqAppCongr
        (ExtDerivation.mono
          (Δ := Δ₁) (Δ' := Δ₁ ++ Δ₂) (φ := .eq f g)
          (by
            intro φ hφ
            exact List.mem_append.mpr (.inl hφ))
          hfg)
        (ExtDerivation.mono
          (Δ := Δ₂) (Δ' := Δ₁ ++ Δ₂) (φ := .eq t u)
          (by
            intro φ hφ
            exact List.mem_append.mpr (.inr hφ))
          htu)

/-- Closed application descends to the typed closed-term quotient. -/
def appClass {T : ClosedTheorySet Const} {σ τ : Ty Base} :
    Quot (Const := Const) T (σ ⇒ τ) →
      Quot (Const := Const) T σ →
      Quot (Const := Const) T τ :=
  Quotient.lift₂
    (fun f t => classOf (T := T) (.app f t))
    (by
      intro f g t u hfg htu
      exact Quotient.sound (app_congr (T := T) hfg htu))

@[simp] theorem appClass_classOf
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    (f : ClosedTerm Const (σ ⇒ τ)) (t : ClosedTerm Const σ) :
    appClass (T := T) (classOf f) (classOf t) =
      classOf (T := T) (.app f t) :=
  rfl

/-- Quotient beta for represented closed lambda application. -/
theorem appClass_beta_classOf
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    (body : Term Const [σ] τ) (t : ClosedTerm Const σ) :
    appClass (T := T) (classOf (.lam body)) (classOf t) =
      classOf (T := T) (instantiate (Base := Base) t body) := by
  exact (classOf_eq_iff (T := T)).2
    (of_closedTheory (T := T) (Δ := [])
      (by
        intro φ hφ
        cases hφ)
      (.beta t body))

/-- Quotient eta for represented closed arrows. -/
theorem appClass_eta_classOf
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    (f : ClosedTerm Const (σ ⇒ τ)) :
    classOf (T := T)
        (.lam (.app (weaken (Base := Base) (σ := σ) f) (.var .vz))) =
      classOf (T := T) f := by
  exact (classOf_eq_iff (T := T)).2
    (of_closedTheory (T := T) (Δ := [])
      (by
        intro φ hφ
        cases hφ)
      (.eta f))

/-- A represented closed arrow sends provably equal closed arguments to the same
canonical quotient class.  This is the closed-term carrier source of semantic
argument congruence. -/
theorem appClass_arg_respects_closedTermEq
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    (f : ClosedTerm Const (σ ⇒ τ)) {t u : ClosedTerm Const σ}
    (htu : ClosedTermEq (Const := Const) T t u) :
    appClass (T := T) (classOf f) (classOf t) =
      appClass (T := T) (classOf f) (classOf u) := by
  exact (classOf_eq_iff (T := T)).2 (app_arg (T := T) f htu)

/-- Any quotient-level closed arrow is congruent in its argument for quotient
equality. -/
theorem appClass_argument_congruent
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    (f : Quot (Const := Const) T (σ ⇒ τ))
    {x y : Quot (Const := Const) T σ}
    (hxy : x = y) :
    appClass (T := T) f x = appClass (T := T) f y := by
  exact congrArg (appClass (T := T) f) hxy

/-- The canonical closed-term carrier supplies the argument-congruence law for
closed arrows. -/
theorem closedTermCarrier_eqvArgumentCongruent
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    (f : Quot (Const := Const) T (σ ⇒ τ)) :
    ∀ {x y : Quot (Const := Const) T σ},
      x = y →
        appClass (T := T) f x = appClass (T := T) f y := by
  intro x y hxy
  exact appClass_argument_congruent (T := T) f hxy

/-- Canary: quotient application respects changes of both representatives. -/
theorem appClass_respects_representatives
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    {f g : ClosedTerm Const (σ ⇒ τ)} {t u : ClosedTerm Const σ}
    (hfg : ClosedTermEq (Const := Const) T f g)
    (htu : ClosedTermEq (Const := Const) T t u) :
    appClass (T := T) (classOf f) (classOf t) =
      appClass (T := T) (classOf g) (classOf u) := by
  exact congrArg₂ (appClass (T := T))
    ((classOf_eq_iff (T := T)).2 hfg)
    ((classOf_eq_iff (T := T)).2 htu)

/-- A quotient value is represented by a closed term when it is that term's
canonical equivalence class. -/
def QuotRepresentsClosedTerm
    {T : ClosedTheorySet Const} {τ : Ty Base}
    (t : ClosedTerm Const τ) (x : Quot (Const := Const) T τ) : Prop :=
  x = classOf (T := T) t

/-- A quotient value is represented when it has some closed-term representative. -/
def QuotRepresentedValue
    {T : ClosedTheorySet Const} {τ : Ty Base}
    (x : Quot (Const := Const) T τ) : Prop :=
  ∃ t : ClosedTerm Const τ,
    QuotRepresentsClosedTerm (Const := Const) (T := T) t x

@[simp] theorem quotRepresentsClosedTerm_classOf
    {T : ClosedTheorySet Const} {τ : Ty Base}
    (t : ClosedTerm Const τ) :
    QuotRepresentsClosedTerm (Const := Const) (T := T) t (classOf t) :=
  rfl

theorem quotRepresentedValue_classOf
    {T : ClosedTheorySet Const} {τ : Ty Base}
    (t : ClosedTerm Const τ) :
    QuotRepresentedValue (Const := Const) (T := T) (classOf t) :=
  ⟨t, quotRepresentsClosedTerm_classOf (T := T) t⟩

/-- Every value of the closed-term quotient carrier is represented by a closed
term.  This is the concrete canonical-carrier fact that is unavailable in an
arbitrary raw `PreModel`. -/
theorem quotRepresentedValue
    {T : ClosedTheorySet Const} {τ : Ty Base}
    (x : Quot (Const := Const) T τ) :
    QuotRepresentedValue (Const := Const) (T := T) x := by
  refine Quotient.inductionOn x ?_
  intro t
  exact quotRepresentedValue_classOf (T := T) t

/-- Closed application preserves quotient-side closed-term representation. -/
theorem quotRepresentsClosedTerm_app
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    {F : ClosedTerm Const (σ ⇒ τ)} {t : ClosedTerm Const σ}
    {f : Quot (Const := Const) T (σ ⇒ τ)}
    {x : Quot (Const := Const) T σ}
    (hF : QuotRepresentsClosedTerm (Const := Const) (T := T) F f)
    (hx : QuotRepresentsClosedTerm (Const := Const) (T := T) t x) :
    QuotRepresentsClosedTerm (Const := Const) (T := T)
      (.app F t) (appClass (T := T) f x) := by
  unfold QuotRepresentsClosedTerm at hF hx ⊢
  rw [hF, hx]
  rfl

/-- A quotient-level arrow is realized when it respects equality of quotient
arguments. -/
def QuotRealizedArrow
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    (f : Quot (Const := Const) T (σ ⇒ τ)) : Prop :=
  ∀ {x y : Quot (Const := Const) T σ},
    x = y → appClass (T := T) f x = appClass (T := T) f y

/-- Every quotient-level arrow value is realized. -/
def QuotRealizedArrowAdmissible
    (T : ClosedTheorySet Const) : Prop :=
  ∀ {σ τ : Ty Base} (f : Quot (Const := Const) T (σ ⇒ τ)),
    QuotRealizedArrow (Const := Const) (T := T) f

/-- Laws showing that the canonical closed-term quotient carrier is controlled
by closed-term representatives.  These are the quotient-side analogue of the
represented semantic carrier laws used in the `PreModel` bridge. -/
structure QuotRepresentedCarrierLaws
    (T : ClosedTheorySet Const) : Prop where
  all_values_represented :
    ∀ {τ : Ty Base} (x : Quot (Const := Const) T τ),
      QuotRepresentedValue (Const := Const) (T := T) x
  eq_reflects_closedTermEq :
    ∀ {τ : Ty Base} {t u : ClosedTerm Const τ}
      {x y : Quot (Const := Const) T τ},
      QuotRepresentsClosedTerm (Const := Const) (T := T) t x →
      QuotRepresentsClosedTerm (Const := Const) (T := T) u y →
      x = y →
        ClosedTermEq (Const := Const) T t u
  closedTermEq_sound :
    ∀ {τ : Ty Base} {t u : ClosedTerm Const τ}
      {x y : Quot (Const := Const) T τ},
      QuotRepresentsClosedTerm (Const := Const) (T := T) t x →
      QuotRepresentsClosedTerm (Const := Const) (T := T) u y →
      ClosedTermEq (Const := Const) T t u →
        x = y

/-- The canonical closed-term quotient carrier satisfies the represented
carrier laws outright. -/
theorem quotRepresentedCarrierLaws
    (T : ClosedTheorySet Const) :
    QuotRepresentedCarrierLaws (Const := Const) T where
  all_values_represented := by
    intro τ x
    exact quotRepresentedValue (T := T) x
  eq_reflects_closedTermEq := by
    intro τ t u x y hx hy hxy
    exact (classOf_eq_iff (T := T)).1 (by
      rw [← hx, ← hy]
      exact hxy)
  closedTermEq_sound := by
    intro τ t u x y hx hy htu
    rw [hx, hy]
    exact (classOf_eq_iff (T := T)).2 htu

/-- The represented-carrier laws of the quotient source realized-arrow
admissibility by applying a closed representative arrow to represented
arguments. -/
theorem quotRepresentedCarrierLaws_realizedArrowAdmissible
    {T : ClosedTheorySet Const}
    (h : QuotRepresentedCarrierLaws (Const := Const) T) :
    QuotRealizedArrowAdmissible (Const := Const) T := by
  intro σ τ f x y hxy
  rcases h.all_values_represented f with ⟨F, hF⟩
  rcases h.all_values_represented x with ⟨tx, htx⟩
  rcases h.all_values_represented y with ⟨ty, hty⟩
  have hxyClosed : ClosedTermEq (Const := Const) T tx ty :=
    h.eq_reflects_closedTermEq htx hty hxy
  have hAppClosed :
      ClosedTermEq (Const := Const) T (.app F tx) (.app F ty) :=
    app_arg (T := T) F hxyClosed
  exact h.closedTermEq_sound
    (quotRepresentsClosedTerm_app (T := T) hF htx)
    (quotRepresentsClosedTerm_app (T := T) hF hty)
    hAppClosed

/-- Canonical quotient arrows are realized. -/
theorem quotRealizedArrowAdmissible
    (T : ClosedTheorySet Const) :
    QuotRealizedArrowAdmissible (Const := Const) T :=
  quotRepresentedCarrierLaws_realizedArrowAdmissible
    (T := T) (quotRepresentedCarrierLaws (Const := Const) T)

/-- The existing quotient argument-congruence theorem follows from the
represented-carrier laws of the canonical quotient source. -/
theorem closedTermCarrier_eqvArgumentCongruent_from_laws
    {T : ClosedTheorySet Const} {σ τ : Ty Base}
    (f : Quot (Const := Const) T (σ ⇒ τ)) :
    ∀ {x y : Quot (Const := Const) T σ},
      x = y →
        appClass (T := T) f x = appClass (T := T) f y := by
  intro x y hxy
  exact quotRealizedArrowAdmissible (Const := Const) T f hxy

end ClosedTermEq

end Mettapedia.AutoBooks.Codex.IntuitionisticHOL
