import Mettapedia.Logic.LP.PropositionalChainer
import Mathlib.Data.Finset.Prod

/-!
# Backward Chaining via Forward Chaining

This file formalizes a propositional Horn version of the "backward chaining as
forward chaining" pattern: a query is compiled into demand atoms, and ordinary
forward saturation propagates those demands and discharges them from facts.

The transformation is close in spirit to the Magic Sets / Magic Templates
lineage for Datalog: make a bottom-up computation goal-directed by materializing
the demand generated by a top-down query.

At this level the "bluebird" / `B` combinator is the implication-composition
spine:

```text
(B → C) → (A → B) → A → C
```

The substantive theorem below is `demandChainerProves_true_iff`: the compiled
demand program proves `Solved target` by the existing forward chainer exactly
when the original Horn program declaratively derives `target`.
-/

namespace Mettapedia.Logic.LP

open scoped Classical

section Bluebird

/-- The `B` combinator, also known as the bluebird: function composition. -/
def bluebird {A B C : Type*} (f : B → C) (g : A → B) : A → C :=
  fun a => f (g a)

/-- The proof-theoretic shape of the bluebird: hypothetical syllogism. -/
theorem bluebird_imp {A B C : Prop} : (B → C) → (A → B) → A → C :=
  fun hBC hAB hA => hBC (hAB hA)

end Bluebird

section DemandHorn

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- Demand atoms used to compile a single backward query into a Horn program.

`need a target` means the top-level query for `target` has generated `a` as a
subgoal. `have a target` means that subgoal has been discharged. `solved target`
marks the final answer.
-/
inductive DemandAtom (α : Type*) where
  | need : α → α → DemandAtom α
  | have : α → α → DemandAtom α
  | solved : α → DemandAtom α
deriving DecidableEq

namespace DemandAtom

instance [Fintype α] [DecidableEq α] : Fintype (DemandAtom α) :=
  { elems :=
      ((Finset.univ.product (Finset.univ : Finset α)).image
        (fun p : α × α => DemandAtom.need p.1 p.2)) ∪
        (((Finset.univ.product (Finset.univ : Finset α)).image
          (fun p : α × α => DemandAtom.have p.1 p.2)) ∪
            ((Finset.univ : Finset α).image DemandAtom.solved))
    complete := by
      intro x
      cases x <;> simp }

end DemandAtom

/-- Seed fact for a demand-driven query. -/
def demandSeed (target : α) : Finset (DemandAtom α) :=
  {DemandAtom.need target target}

/-- A base fact discharges a demanded subgoal. -/
def factDemandRule (target a : α) : PropRule (DemandAtom α) where
  premises := {DemandAtom.need a target}
  head := DemandAtom.have a target

/-- If a rule can prove a demanded head, demand each of its premises. -/
def needDemandRule (target : α) (r : PropRule α) (premise : α) :
    PropRule (DemandAtom α) where
  premises := {DemandAtom.need r.head target}
  head := DemandAtom.need premise target

/-- Once all demanded premises are available, the demanded rule head is available. -/
def haveDemandRule (target : α) (r : PropRule α) : PropRule (DemandAtom α) where
  premises :=
    insert (DemandAtom.need r.head target)
      (r.premises.image fun premise => DemandAtom.have premise target)
  head := DemandAtom.have r.head target

/-- The top-level target is solved once it is available. -/
def solvedDemandRule (target : α) : PropRule (DemandAtom α) where
  premises := {DemandAtom.have target target}
  head := DemandAtom.solved target

/-- Compile an ordinary Horn program and query into a demand-materialized Horn program. -/
def demandProgram (P : PropProgram α) (facts : Finset α) (target : α) :
    PropProgram (DemandAtom α) :=
  (facts.image (factDemandRule target)) ∪
    ((((P.product (Finset.univ : Finset α)).filter
        (fun rp : PropRule α × α => rp.2 ∈ rp.1.premises)).image
          (fun rp : PropRule α × α => needDemandRule target rp.1 rp.2)) ∪
      ((P.image (haveDemandRule target)) ∪ {solvedDemandRule target}))

/-- Boolean query: run the existing forward chainer on the demand program. -/
def demandChainerProves (P : PropProgram α) (facts : Finset α) (target : α) : Bool :=
  chainerProves (demandProgram P facts target) (demandSeed target)
    (DemandAtom.solved target)

/-- Soundness invariant for demand atoms.

Needs are operational obligations and carry no truth claim. Haves and solved
targets must correspond to ordinary derivability in the original Horn program.
-/
def DemandSound (P : PropProgram α) (facts : Finset α) : DemandAtom α → Prop
  | .need _ _ => True
  | .have a _ => Derivable P facts a
  | .solved a => Derivable P facts a

lemma demand_rule_sound (P : PropProgram α) (facts : Finset α) (target : α)
    {r : PropRule (DemandAtom α)}
    (hr : r ∈ demandProgram P facts target)
    (hpre : ∀ b, b ∈ r.premises → DemandSound P facts b) :
    DemandSound P facts r.head := by
  simp only [demandProgram, Finset.mem_union] at hr
  rcases hr with hFact | hRest
  · rcases Finset.mem_image.mp hFact with ⟨a, ha, rfl⟩
    exact Derivable.fact ha
  · rcases hRest with hNeed | hRest
    · rcases Finset.mem_image.mp hNeed with ⟨rp, _hrp, rfl⟩
      trivial
    · rcases hRest with hHave | hSolved
      · rcases Finset.mem_image.mp hHave with ⟨r₀, hr₀, rfl⟩
        refine Derivable.rule hr₀ ?_
        intro b hb
        exact hpre (DemandAtom.have b target)
          (by
            simp only [haveDemandRule, Finset.mem_insert, Finset.mem_image]
            exact Or.inr ⟨b, hb, rfl⟩)
      · simp only [Finset.mem_singleton] at hSolved
        subst r
        exact hpre (DemandAtom.have target target)
          (by simp [solvedDemandRule])

lemma demand_derivable_sound (P : PropProgram α) (facts : Finset α) (target : α)
    {a : DemandAtom α}
    (h : Derivable (demandProgram P facts target) (demandSeed target) a) :
    DemandSound P facts a := by
  induction h with
  | fact ha =>
      simp [demandSeed] at ha
      cases ha
      trivial
  | rule hr hpre ih =>
      exact demand_rule_sound P facts target hr (fun b hb => ih b hb)

lemma demand_need_from_rule (P : PropProgram α) (facts : Finset α) (target : α)
    {r : PropRule α} {premise : α}
    (hNeed : Derivable (demandProgram P facts target) (demandSeed target)
      (DemandAtom.need r.head target))
    (hr : r ∈ P) (hpremise : premise ∈ r.premises) :
    Derivable (demandProgram P facts target) (demandSeed target)
      (DemandAtom.need premise target) := by
  refine Derivable.rule (r := needDemandRule target r premise) ?_ ?_
  · unfold demandProgram
    apply Finset.mem_union.mpr
    right
    apply Finset.mem_union.mpr
    left
    apply Finset.mem_image.mpr
    refine ⟨(r, premise), ?_, rfl⟩
    simp [hr, hpremise]
  · intro b hb
    simp [needDemandRule] at hb
    subst hb
    exact hNeed

lemma demand_have_complete (P : PropProgram α) (facts : Finset α) (target : α) :
    ∀ {a : α},
      Derivable (demandProgram P facts target) (demandSeed target)
        (DemandAtom.need a target) →
      Derivable P facts a →
      Derivable (demandProgram P facts target) (demandSeed target)
        (DemandAtom.have a target)
  | a, hNeed, hDer => by
      induction hDer with
      | fact ha =>
          refine Derivable.rule (r := factDemandRule target _) ?_ ?_
          · unfold demandProgram
            apply Finset.mem_union.mpr
            left
            exact Finset.mem_image.mpr ⟨_, ha, rfl⟩
          · intro b hb
            simp [factDemandRule] at hb
            cases hb
            exact hNeed
      | @rule r hr hpre ih =>
          refine Derivable.rule (r := haveDemandRule target r) ?_ ?_
          · unfold demandProgram
            apply Finset.mem_union.mpr
            right
            apply Finset.mem_union.mpr
            right
            apply Finset.mem_union.mpr
            left
            exact Finset.mem_image.mpr ⟨r, hr, rfl⟩
          · intro b hb
            simp only [haveDemandRule, Finset.mem_insert, Finset.mem_image] at hb
            rcases hb with hbNeed | hbHave
            · cases hbNeed
              exact hNeed
            · rcases hbHave with ⟨premise, hpremise, rfl⟩
              exact ih premise hpremise
                (demand_need_from_rule P facts target hNeed hr hpremise)

theorem demand_solved_iff_derivable
    (P : PropProgram α) (facts : Finset α) (target : α) :
    Derivable (demandProgram P facts target) (demandSeed target)
        (DemandAtom.solved target) ↔
      Derivable P facts target := by
  constructor
  · intro h
    exact demand_derivable_sound P facts target h
  · intro h
    have hNeed :
        Derivable (demandProgram P facts target) (demandSeed target)
          (DemandAtom.need target target) :=
      Derivable.fact (by simp [demandSeed])
    have hHave :
        Derivable (demandProgram P facts target) (demandSeed target)
          (DemandAtom.have target target) :=
      demand_have_complete P facts target hNeed h
    refine Derivable.rule (r := solvedDemandRule target) ?_ ?_
    · simp [demandProgram]
    · intro b hb
      simp [solvedDemandRule] at hb
      subst hb
      exact hHave

/-- Correctness of Nil-style demand materialization at the propositional Horn level. -/
theorem demandChainerProves_true_iff
    (P : PropProgram α) (facts : Finset α) (target : α) :
    demandChainerProves P facts target = true ↔ Derivable P facts target := by
  unfold demandChainerProves
  exact (chainerProves_true_iff (demandProgram P facts target) (demandSeed target)
    (DemandAtom.solved target)).trans (demand_solved_iff_derivable P facts target)

/-! ## Small canaries -/

inductive ChainAtom where
  | a | b | c | d
deriving DecidableEq

namespace ChainAtom

instance : Fintype ChainAtom :=
  { elems := {ChainAtom.a, ChainAtom.b, ChainAtom.c, ChainAtom.d}
    complete := by
      intro x
      cases x <;> simp }

end ChainAtom

def chainProgram : PropProgram ChainAtom :=
  { { premises := {ChainAtom.a}, head := ChainAtom.b },
    { premises := {ChainAtom.b}, head := ChainAtom.c } }

def chainFacts : Finset ChainAtom :=
  {ChainAtom.a}

theorem chain_derives_c : Derivable chainProgram chainFacts ChainAtom.c := by
  refine Derivable.rule
    (r := { premises := {ChainAtom.b}, head := ChainAtom.c }) ?_ ?_
  · simp [chainProgram]
  · intro premise hb
    simp at hb
    subst hb
    refine Derivable.rule
      (r := { premises := {ChainAtom.a}, head := ChainAtom.b }) ?_ ?_
    · simp [chainProgram]
    · intro premise ha
      simp at ha
      subst ha
      exact Derivable.fact (by simp [chainFacts])

theorem chain_demand_chainer_proves_c :
    demandChainerProves chainProgram chainFacts ChainAtom.c = true :=
  (demandChainerProves_true_iff chainProgram chainFacts ChainAtom.c).2 chain_derives_c

def chainReachableABC : Finset ChainAtom :=
  {ChainAtom.a, ChainAtom.b, ChainAtom.c}

theorem chain_d_not_derivable : ¬ Derivable chainProgram chainFacts ChainAtom.d := by
  intro h
  have hmem : ChainAtom.d ∈ chainReachableABC := by
    refine derivable_subset_of_closed chainProgram chainFacts chainReachableABC ?_ ?_
        ChainAtom.d h
    · intro atom ha
      simp [chainFacts, chainReachableABC] at ha ⊢
      exact Or.inl ha
    · intro r hr hsub
      simp [chainProgram] at hr
      rcases hr with hr | hr
      · subst hr
        simp [chainReachableABC]
      · subst hr
        simp [chainReachableABC]
  simp [chainReachableABC] at hmem

theorem chain_demand_chainer_does_not_prove_d :
    demandChainerProves chainProgram chainFacts ChainAtom.d = false := by
  cases h : demandChainerProves chainProgram chainFacts ChainAtom.d
  · rfl
  · exact False.elim
      (chain_d_not_derivable
        ((demandChainerProves_true_iff chainProgram chainFacts ChainAtom.d).1 h))

end DemandHorn

end Mettapedia.Logic.LP
