(* ========================================================================== *)
(* 08_neutrality.mg - AP-GCT Neutrality                                      *)
(* ========================================================================== *)
(* Section 5.1: Per-bit neutrality for sign-invariant views                  *)
(* "Symmetry says: conditional mean is 1/2 (no bias)"                        *)
(* ========================================================================== *)

(* -------------------------------------------------------------------------- *)
(* PART 1: Neutrality Statement (Theorem 5.1)                                *)
(* -------------------------------------------------------------------------- *)

(* For every bit i in [m] and every sign-invariant view I: *)
(* Pr[X_i = 1 | I] = 1/2 almost surely under D_m *)

(* This is the key symmetry result: sign-invariant information about the     *)
(* masked formula carries NO bias about any individual witness bit.          *)

Theorem AP_GCT_neutrality :
  forall m i I,
    (* I is the sigma-algebra generated by sign-invariant functions *)
    i :e m ->
    is_sign_invariant_sigma I m ->
    (* Pr[X_i = 1 | I] = 1/2 a.s. under D_m *)
    True.
Admitted.

(* Proof idea: T_i preserves measure, preserves I, and toggles X_i *)
(* For every I-measurable event B: Pr[X_i=1 AND B] = Pr[X_i=0 AND B] *)

(* -------------------------------------------------------------------------- *)
(* PART 2: Proof via Involution (Lemma 3.6)                                  *)
(* -------------------------------------------------------------------------- *)

(* The promise-preserving involution T_i: *)
(*   - Preserves the sampling measure *)
(*   - Preserves the uniqueness promise *)
(*   - Toggles X_i (the i-th bit of the unique witness) *)
(*   - Fixes any sign-invariant sigma-algebra I *)

Lemma neutrality_via_involution :
  forall m i I B,
    is_sign_invariant_sigma I m ->
    B :e I ->  (* B is I-measurable *)
    (* T_i fixes B: B = T_i(B) *)
    (* T_i toggles X_i *)
    (* Therefore: Pr[X_i=1, B] = Pr[X_i=0, B] *)
    True.
Admitted.

(* Detailed proof sketch: *)
(* 1. T_i is measure-preserving on promise space (Lemma 3.6(i)) *)
(* 2. T_i is a bijection preserving uniqueness (Lemma 3.6(ii)) *)
(* 3. For I-measurable B: since I is sign-invariant, T_i fixes I *)
(* 4. Under T_i: (X_i=1, B) |-> (X_i=0, B) *)
(* 5. Equal measure implies Pr[X_i=1|B] = 1/2 *)

(* -------------------------------------------------------------------------- *)
(* PART 3: Measure-Theoretic Formulation (Appendix A.3)                      *)
(* -------------------------------------------------------------------------- *)

(* Let I be sigma-algebra generated by sign-invariant functions of F^h *)

Theorem neutrality_measure_theoretic :
  forall m i,
    i :e m ->
    (* For every I-measurable event B: *)
    (* Pr[X_i = 1 ∧ B] = Pr[X_i = 0 ∧ B] *)
    True.
Admitted.

(* Since I is T_i-invariant and T_i toggles X_i: *)
(* The sets B ∩ {X_i=1} and B ∩ {X_i=0} have equal measure *)
(* (pair up omega with T_i(omega)) *)

(* Extend by standard disintegration: *)
(* Pr[X_i = 1 | I = value of B] = 1/2 for all atoms *)

(* -------------------------------------------------------------------------- *)
(* PART 4: SILS-Only Predictors (Corollary 5.2)                              *)
(* -------------------------------------------------------------------------- *)

(* Any predictor that uses only SILS features z has no advantage *)

Corollary SILS_only_neutral :
  forall m i g z,
    SILS_extractor z m ->
    (* g : {0,1}^{r(m)} -> {0,1} is any function of SILS only *)
    i :e m ->
    (* Pr[g(z) = X_i] = 1/2 *)
    True.
Admitted.

(* This follows directly from Theorem 5.1 since z generates I *)

(* -------------------------------------------------------------------------- *)
(* PART 5: Limitation of Neutrality (Remark 5.3)                             *)
(* -------------------------------------------------------------------------- *)

(* Neutrality does NOT speak to predictors that also use VV labels (a_i, b) *)
(* For those, we rely on SPARSIFICATION (Section 5.3) *)

(* The VV labels are NOT sign-invariant: *)
(*   - a_i depends on which column of A *)
(*   - b depends on the XOR constraint *)

(* However, sparsification shows that even with VV labels, *)
(* any fixed local per-bit rule has small probability of high bias *)

(* -------------------------------------------------------------------------- *)
(* PART 6: Extension to Full Local Inputs                                    *)
(* -------------------------------------------------------------------------- *)

(* For u = (z, a_i, b), neutrality alone gives: *)
(*   Pr[X_i = 1 | z] = 1/2 *)

(* Combined with sparsification on (a_i, b): *)
(*   For most blocks, Pr[X_i = 1 | u] ≈ 1/2 *)

(* This is what feeds into the Switching-by-Weakness argument *)

(* -------------------------------------------------------------------------- *)
(* PART 7: Exchangeability Observation                                       *)
(* -------------------------------------------------------------------------- *)

(* For fixed u = (z, a_i, b), the involution T_i bijects: *)
(*   (X_i = 0, Y_i = y) <-> (X_i = 1, Y_i = 1-y) *)
(* without changing u or the measure *)

(* Thus (X_i, Y_i) | u is exchangeable: *)
(*   Pr[X_i = 1 | u] = Pr[Y_i = 1 | u] = f_i(u) *)

(* The Bayes rule h*_i(u) = 1[f_i(u) >= 1/2] is optimal for both *)

Lemma calibration_invariance :
  forall m i u,
    (* (X_i, Y_i) | u is exchangeable *)
    (* Bayes optimal for Y_i is also optimal for X_i *)
    True.
Admitted.

(* -------------------------------------------------------------------------- *)
(* END OF 08_neutrality.mg                                                    *)
(* -------------------------------------------------------------------------- *)
