/-
# D-Separation Soundness Infrastructure

This file defines conditional independence of vertex sets in a Bayesian network
using Mathlib's measure-theoretic `CondIndep`, and proves basic properties.

## Main Definitions

- `CondIndepVertices`: Conditional independence of vertex sets X, Y given Z,
  expressed via σ-algebras generated by coordinate projections.

## Main Results

- `condIndepVertices_symm`: Symmetry of conditional independence.
- `condIndepVertices_empty_left/right`: Independence holds trivially when X or Y is empty.
- `condIndepVertices_of_le_left/right`: Monotonicity (subsets preserve independence).

## References

- Koller & Friedman, "Probabilistic Graphical Models" (2009), Chapter 3
- Pearl, "Probabilistic Reasoning in Intelligent Systems" (1988)
-/

import Mettapedia.ProbabilityTheory.BayesianNetworks.BayesianNetwork
import Mettapedia.ProbabilityTheory.BayesianNetworks.DSeparation

open MeasureTheory ProbabilityTheory

namespace Mettapedia.ProbabilityTheory.BayesianNetworks.BayesianNetwork

variable {V : Type*} [Fintype V] [DecidableEq V]
variable (bn : BayesianNetwork V)
variable [∀ v : V, StandardBorelSpace (bn.stateSpace v)]
variable (μ : Measure bn.JointSpace) [IsFiniteMeasure μ]

/-! ## Conditional Independence of Vertex Sets -/

/-- Conditional independence of vertex sets X and Y given Z in a Bayesian network.

This wraps Mathlib's `ProbabilityTheory.CondIndep` using σ-algebras generated by
coordinate projections for each vertex set. -/
def CondIndepVertices (X Y Z : Set V) : Prop :=
  ProbabilityTheory.CondIndep
    (m' := bn.measurableSpaceOfVertices Z)
    (m₁ := bn.measurableSpaceOfVertices X)
    (m₂ := bn.measurableSpaceOfVertices Y)
    (hm' := measurableSpaceOfVertices_le (bn := bn) Z)
    μ

/-! ## Basic Properties -/

omit [DecidableEq V] in
/-- Conditional independence is symmetric in X and Y. -/
theorem condIndepVertices_symm {X Y Z : Set V}
    (h : CondIndepVertices bn μ X Y Z) :
    CondIndepVertices bn μ Y X Z :=
  CondIndep.symm h

omit [DecidableEq V] in
/-- If X is empty, conditional independence holds trivially. -/
theorem condIndepVertices_empty_left (Y Z : Set V) :
    CondIndepVertices bn μ ∅ Y Z := by
  unfold CondIndepVertices
  have h : bn.measurableSpaceOfVertices ∅ = ⊥ := by
    simp [measurableSpaceOfVertices, iSup_of_empty]
  rw [h]
  exact condIndep_bot_left (bn.measurableSpaceOfVertices Y)

omit [DecidableEq V] in
/-- If Y is empty, conditional independence holds trivially. -/
theorem condIndepVertices_empty_right (X Z : Set V) :
    CondIndepVertices bn μ X ∅ Z := by
  exact condIndepVertices_symm bn μ (condIndepVertices_empty_left bn μ X Z)

omit [Fintype V] [DecidableEq V] [∀ (v : V), StandardBorelSpace (bn.stateSpace v)] in
/-- σ-algebra monotonicity: S' ⊆ S → σ(S') ≤ σ(S). -/
theorem measurableSpaceOfVertices_mono {S S' : Set V} (h : S' ⊆ S) :
    bn.measurableSpaceOfVertices S' ≤ bn.measurableSpaceOfVertices S := by
  unfold measurableSpaceOfVertices
  exact iSup_le fun ⟨v, hv⟩ => le_iSup_of_le ⟨v, h hv⟩ le_rfl

omit [DecidableEq V] in
/-- Monotonicity: if X' ⊆ X and X ⫫ Y | Z, then X' ⫫ Y | Z. -/
theorem condIndepVertices_of_le_left {X X' Y Z : Set V} (hXX' : X' ⊆ X)
    (h : CondIndepVertices bn μ X Y Z) :
    CondIndepVertices bn μ X' Y Z := by
  unfold CondIndepVertices at *
  exact condIndep_of_condIndep_of_le_left h (measurableSpaceOfVertices_mono bn hXX')

omit [DecidableEq V] in
/-- Monotonicity: if Y' ⊆ Y and X ⫫ Y | Z, then X ⫫ Y' | Z. -/
theorem condIndepVertices_of_le_right {X Y Y' Z : Set V} (hYY' : Y' ⊆ Y)
    (h : CondIndepVertices bn μ X Y Z) :
    CondIndepVertices bn μ X Y' Z := by
  unfold CondIndepVertices at *
  exact condIndep_of_condIndep_of_le_right h (measurableSpaceOfVertices_mono bn hYY')

/-! ## D-Separation Soundness Interface

This is the standard soundness theorem: **d-separation implies conditional independence**
for measures that satisfy the local Markov property (Koller–Friedman Thm 3.3; Pearl Ch. 3).

We package it as a typeclass so downstream “compiled PLN rules” can demand the theorem
without hard-coding a proof here.
-/

/-- D-separation soundness for a BN and joint measure.

Assuming the local Markov property, d-separation in the graph implies conditional
independence of the corresponding σ-algebras in the joint measure. -/
class DSeparationSoundness {V : Type*} [Fintype V] [DecidableEq V]
    (bn : BayesianNetwork V) [∀ v : V, StandardBorelSpace (bn.stateSpace v)]
    (μ : Measure bn.JointSpace) [IsFiniteMeasure μ]
    [HasLocalMarkovProperty bn μ] : Prop where
  /-- Soundness: d-separation ⇒ conditional independence. -/
  dsep_condIndep :
    ∀ {X Y Z : Set V},
      Mettapedia.ProbabilityTheory.BayesianNetworks.DSeparation.DSeparated bn.graph X Y Z →
        CondIndepVertices bn μ X Y Z

/-- Use d-separation soundness to discharge a conditional-independence obligation. -/
theorem dsep_implies_condIndepVertices
    {V : Type*} [Fintype V] [DecidableEq V]
    (bn : BayesianNetwork V) [∀ v : V, StandardBorelSpace (bn.stateSpace v)]
    (μ : Measure bn.JointSpace) [IsFiniteMeasure μ]
    [HasLocalMarkovProperty bn μ] [DSeparationSoundness bn μ]
    {X Y Z : Set V}
    (h : Mettapedia.ProbabilityTheory.BayesianNetworks.DSeparation.DSeparated bn.graph X Y Z) :
    CondIndepVertices bn μ X Y Z :=
  DSeparationSoundness.dsep_condIndep (bn := bn) (μ := μ) h

end Mettapedia.ProbabilityTheory.BayesianNetworks.BayesianNetwork
