#!/usr/bin/env bash
set -euo pipefail

# Run triangle-free split problems through Vampire -> Dedukti -> Dedukit -> Megalodon
# Assumes triangle_split has been generated by tools/split_ramsey_triangle.py

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SPLIT_DIR="$ROOT/tests/dedukti_bridge/triangle_split"
VAMPIRE="$ROOT/../vampire/build/vampire"
DEDUKIT="$ROOT/../tools/dedukti.py"
PREAMBLE_EGAL="$ROOT/examples/egal/PfgEJun2022Preamble.mgs"
NEQ_LEMMAS="$ROOT/ramsey36/neq_lemmas_pure.mgs"
DK_PRELUDE="$ROOT/tests/dedukti_bridge/dk_prelude.mg"

if [ ! -d "$SPLIT_DIR" ]; then
  echo "Split directory not found: $SPLIT_DIR"
  echo "Generate it with: python3 tools/split_ramsey_triangle.py"
  exit 1
fi

# Caps
: "${DEDUMAXMEM_MB:=8000}"
ulimit -Sv $((DEDUMAXMEM_MB * 1024))

VTIME="${VTIME:-1}"          # per-problem Vampire time limit (seconds)
LIMIT="${LIMIT:-0}"          # process at most LIMIT problems; 0 = all

fail=0
count=0

while IFS= read -r p; do
  base="${p%.p}"
  dk="$base.dk"
  mg="$base.mg"
  combined="$base.combined.mg"
  ((count++))
  if [ "$LIMIT" -ne 0 ] && [ "$count" -gt "$LIMIT" ]; then
    break
  fi
  echo "[${count}] $p"
  # Vampire -> Dedukti
  "$VAMPIRE" -p dedukti --proof_extra full -t "$VTIME" "$p" > "$dk"
  # Dedukit -> Megalodon
  python3 "$DEDUKIT" "$dk" > "$mg"
  cat "$DK_PRELUDE" "$mg" > "$combined"
  # Megalodon check
  if ! "$ROOT/bin/megalodon" -I "$PREAMBLE_EGAL" -I "$NEQ_LEMMAS" "$combined" >/dev/null; then
    echo "  FAILED"
    ((fail++))
  else
    echo "  OK"
  fi
done < <(find "$SPLIT_DIR" -maxdepth 1 -name 'tri_*.p' | sort)

echo "Done. $fail failures out of $count."
if [ "$fail" -ne 0 ]; then
  exit 1
fi
