/-
LLM primer:
- `MarkovParam k` carries init distribution + transition kernels for Fin k
- `MeasurableSpace (MarkovParam k)` = ⨆ over wordProb evaluations (NOT ⊤)
  This makes `wordProb · xs` measurable by construction, and functions INTO
  MarkovParam are measurable iff all wordProb compositions are measurable
- Key API: `measurable_wordProb`, `measurable_into_markovParam`,
  `aemeasurable_into_markovParam`
- `comapMS f m` = pullback σ-algebra {f⁻¹(t) | t ∈ m}
-/
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.Order.Filter.CountableInter

/-!
# Markov de Finetti Hard Base (Active Minimal Surface)

Minimal definitions needed by active Fortini/anchor modules:
`MarkovParam`, `stepProb`, `initProb`, and `wordProb`.

## Measurable Space

The σ-algebra on `MarkovParam k` is generated by `wordProb` evaluations:
```
  ⨆ xs : List (Fin k), comapMS (fun θ => wordProb θ xs) (borel ℝ≥0∞)
```
This is the *coarsest* σ-algebra making every `wordProb · xs` measurable.

**Why not `⊤`?** The discrete σ-algebra `⊤` makes functions FROM `MarkovParam`
trivially measurable but functions INTO it require ALL preimages measurable —
an impossibly strong condition for `Measure.map`. The wordProb-generated
σ-algebra is exactly what integration and `lintegral_map'` need.

## Key API

* `measurable_wordProb` : each `wordProb · xs` is measurable by construction
* `measurable_into_markovParam` : `g` measurable ⟸ all `wordProb ∘ g` measurable
* `aemeasurable_into_markovParam` : `g` AE-measurable ⟸ all `wordProb ∘ g` AE-measurable
-/

set_option autoImplicit false

noncomputable section

namespace Mettapedia.Logic

open MeasureTheory
open scoped NNReal ENNReal

namespace MarkovDeFinettiHard

variable {k : ℕ}

structure MarkovParam (k : ℕ) where
  init : ProbabilityMeasure (Fin k)
  trans : Fin k → ProbabilityMeasure (Fin k)

def stepProb (θ : MarkovParam k) (a b : Fin k) : ℝ≥0 :=
  θ.trans a (Set.singleton b)

def initProb (θ : MarkovParam k) (a : Fin k) : ℝ≥0 :=
  θ.init (Set.singleton a)

def wordProbAux (θ : MarkovParam k) (a : Fin k) : List (Fin k) → ℝ≥0
  | [] => 1
  | b :: xs => stepProb (k := k) θ a b * wordProbAux θ b xs

def wordProbNN (θ : MarkovParam k) : List (Fin k) → ℝ≥0
  | [] => 1
  | a :: xs => initProb (k := k) θ a * wordProbAux (k := k) θ a xs

def wordProb (θ : MarkovParam k) (xs : List (Fin k)) : ℝ≥0∞ :=
  (wordProbNN (k := k) θ xs : ℝ≥0∞)

/-! ## Measurable Space on MarkovParam -/

/-- Pullback σ-algebra: `{f⁻¹(t) | t measurable in m}`. -/
def comapMS {α β : Type*} (f : α → β) (m : MeasurableSpace β) : MeasurableSpace α where
  MeasurableSet' s := ∃ t, @MeasurableSet β m t ∧ f ⁻¹' t = s
  measurableSet_empty := ⟨∅, m.measurableSet_empty, rfl⟩
  measurableSet_compl := by rintro s ⟨t, ht, rfl⟩; exact ⟨tᶜ, ht.compl, rfl⟩
  measurableSet_iUnion := by
    intro g hg; choose t ht heq using hg
    exact ⟨⋃ i, t i, MeasurableSet.iUnion ht, by simp [heq]⟩

/-- The σ-algebra on `MarkovParam k` generated by all `wordProb` evaluations.
    This is the coarsest σ-algebra making every `fun θ => wordProb θ xs` measurable. -/
def markovParamMeasurableSpace (k : ℕ) : MeasurableSpace (MarkovParam k) :=
  ⨆ xs : List (Fin k), comapMS (fun θ => wordProb (k := k) θ xs) inferInstance

instance : MeasurableSpace (MarkovParam k) := markovParamMeasurableSpace k

/-- Each `wordProb · xs` is measurable from `MarkovParam k` (by construction). -/
theorem measurable_wordProb (xs : List (Fin k)) :
    Measurable (fun θ : MarkovParam k => wordProb (k := k) θ xs) := by
  intro s hs
  show @MeasurableSet (MarkovParam k) (markovParamMeasurableSpace k)
    ((fun θ => wordProb (k := k) θ xs) ⁻¹' s)
  have hmem : @MeasurableSet (MarkovParam k)
      (comapMS (fun θ => wordProb (k := k) θ xs) inferInstance)
      ((fun θ => wordProb (k := k) θ xs) ⁻¹' s) := ⟨s, hs, rfl⟩
  exact (le_iSup (fun xs' => comapMS (fun θ => wordProb (k := k) θ xs') inferInstance) xs) _ hmem

/-- A function `g : α → MarkovParam k` is measurable iff every composition
    `fun a => wordProb (g a) xs` is measurable. -/
theorem measurable_into_markovParam {α : Type*} [mα : MeasurableSpace α]
    (g : α → MarkovParam k)
    (h : ∀ xs : List (Fin k),
      Measurable (fun a => wordProb (k := k) (g a) xs)) :
    Measurable g := by
  show markovParamMeasurableSpace k ≤ MeasurableSpace.map g mα
  apply iSup_le
  intro xs s hs
  obtain ⟨t, ht, rfl⟩ := hs
  show @MeasurableSet α mα (g ⁻¹' ((fun θ => wordProb (k := k) θ xs) ⁻¹' t))
  exact h xs ht

/-! ## AE-Measurability into MarkovParam -/

/-- A function `g : α → MarkovParam k` is AE-measurable if every composition
    `fun a => wordProb (g a) xs` is AE-measurable.

    The proof constructs a measurable witness `g'` that equals `g` on a
    full-measure set (where all wordProb compositions agree with their
    measurable AE-representatives) and a fixed `θ₀` on the null set.
    Measurability of `g'` follows from `measurable_into_markovParam`
    since each `wordProb ∘ g'` is a measurable piecewise of the
    AE-representative and a constant. -/
theorem aemeasurable_into_markovParam {α : Type*} [mα : MeasurableSpace α]
    (g : α → MarkovParam k) (μ : Measure α) (θ₀ : MarkovParam k)
    (h : ∀ xs : List (Fin k),
      AEMeasurable (fun a => wordProb (k := k) (g a) xs) μ) :
    AEMeasurable g μ := by
  classical
  -- Combine AE equalities: on a full-measure set, all wordProb compositions
  -- agree with their measurable AE-representatives
  have hae : ∀ᵐ ω ∂μ, ∀ xs : List (Fin k),
      wordProb (k := k) (g ω) xs =
        AEMeasurable.mk (fun a => wordProb (k := k) (g a) xs) (h xs) ω :=
    eventually_countable_forall.mpr (fun xs => AEMeasurable.ae_eq_mk (h xs))
  -- Extract a measurable null set covering the "bad" set
  set N := toMeasurable μ {ω : α | ¬∀ xs : List (Fin k),
    wordProb (k := k) (g ω) xs =
      AEMeasurable.mk (fun a => wordProb (k := k) (g a) xs) (h xs) ω}
  have hN_meas : MeasurableSet N := measurableSet_toMeasurable μ _
  have hN_null : μ N = 0 := by
    rw [measure_toMeasurable]; exact mem_ae_iff.mp hae
  -- Construct measurable witness: g on the good set, θ₀ on the bad set
  set g' : α → MarkovParam k := fun ω => if ω ∈ N then θ₀ else g ω
  -- g' is measurable: each wordProb ∘ g' is a measurable piecewise
  have hg'_meas : @Measurable α (MarkovParam k) mα (markovParamMeasurableSpace k) g' := by
    apply measurable_into_markovParam
    intro xs
    have : (fun ω => wordProb (k := k) (g' ω) xs) =
        N.piecewise (fun _ => wordProb (k := k) θ₀ xs)
          (AEMeasurable.mk (fun a => wordProb (k := k) (g a) xs) (h xs)) := by
      ext ω
      simp only [g', Set.piecewise]
      split_ifs with hN_mem
      · rfl
      · -- ω ∉ N → ω is in the good set → wordProb agrees with mk
        have hgood : ∀ xs : List (Fin k),
            wordProb (k := k) (g ω) xs =
              AEMeasurable.mk (fun a => wordProb (k := k) (g a) xs) (h xs) ω := by
          by_contra h_not
          exact hN_mem (subset_toMeasurable μ _ h_not)
        exact hgood xs
    rw [this]
    exact Measurable.piecewise hN_meas measurable_const (AEMeasurable.measurable_mk (h xs))
  -- g agrees with g' on the full-measure set Nᶜ
  have hae_eq : g =ᵐ[μ] g' := by
    filter_upwards [show Nᶜ ∈ MeasureTheory.ae μ from by rwa [mem_ae_iff, compl_compl]]
    intro ω hω
    show g ω = if ω ∈ N then θ₀ else g ω
    simp [show ω ∉ N from hω]
  exact ⟨g', hg'_meas, hae_eq⟩

end MarkovDeFinettiHard
end Mettapedia.Logic
