import Mettapedia.Logic.MarkovDeFinettiMomentProblem
import Mettapedia.Logic.MarkovDeFinettiSequenceKernel
import Mathlib.Probability.Kernel.IonescuTulcea.Traj
import Mathlib.Probability.Kernel.WithDensity
import Mathlib.Probability.Kernel.Composition.ParallelComp

/-!
# Borel Sequence Kernel of a Markov Parameter

This file builds the measurable kernel
`MarkovParam k → Measure (ℕ → Fin k)` on the **Borel** parameter space.

The active `MarkovParam` measurable space in `MarkovDeFinettiHardBase` is the
coarser σ-algebra generated by the `wordProb` coordinates. For the stronger
sequence-valued kernel, it is safer to work first on the Borel space coming
from compactness of `MarkovParam`, then bridge back at the theorem layer.

The construction carries the parameter through a paired trajectory
`ℕ → (MarkovParam k × Fin k)` and then projects to the state sequence.
-/

set_option autoImplicit false

noncomputable section

namespace Mettapedia.Logic

open MeasureTheory ProbabilityTheory
open Preorder
open scoped ENNReal NNReal
open MarkovDeFinettiHard
open MarkovDeFinettiRecurrence
open MarkovDeFinettiSequenceKernel

namespace MarkovDeFinettiSequenceKernelBorel

local notation "Kernel" => ProbabilityTheory.Kernel
local notation "IsMarkovKernel" => ProbabilityTheory.IsMarkovKernel
local infixl:100 " ∘ₖ " => ProbabilityTheory.Kernel.comp
local infixl:100 " ∥ₖ " => ProbabilityTheory.Kernel.parallelComp

variable {k : ℕ}

local instance : MeasurableSpace (MarkovParam k) := MarkovParam.borelMS (k := k)
local instance : BorelSpace (MarkovParam k) := ⟨rfl⟩

/-- Paired Markov state carrying both the parameter and the current symbol. -/
abbrev PairState (k : ℕ) := MarkovParam k × Fin k

/-- Paired trajectories indexed by time. -/
abbrev PairTrajectory (k : ℕ) := ℕ → PairState k

/-- `Iic`-indexed paired prefixes, matching the `traj` API. -/
abbrev PairPrefix (k : ℕ) (n : ℕ) := ∀ _ : Finset.Iic n, PairState k

/-- Density used to sample the initial state from a Borel Markov parameter. -/
theorem measurable_initWeight (b : Fin k) :
    Measurable (Function.uncurry
      (fun θ : MarkovParam k => fun _ : Fin k => (initProb (k := k) θ b : ℝ≥0∞))) := by
  simpa [Function.uncurry] using
    ((measurable_initProb_borel (k := k) b).coe_nnreal_ennreal.comp measurable_fst)

/-- Density used to sample the next state from a paired Markov state. -/
theorem measurable_stepWeight (b : Fin k) :
    Measurable (Function.uncurry
      (fun x : PairState k => fun _ : Fin k => (stepProb (k := k) x.1 x.2 b : ℝ≥0∞))) := by
  have hpair : Measurable (fun x : PairState k => (stepProb (k := k) x.1 x.2 b : ℝ≥0∞)) := by
    refine measurable_from_prod_countable_left ?_
    intro a
    simpa using (measurable_stepProb_borel (k := k) a b).coe_nnreal_ennreal
  simpa [Function.uncurry] using hpair.comp measurable_fst

/-- Initial-state kernel on the Borel parameter space. -/
noncomputable def markovInitialKernel : Kernel (MarkovParam k) (Fin k) :=
  ∑ b : Fin k,
    ProbabilityTheory.Kernel.withDensity
      (ProbabilityTheory.Kernel.const (MarkovParam k) (Measure.dirac b))
      (fun θ _ => (initProb (k := k) θ b : ℝ≥0∞))

instance markovInitialKernel_isMarkov : IsMarkovKernel (markovInitialKernel (k := k)) := by
  refine ⟨?_⟩
  intro θ
  refine ⟨?_⟩
  rw [markovInitialKernel, ProbabilityTheory.Kernel.finset_sum_apply' Finset.univ
    (fun b : Fin k =>
      ProbabilityTheory.Kernel.withDensity
        (ProbabilityTheory.Kernel.const (MarkovParam k) (Measure.dirac b))
        (fun θ _ => (initProb (k := k) θ b : ℝ≥0∞))) θ Set.univ]
  have hterm : ∀ b : Fin k,
      ProbabilityTheory.Kernel.withDensity
        (ProbabilityTheory.Kernel.const (MarkovParam k) (Measure.dirac b))
        (fun θ _ => (initProb (k := k) θ b : ℝ≥0∞)) θ Set.univ
        = initProb (k := k) θ b := by
    intro b
    rw [ProbabilityTheory.Kernel.withDensity_apply' _
      (measurable_initWeight (k := k) b) θ Set.univ]
    simp [initProb]
  simp_rw [hterm]
  simpa using (initProb_sum_enn (k := k) θ)

/-- The Borel initial kernel evaluates singletons by `initProb`. -/
theorem markovInitialKernel_apply_singleton
    (θ : MarkovParam k) (b : Fin k) :
    markovInitialKernel (k := k) θ ({b} : Set (Fin k)) =
      initProb (k := k) θ b := by
  classical
  rw [markovInitialKernel, ProbabilityTheory.Kernel.finset_sum_apply' Finset.univ
    (fun c : Fin k =>
      ProbabilityTheory.Kernel.withDensity
        (ProbabilityTheory.Kernel.const (MarkovParam k) (Measure.dirac c))
        (fun θ _ => (initProb (k := k) θ c : ℝ≥0∞))) θ ({b} : Set (Fin k))]
  have hterm : ∀ c : Fin k,
      ProbabilityTheory.Kernel.withDensity
        (ProbabilityTheory.Kernel.const (MarkovParam k) (Measure.dirac c))
        (fun θ _ => (initProb (k := k) θ c : ℝ≥0∞)) θ ({b} : Set (Fin k))
        = if c = b then initProb (k := k) θ c else 0 := by
    intro c
    rw [ProbabilityTheory.Kernel.withDensity_apply' _
      (measurable_initWeight (k := k) c) θ ({b} : Set (Fin k))]
    by_cases hc : c = b
    · subst hc
      simp [initProb]
    · simp [hc, initProb]
  simp_rw [hterm]
  rw [Finset.sum_eq_single_of_mem b (Finset.mem_univ b)]
  · simp
  · intro c _ hc
    simp [hc]

/-- Start kernel for the paired trajectory process. -/
noncomputable def markovStartKernel : Kernel (MarkovParam k) (PairState k) :=
  (((ProbabilityTheory.Kernel.id : Kernel (MarkovParam k) (MarkovParam k)) ∥ₖ
      markovInitialKernel) ∘ₖ
    ProbabilityTheory.Kernel.copy (MarkovParam k))

instance markovStartKernel_isMarkov : IsMarkovKernel (markovStartKernel (k := k)) := by
  dsimp [markovStartKernel]
  infer_instance

/-- The paired start kernel keeps the parameter fixed and samples the first state
from `θ.init`. -/
theorem markovStartKernel_apply_singleton_same
    (θ : MarkovParam k) (b : Fin k) :
    markovStartKernel (k := k) θ ({(θ, b)} : Set (PairState k)) =
      initProb (k := k) θ b := by
  have hs :
      ({(θ, b)} : Set (PairState k)) =
        ({θ} : Set (MarkovParam k)) ×ˢ ({b} : Set (Fin k)) := by
    ext z
    simp
  rw [markovStartKernel,
    ProbabilityTheory.Kernel.comp_apply' _ _ _ (MeasurableSet.singleton (θ, b))]
  rw [ProbabilityTheory.Kernel.copy_apply, lintegral_dirac]
  rw [hs, ProbabilityTheory.Kernel.parallelComp_apply_prod]
  simp [ProbabilityTheory.Kernel.id_apply, markovInitialKernel_apply_singleton, initProb]

/-- The paired start kernel cannot change the parameter. -/
theorem markovStartKernel_apply_singleton_of_ne
    (θ θ' : MarkovParam k) (b : Fin k) (h : θ' ≠ θ) :
    markovStartKernel (k := k) θ ({(θ', b)} : Set (PairState k)) = 0 := by
  have hs :
      ({(θ', b)} : Set (PairState k)) =
        ({θ'} : Set (MarkovParam k)) ×ˢ ({b} : Set (Fin k)) := by
    ext z
    simp
  rw [markovStartKernel,
    ProbabilityTheory.Kernel.comp_apply' _ _ _ (MeasurableSet.singleton (θ', b))]
  rw [ProbabilityTheory.Kernel.copy_apply, lintegral_dirac]
  rw [hs, ProbabilityTheory.Kernel.parallelComp_apply_prod]
  have hne : θ ≠ θ' := by
    simpa [eq_comm] using h
  have hid : (ProbabilityTheory.Kernel.id : Kernel (MarkovParam k) (MarkovParam k)) θ
      ({θ'} : Set (MarkovParam k)) = 0 := by
    simp [ProbabilityTheory.Kernel.id_apply, hne]
  rw [hid, zero_mul]

/-- Deterministically keep the parameter while evolving the paired chain. -/
noncomputable def keepParamKernel : Kernel (PairState k) (MarkovParam k) :=
  ProbabilityTheory.Kernel.deterministic Prod.fst measurable_fst

instance keepParamKernel_isMarkov : IsMarkovKernel (keepParamKernel (k := k)) := by
  dsimp [keepParamKernel]
  infer_instance

/-- One-step transition kernel on paired states. -/
noncomputable def markovStepKernel : Kernel (PairState k) (Fin k) :=
  ∑ b : Fin k,
    ProbabilityTheory.Kernel.withDensity
      (ProbabilityTheory.Kernel.const (PairState k) (Measure.dirac b))
      (fun x _ => (stepProb (k := k) x.1 x.2 b : ℝ≥0∞))

instance markovStepKernel_isMarkov : IsMarkovKernel (markovStepKernel (k := k)) := by
  refine ⟨?_⟩
  intro x
  refine ⟨?_⟩
  rw [markovStepKernel, ProbabilityTheory.Kernel.finset_sum_apply' Finset.univ
    (fun b : Fin k =>
      ProbabilityTheory.Kernel.withDensity
        (ProbabilityTheory.Kernel.const (PairState k) (Measure.dirac b))
        (fun x _ => (stepProb (k := k) x.1 x.2 b : ℝ≥0∞))) x Set.univ]
  have hterm : ∀ b : Fin k,
      ProbabilityTheory.Kernel.withDensity
        (ProbabilityTheory.Kernel.const (PairState k) (Measure.dirac b))
        (fun x _ => (stepProb (k := k) x.1 x.2 b : ℝ≥0∞)) x Set.univ
        = stepProb (k := k) x.1 x.2 b := by
    intro b
    rw [ProbabilityTheory.Kernel.withDensity_apply' _
      (measurable_stepWeight (k := k) b) x Set.univ]
    simp [stepProb]
  simp_rw [hterm]
  simpa using (stepProb_sum_enn (k := k) x.1 x.2)

/-- The Borel one-step kernel evaluates singletons by `stepProb`. -/
theorem markovStepKernel_apply_singleton
    (x : PairState k) (b : Fin k) :
    markovStepKernel (k := k) x ({b} : Set (Fin k)) =
      stepProb (k := k) x.1 x.2 b := by
  classical
  rw [markovStepKernel, ProbabilityTheory.Kernel.finset_sum_apply' Finset.univ
    (fun c : Fin k =>
      ProbabilityTheory.Kernel.withDensity
        (ProbabilityTheory.Kernel.const (PairState k) (Measure.dirac c))
        (fun x _ => (stepProb (k := k) x.1 x.2 c : ℝ≥0∞))) x ({b} : Set (Fin k))]
  have hterm : ∀ c : Fin k,
      ProbabilityTheory.Kernel.withDensity
        (ProbabilityTheory.Kernel.const (PairState k) (Measure.dirac c))
        (fun x _ => (stepProb (k := k) x.1 x.2 c : ℝ≥0∞)) x ({b} : Set (Fin k))
        = if c = b then stepProb (k := k) x.1 x.2 c else 0 := by
    intro c
    rw [ProbabilityTheory.Kernel.withDensity_apply' _
      (measurable_stepWeight (k := k) c) x ({b} : Set (Fin k))]
    by_cases hc : c = b
    · subst hc
      simp [stepProb]
    · simp [hc, stepProb]
  simp_rw [hterm]
  rw [Finset.sum_eq_single_of_mem b (Finset.mem_univ b)]
  · simp
  · intro c _ hc
    simp [hc]

/-- Paired transition kernel that copies the parameter and samples the next state. -/
noncomputable def markovPairStepKernel : Kernel (PairState k) (PairState k) :=
  (keepParamKernel ∥ₖ markovStepKernel) ∘ₖ ProbabilityTheory.Kernel.copy (PairState k)

instance markovPairStepKernel_isMarkov : IsMarkovKernel (markovPairStepKernel (k := k)) := by
  dsimp [markovPairStepKernel]
  infer_instance

/-- One step of the paired kernel keeps the parameter fixed and samples the next
state from the corresponding row of `θ.trans`. -/
theorem markovPairStepKernel_apply_singleton_same
    (x : PairState k) (b : Fin k) :
    markovPairStepKernel (k := k) x ({(x.1, b)} : Set (PairState k)) =
      stepProb (k := k) x.1 x.2 b := by
  have hs :
      ({(x.1, b)} : Set (PairState k)) =
        ({x.1} : Set (MarkovParam k)) ×ˢ ({b} : Set (Fin k)) := by
    ext z
    simp
  rw [markovPairStepKernel,
    ProbabilityTheory.Kernel.comp_apply' _ _ _ (MeasurableSet.singleton (x.1, b))]
  rw [ProbabilityTheory.Kernel.copy_apply, lintegral_dirac]
  rw [hs, ProbabilityTheory.Kernel.parallelComp_apply_prod]
  simp [keepParamKernel, ProbabilityTheory.Kernel.deterministic_apply,
    markovStepKernel_apply_singleton, stepProb]

/-- The paired transition kernel cannot change the carried parameter. -/
theorem markovPairStepKernel_apply_singleton_of_ne
    (x : PairState k) (θ' : MarkovParam k) (b : Fin k) (h : θ' ≠ x.1) :
    markovPairStepKernel (k := k) x ({(θ', b)} : Set (PairState k)) = 0 := by
  have hs :
      ({(θ', b)} : Set (PairState k)) =
        ({θ'} : Set (MarkovParam k)) ×ˢ ({b} : Set (Fin k)) := by
    ext z
    simp
  rw [markovPairStepKernel,
    ProbabilityTheory.Kernel.comp_apply' _ _ _ (MeasurableSet.singleton (θ', b))]
  rw [ProbabilityTheory.Kernel.copy_apply, lintegral_dirac]
  rw [hs, ProbabilityTheory.Kernel.parallelComp_apply_prod]
  have hne : x.1 ≠ θ' := by
    simpa [eq_comm] using h
  have hkeep : keepParamKernel (k := k) x ({θ'} : Set (MarkovParam k)) = 0 := by
    simp [keepParamKernel, ProbabilityTheory.Kernel.deterministic_apply, hne]
  rw [hkeep, zero_mul]

/-- The final coordinate of an `Iic`-indexed paired prefix. -/
theorem measurable_lastPairPrefix (n : ℕ) :
    Measurable (fun x : PairPrefix k n => x ⟨n, Finset.mem_Iic.2 le_rfl⟩) := by
  exact measurable_pi_apply _

/-- Prefix-indexed paired transition kernel for `traj`. -/
noncomputable def pairPrefixKernel (n : ℕ) : Kernel (PairPrefix k n) (PairState k) :=
  ProbabilityTheory.Kernel.comap markovPairStepKernel
    (fun x : PairPrefix k n => x ⟨n, Finset.mem_Iic.2 le_rfl⟩)
    (measurable_lastPairPrefix (k := k) n)

instance pairPrefixKernel_isMarkov (n : ℕ) : IsMarkovKernel (pairPrefixKernel (k := k) n) := by
  dsimp [pairPrefixKernel]
  infer_instance

/-- Convert the paired start kernel to the prefix-shaped domain expected by `traj`. -/
noncomputable def pairStartPrefixKernel : Kernel (MarkovParam k) (PairPrefix k 0) :=
  ProbabilityTheory.Kernel.map markovStartKernel
    (MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => PairState k)).symm

instance pairStartPrefixKernel_isMarkov : IsMarkovKernel (pairStartPrefixKernel (k := k)) := by
  simpa [pairStartPrefixKernel] using
    (ProbabilityTheory.Kernel.IsMarkovKernel.map
      (κ := markovStartKernel (k := k))
      ((MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => PairState k)).symm.measurable))

/-- Trajectory kernel on paired states, parameterized by a Borel `MarkovParam`. -/
noncomputable def markovPairedTrajectoryKernel : Kernel (MarkovParam k) (PairTrajectory k) :=
  (ProbabilityTheory.Kernel.traj pairPrefixKernel 0) ∘ₖ pairStartPrefixKernel

instance markovPairedTrajectoryKernel_isMarkov :
    IsMarkovKernel (markovPairedTrajectoryKernel (k := k)) := by
  dsimp [markovPairedTrajectoryKernel]
  infer_instance

/-- Forget the carried parameter and keep only the state sequence. -/
noncomputable def stateSequenceOfPairTrajectory : PairTrajectory k → ℕ → Fin k :=
  fun x n => (x n).2

theorem measurable_stateSequenceOfPairTrajectory :
    Measurable (stateSequenceOfPairTrajectory (k := k)) := by
  simpa [stateSequenceOfPairTrajectory] using
    (show Measurable (fun x : PairTrajectory k => fun n => (x n).2) by
      fun_prop)

/-- The Borel Markov-parameter kernel into infinite state sequences. -/
noncomputable def markovSequenceKernel : Kernel (MarkovParam k) (ℕ → Fin k) :=
  ProbabilityTheory.Kernel.map markovPairedTrajectoryKernel
    (stateSequenceOfPairTrajectory (k := k))

instance markovSequenceKernel_isMarkov : IsMarkovKernel (markovSequenceKernel (k := k)) := by
  simpa [markovSequenceKernel] using
    (ProbabilityTheory.Kernel.IsMarkovKernel.map
      (κ := markovPairedTrajectoryKernel (k := k))
      (measurable_stateSequenceOfPairTrajectory (k := k)))

/-- Forget the carried parameter on a paired finite prefix. -/
def statePrefixOfPairPrefix (n : ℕ) : PairPrefix k n → PrefixState k n :=
  fun x i => (x i).2

theorem measurable_statePrefixOfPairPrefix (n : ℕ) :
    Measurable (statePrefixOfPairPrefix (k := k) n) := by
  unfold statePrefixOfPairPrefix
  fun_prop

/-- Lift a state prefix to the paired prefix carrying a fixed parameter `θ`. -/
def pairPrefixOfState (θ : MarkovParam k) (n : ℕ) (x : PrefixState k n) : PairPrefix k n :=
  fun i => (θ, x i)

theorem measurable_pairPrefixOfState (θ : MarkovParam k) (n : ℕ) :
    Measurable (pairPrefixOfState (k := k) θ n) := by
  unfold pairPrefixOfState
  fun_prop

@[simp] theorem statePrefixOfPairPrefix_pairPrefixOfState
    (θ : MarkovParam k) (n : ℕ) (x : PrefixState k n) :
    statePrefixOfPairPrefix (k := k) n (pairPrefixOfState (k := k) θ n x) = x := by
  funext i
  simp [statePrefixOfPairPrefix, pairPrefixOfState]

/-- Prefix event on paired trajectories. -/
def pairPrefixEvent (n : ℕ) (x : PairPrefix k n) : Set (PairTrajectory k) :=
  (frestrictLe n) ⁻¹' ({x} : Set (PairPrefix k n))

/-- Decompose a paired prefix of length `n+2` into its first `n+1` coordinates and
final paired state. -/
def pairNextPairMap (n : ℕ) : PairPrefix k (n + 1) → PairPrefix k n × PairState k :=
  fun x => (frestrictLe₂ (π := fun _ : ℕ => PairState k) (Nat.le_succ n) x,
    x ⟨n + 1, Finset.mem_Iic.2 le_rfl⟩)

/-- Reassemble a paired prefix of length `n+2` from its first `n+1` coordinates and
the final paired state. -/
noncomputable def pairSuccAssemble (n : ℕ) :
    PairPrefix k n × PairState k → PairPrefix k (n + 1) :=
  fun x =>
    (MeasurableEquiv.IicProdIoc (X := fun _ : ℕ => PairState k) (Nat.le_succ n))
      (x.1, (MeasurableEquiv.piSingleton (X := fun _ : ℕ => PairState k) n) x.2)

@[simp] theorem pairSuccAssemble_apply_le
    (n : ℕ) (x : PairPrefix k n × PairState k)
    {i : Finset.Iic (n + 1)} (hi : i.1 ≤ n) :
    pairSuccAssemble (k := k) n x i = x.1 ⟨i.1, Finset.mem_Iic.2 hi⟩ := by
  unfold pairSuccAssemble
  simp [MeasurableEquiv.IicProdIoc, hi]

@[simp] theorem pairSuccAssemble_apply_last
    (n : ℕ) (x : PairPrefix k n × PairState k) :
    pairSuccAssemble (k := k) n x ⟨n + 1, Finset.mem_Iic.2 le_rfl⟩ = x.2 := by
  unfold pairSuccAssemble
  simp [MeasurableEquiv.IicProdIoc, MeasurableEquiv.piSingleton]

@[simp] theorem pairNextPairMap_pairSuccAssemble
    (n : ℕ) (x : PairPrefix k n × PairState k) :
    pairNextPairMap (k := k) n (pairSuccAssemble (k := k) n x) = x := by
  rcases x with ⟨x, z⟩
  apply Prod.ext
  · funext i
    exact pairSuccAssemble_apply_le (k := k) n (x := (x, z)) (hi := Finset.mem_Iic.1 i.2)
  · simp [pairNextPairMap]

@[simp] theorem pairSuccAssemble_pairNextPairMap
    (n : ℕ) :
    pairSuccAssemble (k := k) n ∘ pairNextPairMap (k := k) n = id := by
  funext x
  funext i
  by_cases hi : i.1 ≤ n
  · simpa [pairNextPairMap] using
      (pairSuccAssemble_apply_le (k := k) n (x := pairNextPairMap (k := k) n x) hi)
  · have hi_eq : i = ⟨n + 1, Finset.mem_Iic.2 le_rfl⟩ := by
      apply Subtype.ext
      have hi_lt : n < i.1 := Nat.lt_of_not_ge hi
      exact le_antisymm (Finset.mem_Iic.1 i.2) (Nat.succ_le_of_lt hi_lt)
    subst hi_eq
    calc
      pairSuccAssemble (k := k) n (pairNextPairMap (k := k) n x)
          ⟨n + 1, Finset.mem_Iic.2 le_rfl⟩
          = (pairNextPairMap (k := k) n x).2 :=
            pairSuccAssemble_apply_last (k := k) n (x := pairNextPairMap (k := k) n x)
      _ = x ⟨n + 1, Finset.mem_Iic.2 le_rfl⟩ := rfl

theorem pairPrefixEvent_pairSuccAssemble_eq_pairPreimage
    (n : ℕ) (x : PairPrefix k n) (z : PairState k) :
    pairPrefixEvent (k := k) (n + 1) (pairSuccAssemble (k := k) n (x, z)) =
      (fun ω : PairTrajectory k => (frestrictLe n ω, ω (n + 1))) ⁻¹'
        ({(x, z)} : Set (PairPrefix k n × PairState k)) := by
  ext ω
  constructor
  · intro h
    have h' : frestrictLe (π := fun _ : ℕ => PairState k) (n + 1) ω =
        pairSuccAssemble (k := k) n (x, z) := by
      simpa [pairPrefixEvent] using h
    apply Prod.ext
    · funext i
      have hi :=
        congrArg (fun f : PairPrefix k (n + 1) =>
          f ⟨i.1, Finset.mem_Iic.2 (Nat.le_trans (Finset.mem_Iic.1 i.2) (Nat.le_succ n))⟩) h'
      calc
        ω i.1 = pairSuccAssemble (k := k) n (x, z)
            ⟨i.1, Finset.mem_Iic.2
              (Nat.le_trans (Finset.mem_Iic.1 i.2) (Nat.le_succ n))⟩ := hi
        _ = x i := pairSuccAssemble_apply_le (k := k) n (x := (x, z))
              (hi := Finset.mem_Iic.1 i.2)
    · have hlast :=
        congrArg (fun f : PairPrefix k (n + 1) => f ⟨n + 1, Finset.mem_Iic.2 le_rfl⟩) h'
      simpa [pairNextPairMap] using hlast
  · intro h
    have hfst : frestrictLe (π := fun _ : ℕ => PairState k) n ω = x := by
      exact congrArg Prod.fst h
    have hsnd : ω (n + 1) = z := by
      exact congrArg Prod.snd h
    change frestrictLe (π := fun _ : ℕ => PairState k) (n + 1) ω =
      pairSuccAssemble (k := k) n (x, z)
    funext i
    by_cases hi : i.1 ≤ n
    · have hi' :=
        congrArg (fun f : PairPrefix k n => f ⟨i.1, Finset.mem_Iic.2 hi⟩) hfst
      calc
        ω i.1 = x ⟨i.1, Finset.mem_Iic.2 hi⟩ := hi'
        _ = pairSuccAssemble (k := k) n (x, z) i :=
          (pairSuccAssemble_apply_le (k := k) n (x := (x, z)) (hi := hi)).symm
    · have hi_eq : i = ⟨n + 1, Finset.mem_Iic.2 le_rfl⟩ := by
        apply Subtype.ext
        have hi_lt : n < i.1 := Nat.lt_of_not_ge hi
        exact le_antisymm (Finset.mem_Iic.1 i.2) (Nat.succ_le_of_lt hi_lt)
      subst hi_eq
      simpa using hsnd

/-- The paired trajectory measure for a fixed parameter `θ`. -/
noncomputable def markovPairedTrajectoryMeasure (θ : MarkovParam k) : Measure (PairTrajectory k) :=
  ProbabilityTheory.Kernel.trajMeasure (X := fun _ : ℕ => PairState k)
    (markovStartKernel (k := k) θ) (pairPrefixKernel (k := k))

instance markovPairedTrajectoryMeasure_isProbability (θ : MarkovParam k) :
    IsProbabilityMeasure (markovPairedTrajectoryMeasure (k := k) θ) := by
  unfold markovPairedTrajectoryMeasure
  infer_instance

theorem markovPairedTrajectoryKernel_eq_measure
    (θ : MarkovParam k) :
    markovPairedTrajectoryKernel (k := k) θ =
      markovPairedTrajectoryMeasure (k := k) θ := by
  rw [markovPairedTrajectoryKernel, markovPairedTrajectoryMeasure,
    ProbabilityTheory.Kernel.trajMeasure]
  ext s hs
  rw [ProbabilityTheory.Kernel.comp_apply' _ _ _ hs,
    pairStartPrefixKernel,
    ProbabilityTheory.Kernel.map_apply
      (κ := markovStartKernel (k := k))
      (hf := (MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => PairState k)).symm.measurable)
      (a := θ),
    Measure.bind_apply hs
      (ProbabilityTheory.Kernel.aemeasurable _)]

/-- The paired trajectory measure has the expected initial `Iic 0` marginal. -/
theorem markovPairedTrajectoryMeasure_map_frestrictLe_zero
    (θ : MarkovParam k) :
    (markovPairedTrajectoryMeasure (k := k) θ).map
        (frestrictLe (π := fun _ : ℕ => PairState k) 0) =
      pairStartPrefixKernel (k := k) θ := by
  unfold markovPairedTrajectoryMeasure ProbabilityTheory.Kernel.trajMeasure
  rw [Measure.map_comp _ _ (by fun_prop)]
  rw [ProbabilityTheory.Kernel.traj_map_frestrictLe (X := fun _ : ℕ => PairState k)]
  rw [ProbabilityTheory.Kernel.partialTraj_self, Measure.id_comp]
  rw [pairStartPrefixKernel, ProbabilityTheory.Kernel.map_apply
    (κ := markovStartKernel (k := k))
    (hf := (MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => PairState k)).symm.measurable)
    (a := θ)]

/-- A constant-parameter paired `Iic n` prefix corresponding to the state prefix `x`. -/
def pairedPrefixOfState (θ : MarkovParam k) (n : ℕ) (x : PrefixState k n) : PairPrefix k n :=
  pairPrefixOfState (k := k) θ n x

theorem pairSuccAssemble_pairedPrefixOfState
    (θ : MarkovParam k) (n : ℕ) (x : PrefixState k n) (b : Fin k) :
    pairSuccAssemble (k := k) n
        (pairedPrefixOfState (k := k) θ n x, (θ, b)) =
      pairedPrefixOfState (k := k) θ (n + 1)
        (succAssemble (k := k) n (x, b)) := by
  funext i
  by_cases hi : i.1 ≤ n
  · simp [pairedPrefixOfState, pairPrefixOfState, pairSuccAssemble_apply_le,
      succAssemble_apply_le, hi]
  · have hi_eq : i = ⟨n + 1, Finset.mem_Iic.2 le_rfl⟩ := by
      apply Subtype.ext
      have hi_lt : n < i.1 := Nat.lt_of_not_ge hi
      exact le_antisymm (Finset.mem_Iic.1 i.2) (Nat.succ_le_of_lt hi_lt)
    subst hi_eq
    simp [pairedPrefixOfState, pairPrefixOfState, pairSuccAssemble_apply_last,
      succAssemble_apply_last]

theorem pairStartPrefixKernel_apply_singleton_pairedPrefixOfState
    (θ : MarkovParam k) (x : PrefixState k 0) :
    pairStartPrefixKernel (k := k) θ
        ({pairedPrefixOfState (k := k) θ 0 x} : Set (PairPrefix k 0)) =
      wordProb (k := k) θ (listOfPrefix (k := k) 0 x) := by
  let i0 : Finset.Iic 0 := ⟨0, Finset.mem_Iic.2 le_rfl⟩
  rw [pairStartPrefixKernel, ProbabilityTheory.Kernel.map_apply'
      (κ := markovStartKernel (k := k))
      ((MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => PairState k)).symm.measurable)
      θ (MeasurableSet.singleton _)]
  let b : Fin k := x i0
  have hpre :
      ((MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => PairState k)).symm) ⁻¹'
          ({pairedPrefixOfState (k := k) θ 0 x} : Set (PairPrefix k 0)) =
        ({(θ, b)} : Set (PairState k)) := by
    ext y
    constructor
    · intro hy
      have : (MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => PairState k)).symm y =
          pairedPrefixOfState (k := k) θ 0 x := by
        simpa using hy
      change y = (θ, b)
      simpa [pairedPrefixOfState, pairPrefixOfState, b, i0] using
        congrArg (fun z : PairPrefix k 0 => z i0) this
    · intro hy
      have : y = (θ, b) := by simpa [b] using hy
      subst this
      have hx :
          (MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => PairState k)).symm (θ, b) =
            pairedPrefixOfState (k := k) θ 0 x := by
        funext i
        have : i = i0 := Subsingleton.elim _ _
        subst this
        simp [pairedPrefixOfState, pairPrefixOfState, b]
      exact hx
  rw [hpre]
  have hword : wordProb (k := k) θ (listOfPrefix (k := k) 0 x) = initProb (k := k) θ b := by
    simp [wordProb, wordProbNN, wordProbAux, listOfPrefix, dropPrefix, b, i0]
  rw [hword]
  exact markovStartKernel_apply_singleton_same (k := k) θ b

/-- Base prefix probability for the paired trajectory measure. -/
theorem markovPairedTrajectoryMeasure_prefix_apply_zero
    (θ : MarkovParam k) (x : PrefixState k 0) :
    markovPairedTrajectoryMeasure (k := k) θ
        (pairPrefixEvent (k := k) 0 (pairedPrefixOfState (k := k) θ 0 x)) =
      wordProb (k := k) θ (listOfPrefix (k := k) 0 x) := by
  calc
    markovPairedTrajectoryMeasure (k := k) θ
        (pairPrefixEvent (k := k) 0 (pairedPrefixOfState (k := k) θ 0 x))
        =
      ((markovPairedTrajectoryMeasure (k := k) θ).map
        (frestrictLe (π := fun _ : ℕ => PairState k) 0))
          ({pairedPrefixOfState (k := k) θ 0 x} : Set (PairPrefix k 0)) := by
            exact (Measure.map_apply
              (measurable_frestrictLe (X := fun _ : ℕ => PairState k) 0)
              (MeasurableSet.singleton _)).symm
    _ = pairStartPrefixKernel (k := k) θ
          ({pairedPrefixOfState (k := k) θ 0 x} : Set (PairPrefix k 0)) := by
            rw [markovPairedTrajectoryMeasure_map_frestrictLe_zero (k := k) θ]
    _ = wordProb (k := k) θ (listOfPrefix (k := k) 0 x) :=
          pairStartPrefixKernel_apply_singleton_pairedPrefixOfState (k := k) θ x

/-- Recursion step for constant-parameter paired prefixes. -/
theorem markovPairedTrajectoryMeasure_prefix_apply_succAssemble
    (θ : MarkovParam k) (n : ℕ) (x : PrefixState k n) (b : Fin k) :
    markovPairedTrajectoryMeasure (k := k) θ
        (pairPrefixEvent (k := k) (n + 1)
          (pairedPrefixOfState (k := k) θ (n + 1)
            (succAssemble (k := k) n (x, b)))) =
      markovPairedTrajectoryMeasure (k := k) θ
        (pairPrefixEvent (k := k) n (pairedPrefixOfState (k := k) θ n x)) *
        stepProb (k := k) θ (lastCoord (k := k) n x) b := by
  classical
  let μ := markovPairedTrajectoryMeasure (k := k) θ
  have htraj :=
    ProbabilityTheory.Kernel.map_frestrictLe_trajMeasure_compProd_eq_map_trajMeasure
      (X := fun _ : ℕ => PairState k)
      (μ₀ := markovStartKernel (k := k) θ)
      (κ := pairPrefixKernel (k := k)) (a := n)
  have hmap :
      μ (pairPrefixEvent (k := k) (n + 1)
            (pairedPrefixOfState (k := k) θ (n + 1)
              (succAssemble (k := k) n (x, b))))
        =
      ((μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n)).compProd
          (pairPrefixKernel (k := k) n))
        ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
          Set (PairPrefix k n × PairState k)) := by
    calc
      μ (pairPrefixEvent (k := k) (n + 1)
            (pairedPrefixOfState (k := k) θ (n + 1)
              (succAssemble (k := k) n (x, b))))
          =
        μ ((fun ω : PairTrajectory k => (frestrictLe n ω, ω (n + 1))) ⁻¹'
            ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
              Set (PairPrefix k n × PairState k))) := by
              rw [← pairSuccAssemble_pairedPrefixOfState (k := k) θ n x b]
              exact congrArg μ <|
                pairPrefixEvent_pairSuccAssemble_eq_pairPreimage
                  (k := k) n (pairedPrefixOfState (k := k) θ n x) (θ, b)
      _ =
        (μ.map (fun ω : PairTrajectory k => (frestrictLe n ω, ω (n + 1))))
          ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
            Set (PairPrefix k n × PairState k)) := by
              symm
              exact Measure.map_apply
                (by fun_prop)
                (MeasurableSet.singleton _)
      _ =
        ((μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n)).compProd
          (pairPrefixKernel (k := k) n))
          ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
            Set (PairPrefix k n × PairState k)) := by
              simpa [μ] using
                congrArg
                  (fun ν : Measure (PairPrefix k n × PairState k) =>
                    ν ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
                      Set (PairPrefix k n × PairState k)))
                  htraj.symm
  have hcomp :
      ((μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n)).compProd
          (pairPrefixKernel (k := k) n))
        ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
          Set (PairPrefix k n × PairState k))
        =
      (μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n))
          ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) *
        (stepProb (k := k) θ (lastCoord (k := k) n x) b : ℝ≥0∞) := by
    rw [Measure.compProd_apply (MeasurableSet.singleton _)]
    change ∫⁻ z : PairPrefix k n,
        pairPrefixKernel (k := k) n z
          (Prod.mk z ⁻¹' ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
            Set (PairPrefix k n × PairState k)))
          ∂(μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n))
      =
      (μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n))
          ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) *
        (stepProb (k := k) θ (lastCoord (k := k) n x) b : ℝ≥0∞)
    have hpre :
        ∀ z : PairPrefix k n,
          Prod.mk z ⁻¹' ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
            Set (PairPrefix k n × PairState k)) =
            if z = pairedPrefixOfState (k := k) θ n x
            then ({(θ, b)} : Set (PairState k)) else ∅ := by
      intro z
      ext y
      by_cases hz : z = pairedPrefixOfState (k := k) θ n x
      · subst hz
        simp
      · simp [hz]
    have hkernel :
        ∀ z : PairPrefix k n,
          pairPrefixKernel (k := k) n z
            (Prod.mk z ⁻¹' ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
              Set (PairPrefix k n × PairState k)))
            =
          if z = pairedPrefixOfState (k := k) θ n x
          then (stepProb (k := k) θ (lastCoord (k := k) n x) b : ℝ≥0∞)
          else 0 := by
      intro z
      by_cases hz : z = pairedPrefixOfState (k := k) θ n x
      · rw [hpre z, if_pos hz]
        subst hz
        rw [pairPrefixKernel, ProbabilityTheory.Kernel.comap_apply']
        simpa [pairedPrefixOfState, pairPrefixOfState, lastCoord] using
          markovPairStepKernel_apply_singleton_same (k := k)
            ((θ, lastCoord (k := k) n x)) b
      · have hset0 :
            Prod.mk z ⁻¹' ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
              Set (PairPrefix k n × PairState k)) = (∅ : Set (PairState k)) := by
          ext y
          simp [hz]
        rw [pairPrefixKernel, ProbabilityTheory.Kernel.comap_apply', hset0, if_neg hz]
        simp
    rw [show
      (fun z : PairPrefix k n =>
        pairPrefixKernel (k := k) n z
          (Prod.mk z ⁻¹' ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
            Set (PairPrefix k n × PairState k))))
      =
      (fun z : PairPrefix k n =>
        if z = pairedPrefixOfState (k := k) θ n x
        then (stepProb (k := k) θ (lastCoord (k := k) n x) b : ℝ≥0∞) else 0) by
          funext z; exact hkernel z]
    have hxmeas : MeasurableSet ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) :=
      MeasurableSet.singleton _
    rw [show
      (fun z : PairPrefix k n =>
        if z = pairedPrefixOfState (k := k) θ n x
        then (stepProb (k := k) θ (lastCoord (k := k) n x) b : ℝ≥0∞) else 0)
      =
      Set.indicator ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n))
        (fun _ : PairPrefix k n =>
          (stepProb (k := k) θ (lastCoord (k := k) n x) b : ℝ≥0∞)) by
            funext z
            by_cases hz : z = pairedPrefixOfState (k := k) θ n x <;> simp [hz]]
    rw [lintegral_indicator hxmeas]
    simp [lintegral_const, mul_comm]
  have hprev :
      (μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n))
        ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) =
      μ (pairPrefixEvent (k := k) n (pairedPrefixOfState (k := k) θ n x)) := by
    exact Measure.map_apply
      (measurable_frestrictLe (X := fun _ : ℕ => PairState k) n)
      (MeasurableSet.singleton _)
  calc
    μ (pairPrefixEvent (k := k) (n + 1)
          (pairedPrefixOfState (k := k) θ (n + 1)
            (succAssemble (k := k) n (x, b))))
        =
      ((μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n)).compProd
          (pairPrefixKernel (k := k) n))
        ({(pairedPrefixOfState (k := k) θ n x, (θ, b))} :
          Set (PairPrefix k n × PairState k)) := hmap
    _ =
      (μ.map (frestrictLe (π := fun _ : ℕ => PairState k) n))
          ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) *
        (stepProb (k := k) θ (lastCoord (k := k) n x) b : ℝ≥0∞) := hcomp
    _ =
      μ (pairPrefixEvent (k := k) n (pairedPrefixOfState (k := k) θ n x)) *
        stepProb (k := k) θ (lastCoord (k := k) n x) b := by
          rw [hprev]

/-- Constant-parameter paired prefix probabilities are exactly `wordProb`. -/
theorem markovPairedTrajectoryMeasure_prefix_eq_wordProb
    (θ : MarkovParam k) :
    ∀ n : ℕ, ∀ x : PrefixState k n,
      markovPairedTrajectoryMeasure (k := k) θ
          (pairPrefixEvent (k := k) n (pairedPrefixOfState (k := k) θ n x)) =
        wordProb (k := k) θ (listOfPrefix (k := k) n x)
  | 0, x => markovPairedTrajectoryMeasure_prefix_apply_zero (k := k) θ x
  | n + 1, x => by
      let xPrev : PrefixState k n :=
        frestrictLe₂ (π := fun _ : ℕ => Fin k) (Nat.le_succ n) x
      let bLast : Fin k := lastCoord (k := k) (n + 1) x
      have hx : succAssemble (k := k) n (xPrev, bLast) = x := by
        simpa [xPrev, bLast, nextPairMap] using
          congrArg (fun f => f x) (succAssemble_nextPairMap (k := k) n)
      calc
        markovPairedTrajectoryMeasure (k := k) θ
            (pairPrefixEvent (k := k) (n + 1)
              (pairedPrefixOfState (k := k) θ (n + 1) x))
            =
          markovPairedTrajectoryMeasure (k := k) θ
            (pairPrefixEvent (k := k) (n + 1)
              (pairedPrefixOfState (k := k) θ (n + 1)
                (succAssemble (k := k) n (xPrev, bLast)))) := by
                  simp [hx]
        _ =
          markovPairedTrajectoryMeasure (k := k) θ
            (pairPrefixEvent (k := k) n (pairedPrefixOfState (k := k) θ n xPrev)) *
              stepProb (k := k) θ (lastCoord (k := k) n xPrev) bLast :=
                markovPairedTrajectoryMeasure_prefix_apply_succAssemble
                  (k := k) θ n xPrev bLast
        _ =
          wordProb (k := k) θ (listOfPrefix (k := k) n xPrev) *
            stepProb (k := k) θ (lastCoord (k := k) n xPrev) bLast := by
              simp [markovPairedTrajectoryMeasure_prefix_eq_wordProb (n := n) (x := xPrev)]
        _ =
          wordProb (k := k) θ
            (listOfPrefix (k := k) (n + 1)
              (succAssemble (k := k) n (xPrev, bLast))) := by
                symm
                exact wordProb_listOfPrefix_succAssemble (k := k) θ n xPrev bLast
        _ = wordProb (k := k) θ (listOfPrefix (k := k) (n + 1) x) := by
              simp [hx]

/-- Old fixed-parameter marginals sum to `1` over all finite prefixes of a given length. -/
theorem sum_wordProb_prefix_eq_one
    (θ : MarkovParam k) (n : ℕ) :
    ∑ x : PrefixState k n, wordProb (k := k) θ (listOfPrefix (k := k) n x) = 1 := by
  let μ := (Mettapedia.Logic.MarkovDeFinettiSequenceKernel.markovSequenceMeasure (k := k) θ).map
    (frestrictLe (π := fun _ : ℕ => Fin k) n)
  have hμprob : IsProbabilityMeasure μ := by
    dsimp [μ]
    exact Measure.isProbabilityMeasure_map
      (measurable_frestrictLe (X := fun _ : ℕ => Fin k) n).aemeasurable
  letI : IsProbabilityMeasure μ := hμprob
  have huniv : μ Set.univ = 1 := by
    exact measure_univ
  have hdecomp :
      μ Set.univ =
        ∑ x : PrefixState k n, μ ({x} : Set (PrefixState k n)) := by
    have h := measure_biUnion_finset (μ := μ) (s := Finset.univ)
      (f := fun x : PrefixState k n => ({x} : Set (PrefixState k n)))
      (fun x _ y _ hxy => Set.disjoint_singleton.2 hxy)
      (fun x _ => MeasurableSet.singleton x)
    simp only [Finset.mem_univ, Set.iUnion_true] at h
    rwa [show (⋃ b, ({b} : Set (PrefixState k n))) = Set.univ by ext; simp] at h
  rw [hdecomp] at huniv
  have hsingle (x : PrefixState k n) :
      μ ({x} : Set (PrefixState k n)) =
        wordProb (k := k) θ (listOfPrefix (k := k) n x) := by
    rw [Measure.map_apply (measurable_frestrictLe (X := fun _ : ℕ => Fin k) n)
      (MeasurableSet.singleton x)]
    simpa [prefixEvent] using
      Mettapedia.Logic.MarkovDeFinettiSequenceKernel.markovSequenceMeasure_prefix_eq_wordProb
        (k := k) θ n x
  simp_rw [hsingle] at huniv
  simpa [prefixEvent,
    Mettapedia.Logic.MarkovDeFinettiSequenceKernel.markovSequenceMeasure_prefix_eq_wordProb]
    using huniv

/-- Finite-support set of paired prefixes carrying the fixed parameter `θ`. -/
def constantPairPrefixSupport (θ : MarkovParam k) (n : ℕ) : Set (PairPrefix k n) :=
  ⋃ x ∈ (Finset.univ : Finset (PrefixState k n)),
    ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n))

theorem measurableSet_constantPairPrefixSupport
    (θ : MarkovParam k) (n : ℕ) :
    MeasurableSet (constantPairPrefixSupport (k := k) θ n) := by
  classical
  have hEq :
      constantPairPrefixSupport (k := k) θ n =
        ⋃ x : PrefixState k n,
          ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) := by
    ext y
    simp [constantPairPrefixSupport]
  rw [hEq]
  simpa using
    (MeasurableSet.iUnion
      (fun x : PrefixState k n =>
        MeasurableSet.singleton (pairedPrefixOfState (k := k) θ n x)))

/-- The paired prefix marginal is supported on the finite family of constant-parameter
prefix lifts. -/
theorem markovPairedTrajectoryMeasure_constantPairPrefixSupport
    (θ : MarkovParam k) (n : ℕ) :
    ((markovPairedTrajectoryMeasure (k := k) θ).map
      (frestrictLe (π := fun _ : ℕ => PairState k) n))
      (constantPairPrefixSupport (k := k) θ n) = 1 := by
  let μ := (markovPairedTrajectoryMeasure (k := k) θ).map
    (frestrictLe (π := fun _ : ℕ => PairState k) n)
  have hμprob : IsProbabilityMeasure μ := by
    dsimp [μ]
    exact Measure.isProbabilityMeasure_map
      (measurable_frestrictLe (X := fun _ : ℕ => PairState k) n).aemeasurable
  letI : IsProbabilityMeasure μ := hμprob
  have hinj : Function.Injective (pairedPrefixOfState (k := k) θ n) := by
    intro x y hxy
    have := congrArg (statePrefixOfPairPrefix (k := k) n) hxy
    simpa using this
  have hsupport :
      μ (constantPairPrefixSupport (k := k) θ n) =
        ∑ x : PrefixState k n,
          μ ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) := by
    simpa [constantPairPrefixSupport] using
      (measure_biUnion_finset (μ := μ) (s := Finset.univ)
        (f := fun x : PrefixState k n =>
          ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)))
        (fun x _ y _ hxy => Set.disjoint_singleton.2 (by
          intro hEq
          exact hxy (hinj hEq)))
        (fun x _ => MeasurableSet.singleton _))
  rw [hsupport]
  have hsingle (x : PrefixState k n) :
      μ ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) =
        wordProb (k := k) θ (listOfPrefix (k := k) n x) := by
    rw [Measure.map_apply (measurable_frestrictLe (X := fun _ : ℕ => PairState k) n)
      (MeasurableSet.singleton _)]
    exact markovPairedTrajectoryMeasure_prefix_eq_wordProb (k := k) θ n x
  simp_rw [hsingle]
  exact sum_wordProb_prefix_eq_one (k := k) θ n

theorem pairPrefix_statePrefix_inter_support
    (θ : MarkovParam k) (n : ℕ) (x : PrefixState k n) :
    (statePrefixOfPairPrefix (k := k) n ⁻¹' ({x} : Set (PrefixState k n))) ∩
        constantPairPrefixSupport (k := k) θ n
      =
    ({pairedPrefixOfState (k := k) θ n x} : Set (PairPrefix k n)) := by
  ext y
  constructor
  · rintro ⟨hyState, hySupp⟩
    simp only [constantPairPrefixSupport, Set.mem_iUnion, Finset.mem_univ,
      exists_prop] at hySupp
    rcases hySupp with ⟨x', -, hx'⟩
    have : x' = x := by
      have hy' : y = pairedPrefixOfState (k := k) θ n x' := by simpa using hx'
      have hyState' : statePrefixOfPairPrefix (k := k) n y = x := by simpa using hyState
      have hstate' := congrArg (statePrefixOfPairPrefix (k := k) n) hy'
      have hstate'' : statePrefixOfPairPrefix (k := k) n y = x' := by
        simpa [statePrefixOfPairPrefix_pairPrefixOfState] using hstate'
      exact hstate''.symm.trans hyState'
    subst this
    simpa using hx'
  · intro hy
    have hy' : y = pairedPrefixOfState (k := k) θ n x := by simpa using hy
    constructor
    · rw [hy']
      exact statePrefixOfPairPrefix_pairPrefixOfState (k := k) θ n x
    · simp [constantPairPrefixSupport, hy']

/-- Strict prefix probabilities under the Borel sequence kernel are exactly `wordProb`. -/
theorem markovSequenceKernel_prefix_eq_wordProb
    (θ : MarkovParam k) :
    ∀ n : ℕ, ∀ x : PrefixState k n,
      markovSequenceKernel (k := k) θ (prefixEvent (k := k) n x) =
        wordProb (k := k) θ (listOfPrefix (k := k) n x) := by
  intro n x
  let ν := markovPairedTrajectoryMeasure (k := k) θ
  let A : Set (PairTrajectory k) :=
    stateSequenceOfPairTrajectory (k := k) ⁻¹' prefixEvent (k := k) n x
  let B : Set (PairTrajectory k) :=
    frestrictLe (π := fun _ : ℕ => PairState k) n ⁻¹'
      constantPairPrefixSupport (k := k) θ n
  have hmap :
      markovSequenceKernel (k := k) θ (prefixEvent (k := k) n x) = ν A := by
    have hPrefixMeas : MeasurableSet (prefixEvent (k := k) n x) := by
      unfold prefixEvent
      exact (measurable_frestrictLe (X := fun _ : ℕ => Fin k) n) (MeasurableSet.singleton x)
    calc
      markovSequenceKernel (k := k) θ (prefixEvent (k := k) n x)
          =
        markovPairedTrajectoryKernel (k := k) θ
          (stateSequenceOfPairTrajectory (k := k) ⁻¹' prefixEvent (k := k) n x) := by
            exact ProbabilityTheory.Kernel.map_apply'
              (κ := markovPairedTrajectoryKernel (k := k))
              (hf := measurable_stateSequenceOfPairTrajectory (k := k))
              (a := θ)
              (hs := hPrefixMeas)
      _ = ν A := by simp [A, ν, markovPairedTrajectoryKernel_eq_measure (k := k) θ]
  have hBmeas : MeasurableSet B := by
    change MeasurableSet
      ((frestrictLe (π := fun _ : ℕ => PairState k) n) ⁻¹'
        constantPairPrefixSupport (k := k) θ n)
    exact (measurable_frestrictLe (X := fun _ : ℕ => PairState k) n)
      (measurableSet_constantPairPrefixSupport (k := k) θ n)
  have hBone : ν B = 1 := by
    rw [show ν B =
      ((markovPairedTrajectoryMeasure (k := k) θ).map
        (frestrictLe (π := fun _ : ℕ => PairState k) n))
        (constantPairPrefixSupport (k := k) θ n) by
          simpa [ν, B] using
            (Measure.map_apply
              (measurable_frestrictLe (X := fun _ : ℕ => PairState k) n)
              (measurableSet_constantPairPrefixSupport (k := k) θ n)).symm]
    exact markovPairedTrajectoryMeasure_constantPairPrefixSupport (k := k) θ n
  have hBcomp : ν Bᶜ = 0 := by
    letI : IsProbabilityMeasure ν := by infer_instance
    exact (prob_compl_eq_zero_iff (μ := ν) hBmeas).2 hBone
  have hinter : ν (B ∩ A) = ν A := by
    have hdiff0 : ν (A \ B) = 0 := by
      exact measure_mono_null (fun z hz => hz.2) hBcomp
    have hAeq : ν A = ν (A ∩ B) := by
      calc
        ν A = ν (A ∩ B) + ν (A \ B) := (measure_inter_add_diff A hBmeas).symm
        _ = ν (A ∩ B) := by simp [hdiff0]
    simpa [Set.inter_comm] using hAeq.symm
  have hset :
      B ∩ A =
        pairPrefixEvent (k := k) n (pairedPrefixOfState (k := k) θ n x) := by
    ext z
    constructor
    · intro hz
      rcases hz with ⟨hzB, hzA⟩
      change statePrefixOfPairPrefix (k := k) n (frestrictLe n z) = x at hzA
      have hzSupp : frestrictLe (π := fun _ : ℕ => PairState k) n z ∈
          constantPairPrefixSupport (k := k) θ n := hzB
      have : frestrictLe (π := fun _ : ℕ => PairState k) n z =
          pairedPrefixOfState (k := k) θ n x := by
        have hzInter :
            frestrictLe (π := fun _ : ℕ => PairState k) n z ∈
              (statePrefixOfPairPrefix (k := k) n ⁻¹' ({x} : Set (PrefixState k n))) ∩
                constantPairPrefixSupport (k := k) θ n := by
          exact ⟨by simpa using hzA, hzSupp⟩
        simpa [pairPrefix_statePrefix_inter_support (k := k) θ n x] using hzInter
      simp [pairPrefixEvent, this]
    · intro hz
      have hz' : frestrictLe (π := fun _ : ℕ => PairState k) n z =
          pairedPrefixOfState (k := k) θ n x := by
        simpa [pairPrefixEvent] using hz
      constructor
      · simp [B, hz', constantPairPrefixSupport]
      · change statePrefixOfPairPrefix (k := k) n (frestrictLe n z) = x
        rw [hz']
        exact statePrefixOfPairPrefix_pairPrefixOfState (k := k) θ n x
  calc
    markovSequenceKernel (k := k) θ (prefixEvent (k := k) n x) = ν A := hmap
    _ = ν (B ∩ A) := hinter.symm
    _ = ν (pairPrefixEvent (k := k) n (pairedPrefixOfState (k := k) θ n x)) := by
          rw [hset]
    _ = wordProb (k := k) θ (listOfPrefix (k := k) n x) :=
          markovPairedTrajectoryMeasure_prefix_eq_wordProb (k := k) θ n x

/-- The Borel sequence kernel evaluates finite cylinders by `wordProb`. -/
theorem markovSequenceKernel_cylinder_eq_wordProb
    (θ : MarkovParam k) :
    ∀ xs : List (Fin k),
      markovSequenceKernel (k := k) θ (cylinder (k := k) xs) =
        wordProb (k := k) θ xs := by
  refine List.ofFnRec ?_
  intro n x
  cases n with
  | zero =>
      have hx : List.ofFn x = ([] : List (Fin k)) := by simp
      rw [hx]
      letI : IsProbabilityMeasure (markovSequenceKernel (k := k) θ) := by infer_instance
      rw [MarkovDeFinettiRecurrence.cylinder, wordProb, wordProbNN]
      simp
  | succ n =>
      calc
        markovSequenceKernel (k := k) θ
            (MarkovDeFinettiRecurrence.cylinder (k := k) (List.ofFn x))
            =
          markovSequenceKernel (k := k) θ
            (prefixEvent (k := k) n (prefixOfFin (k := k) n x)) := by
              simp [prefixEvent_prefixOfFin_eq_cylinder_ofFn]
        _ =
          wordProb (k := k) θ
            (listOfPrefix (k := k) n (prefixOfFin (k := k) n x)) :=
              markovSequenceKernel_prefix_eq_wordProb (k := k) θ n
                (prefixOfFin (k := k) n x)
        _ = wordProb (k := k) θ (List.ofFn x) := by
              simp [listOfPrefix_prefixOfFin]

end MarkovDeFinettiSequenceKernelBorel

end Mettapedia.Logic
