import Mathlib.Data.Multiset.AddSub
import Mathlib.Data.Multiset.Count
import Mettapedia.Logic.PLNWorldModel
import Mettapedia.Logic.PLNWorldModelCalculus
import Mettapedia.Logic.PLNWorldModelHOL

/-!
# Infinitary HOL (Countable `iAnd`/`iOr`) Instance for WM Calculus

This module adds a countably infinitary HOL query layer on top of pointed HOL
states. Queries are generated by:

- base HOL predicate-codes (`atom`)
- countable conjunction (`iAnd : (Nat → q) → q`)
- countable disjunction (`iOr : (Nat → q) → q`)

Satisfaction is relational and evidence is extracted by positive/negative
support counts over multisets of pointed states.
-/

namespace Mettapedia.Logic.PLNWorldModelHOLInfinitary

open Mettapedia.Logic.PLNWorldModel
open Mettapedia.Logic.EvidenceClass
open Mettapedia.Logic.EvidenceQuantale
open Mettapedia.Logic.PLNWorldModelHOL
open scoped ENNReal

abbrev BaseHOLQuery (U : Type*) := Mettapedia.Logic.PLNWorldModelHOL.HOLQuery U
abbrev PointedHOL (U : Type*) := Mettapedia.Logic.PLNWorldModelHOL.PointedHOL U

/-- Countably infinitary HOL query fragment. -/
inductive HOLInfQuery (U : Type*) where
  | atom : BaseHOLQuery U → HOLInfQuery U
  | iAnd : (Nat → HOLInfQuery U) → HOLInfQuery U
  | iOr : (Nat → HOLInfQuery U) → HOLInfQuery U

/-- Relational satisfaction for infinitary HOL queries. -/
inductive SatisfiesInf {U : Type*} : PointedHOL U → HOLInfQuery U → Prop where
  | atom {pw : PointedHOL U} {q : BaseHOLQuery U} :
      pw.satisfies q → SatisfiesInf pw (.atom q)
  | iAnd {pw : PointedHOL U} {F : Nat → HOLInfQuery U} :
      (∀ n, SatisfiesInf pw (F n)) → SatisfiesInf pw (.iAnd F)
  | iOr {pw : PointedHOL U} {F : Nat → HOLInfQuery U} {n : Nat} :
      SatisfiesInf pw (F n) → SatisfiesInf pw (.iOr F)

theorem satisfiesInf_iAnd_iff {U : Type*} (pw : PointedHOL U) (F : Nat → HOLInfQuery U) :
    SatisfiesInf pw (.iAnd F) ↔ ∀ n, SatisfiesInf pw (F n) := by
  constructor
  · intro h
    cases h with
    | iAnd hall => exact hall
  · intro hall
    exact SatisfiesInf.iAnd hall

theorem satisfiesInf_iOr_iff {U : Type*} (pw : PointedHOL U) (F : Nat → HOLInfQuery U) :
    SatisfiesInf pw (.iOr F) ↔ ∃ n, SatisfiesInf pw (F n) := by
  constructor
  · intro h
    cases h with
    | iOr hs => exact ⟨_, hs⟩
  · intro h
    rcases h with ⟨n, hn⟩
    exact SatisfiesInf.iOr hn

abbrev HOLInfState (U : Type*) := Multiset (PointedHOL U)

instance {U : Type*} : EvidenceType (HOLInfState U) where

/-- Evidence extraction for infinitary HOL queries by support/refutation counts. -/
noncomputable def holInfEvidence {U : Type*}
    (W : HOLInfState U) (q : HOLInfQuery U) : Evidence := by
  classical
  exact
    ⟨(Multiset.countP (fun pw => SatisfiesInf pw q) W : ℝ≥0∞),
     (Multiset.countP (fun pw => ¬ SatisfiesInf pw q) W : ℝ≥0∞)⟩

theorem holInfEvidence_add {U : Type*}
    (W₁ W₂ : HOLInfState U) (q : HOLInfQuery U) :
    holInfEvidence (W₁ + W₂) q = holInfEvidence W₁ q + holInfEvidence W₂ q := by
  classical
  apply Evidence.ext'
  · simp [holInfEvidence, Multiset.countP_add, Evidence.hplus_def]
  · simp [holInfEvidence, Multiset.countP_add, Evidence.hplus_def]

noncomputable instance {U : Type*} : WorldModel (HOLInfState U) (HOLInfQuery U) where
  evidence := holInfEvidence
  evidence_add := holInfEvidence_add

theorem holInfEvidence_singleton_of_satisfies {U : Type*}
    (pw : PointedHOL U) (q : HOLInfQuery U) (h : SatisfiesInf pw q) :
    holInfEvidence ({pw} : HOLInfState U) q = ⟨1, 0⟩ := by
  classical
  ext <;> simp [holInfEvidence, ← Multiset.cons_zero, h]

theorem holInfEvidence_singleton_of_not_satisfies {U : Type*}
    (pw : PointedHOL U) (q : HOLInfQuery U) (h : ¬ SatisfiesInf pw q) :
    holInfEvidence ({pw} : HOLInfState U) q = ⟨0, 1⟩ := by
  classical
  ext <;> simp [holInfEvidence, ← Multiset.cons_zero, h]

theorem queryStrength_singleton_of_satisfies {U : Type*}
    (pw : PointedHOL U) (q : HOLInfQuery U) (h : SatisfiesInf pw q) :
    WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
        ({pw} : HOLInfState U) q = 1 := by
  change Evidence.toStrength (holInfEvidence ({pw} : HOLInfState U) q) = 1
  rw [holInfEvidence_singleton_of_satisfies pw q h]
  simp [Evidence.toStrength, Evidence.total]

theorem queryStrength_singleton_of_not_satisfies {U : Type*}
    (pw : PointedHOL U) (q : HOLInfQuery U) (h : ¬ SatisfiesInf pw q) :
    WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
        ({pw} : HOLInfState U) q = 0 := by
  change Evidence.toStrength (holInfEvidence ({pw} : HOLInfState U) q) = 0
  rw [holInfEvidence_singleton_of_not_satisfies pw q h]
  simp [Evidence.toStrength, Evidence.total]

theorem singleton_adequacy_strength_one {U : Type*}
    (pw : PointedHOL U) (q : HOLInfQuery U) :
    SatisfiesInf pw q ↔
      WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
        ({pw} : HOLInfState U) q = 1 := by
  constructor
  · intro h
    exact queryStrength_singleton_of_satisfies pw q h
  · intro h
    by_cases hs : SatisfiesInf pw q
    · exact hs
    · have h0 :
          WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
              ({pw} : HOLInfState U) q = 0 :=
        queryStrength_singleton_of_not_satisfies pw q hs
      have h01 : (0 : ℝ≥0∞) = 1 := by
        calc
          (0 : ℝ≥0∞) =
              WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
                ({pw} : HOLInfState U) q := h0.symm
          _ = 1 := h
      exact False.elim (zero_ne_one h01)

def pointwiseImplies {U : Type*} (q₁ q₂ : HOLInfQuery U) : Prop :=
  ∀ pw : PointedHOL U, SatisfiesInf pw q₁ → SatisfiesInf pw q₂

def singletonStrengthLE {U : Type*} (q₁ q₂ : HOLInfQuery U) : Prop :=
  ∀ pw : PointedHOL U,
    WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
        ({pw} : HOLInfState U) q₁ ≤
      WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
        ({pw} : HOLInfState U) q₂

theorem pointwiseImplies_iff_singletonStrengthLE {U : Type*}
    (q₁ q₂ : HOLInfQuery U) :
    pointwiseImplies q₁ q₂ ↔ singletonStrengthLE q₁ q₂ := by
  constructor
  · intro himp pw
    by_cases hq₁ : SatisfiesInf pw q₁
    · have hq₂ : SatisfiesInf pw q₂ := himp pw hq₁
      rw [queryStrength_singleton_of_satisfies pw q₁ hq₁]
      rw [queryStrength_singleton_of_satisfies pw q₂ hq₂]
    · rw [queryStrength_singleton_of_not_satisfies pw q₁ hq₁]
      exact zero_le _
  · intro hle pw hq₁
    by_contra hq₂
    have hsingleton := hle pw
    have h1 :
        WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
            ({pw} : HOLInfState U) q₁ = 1 :=
      queryStrength_singleton_of_satisfies pw q₁ hq₁
    have h0 :
        WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U)
            ({pw} : HOLInfState U) q₂ = 0 :=
      queryStrength_singleton_of_not_satisfies pw q₂ hq₂
    have h10 : (1 : ℝ≥0∞) ≤ 0 := by
      have htmp := hsingleton
      rw [h1, h0] at htmp
      exact htmp
    exact not_le_of_gt (by simp : (0 : ℝ≥0∞) < 1) h10

private theorem countP_le_countP_of_imp {U : Type*}
    (W : HOLInfState U)
    {p q : PointedHOL U → Prop}
    [DecidablePred p] [DecidablePred q]
    (himp : ∀ pw, p pw → q pw) :
    Multiset.countP p W ≤ Multiset.countP q W := by
  induction W using Multiset.induction_on with
  | empty =>
      simp
  | @cons a W ih =>
      by_cases hp : p a
      · have hq : q a := himp a hp
        simpa [Multiset.countP_cons_of_pos, hp, hq] using Nat.succ_le_succ ih
      · by_cases hq : q a
        · have hstep : Multiset.countP p W ≤ Multiset.countP q W + 1 :=
            le_trans ih (Nat.le_succ _)
          simpa [Multiset.countP_cons_of_neg, hp, Multiset.countP_cons_of_pos, hq]
            using hstep
        · simpa [Multiset.countP_cons_of_neg, hp, hq] using ih

private theorem holInfEvidence_total {U : Type*}
    (W : HOLInfState U) (q : HOLInfQuery U) :
    (holInfEvidence W q).total = (W.card : ℝ≥0∞) := by
  classical
  have hcardNat :
      W.card =
        Multiset.countP (fun pw : PointedHOL U => SatisfiesInf pw q) W +
          Multiset.countP (fun pw : PointedHOL U => ¬ SatisfiesInf pw q) W := by
    simpa using (Multiset.card_eq_countP_add_countP
      (p := fun pw : PointedHOL U => SatisfiesInf pw q) W)
  have hcard :
      (W.card : ℝ≥0∞) =
        (Multiset.countP (fun pw : PointedHOL U => SatisfiesInf pw q) W : ℝ≥0∞) +
          (Multiset.countP (fun pw : PointedHOL U => ¬ SatisfiesInf pw q) W : ℝ≥0∞) := by
    exact_mod_cast hcardNat
  unfold holInfEvidence Evidence.total
  simpa using hcard.symm

theorem queryStrength_le_of_pointwise {U : Type*}
    (W : HOLInfState U) (q₁ q₂ : HOLInfQuery U)
    (himp : pointwiseImplies q₁ q₂) :
    WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U) W q₁ ≤
      WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U) W q₂ := by
  let p₁ : PointedHOL U → Prop := fun pw => SatisfiesInf pw q₁
  let p₂ : PointedHOL U → Prop := fun pw => SatisfiesInf pw q₂
  letI : DecidablePred p₁ := Classical.decPred p₁
  letI : DecidablePred p₂ := Classical.decPred p₂
  have hq₁ :
      WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U) W q₁ =
        if (W.card : ℝ≥0∞) = 0 then 0 else (Multiset.countP p₁ W : ℝ≥0∞) / (W.card : ℝ≥0∞) := by
    unfold WorldModel.queryStrength Evidence.toStrength
    change (if (holInfEvidence W q₁).total = 0 then 0
      else (holInfEvidence W q₁).pos / (holInfEvidence W q₁).total)
        = if (W.card : ℝ≥0∞) = 0 then 0 else (Multiset.countP p₁ W : ℝ≥0∞) / (W.card : ℝ≥0∞)
    rw [holInfEvidence_total (W := W) (q := q₁)]
    simp [holInfEvidence, p₁]
  have hq₂ :
      WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U) W q₂ =
        if (W.card : ℝ≥0∞) = 0 then 0 else (Multiset.countP p₂ W : ℝ≥0∞) / (W.card : ℝ≥0∞) := by
    unfold WorldModel.queryStrength Evidence.toStrength
    change (if (holInfEvidence W q₂).total = 0 then 0
      else (holInfEvidence W q₂).pos / (holInfEvidence W q₂).total)
        = if (W.card : ℝ≥0∞) = 0 then 0 else (Multiset.countP p₂ W : ℝ≥0∞) / (W.card : ℝ≥0∞)
    rw [holInfEvidence_total (W := W) (q := q₂)]
    simp [holInfEvidence, p₂]
  by_cases hcard : (W.card : ℝ≥0∞) = 0
  · rw [hq₁, hq₂, hcard]
    simp
  · rw [hq₁, hq₂]
    simp [hcard]
    have hcountNat :
        Multiset.countP p₁ W ≤ Multiset.countP p₂ W :=
      countP_le_countP_of_imp (W := W) (p := p₁) (q := p₂) (by
        intro pw hp
        exact himp pw (by simpa [p₁] using hp))
    have hcount :
        (Multiset.countP p₁ W : ℝ≥0∞) ≤
          (Multiset.countP p₂ W : ℝ≥0∞) := by
      exact_mod_cast hcountNat
    exact ENNReal.div_le_div_right hcount (W.card : ℝ≥0∞)

/-- Infinitary conjunction elimination at the pointwise level. -/
theorem pointwise_iAnd_to_component {U : Type*}
    (F : Nat → HOLInfQuery U) (n : Nat) :
    pointwiseImplies (.iAnd F) (F n) := by
  intro pw h
  exact (satisfiesInf_iAnd_iff pw F).1 h n

/-- Infinitary disjunction introduction at the pointwise level. -/
theorem pointwise_component_to_iOr {U : Type*}
    (F : Nat → HOLInfQuery U) (n : Nat) :
    pointwiseImplies (F n) (.iOr F) := by
  intro pw h
  exact SatisfiesInf.iOr h

/-- WM inequality endpoint for countable conjunction elimination. -/
theorem queryStrength_le_iAnd_component {U : Type*}
    (W : HOLInfState U) (F : Nat → HOLInfQuery U) (n : Nat) :
    WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U) W (.iAnd F) ≤
      WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U) W (F n) :=
  queryStrength_le_of_pointwise (W := W) (q₁ := .iAnd F) (q₂ := F n)
    (pointwise_iAnd_to_component (F := F) (n := n))

/-- WM inequality endpoint for countable disjunction introduction. -/
theorem queryStrength_le_iOr_of_component {U : Type*}
    (W : HOLInfState U) (F : Nat → HOLInfQuery U) (n : Nat) :
    WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U) W (F n) ≤
      WorldModel.queryStrength (State := HOLInfState U) (Query := HOLInfQuery U) W (.iOr F) :=
  queryStrength_le_of_pointwise (W := W) (q₁ := F n) (q₂ := .iOr F)
    (pointwise_component_to_iOr (F := F) (n := n))

end Mettapedia.Logic.PLNWorldModelHOLInfinitary
