import Mathlib.Data.Multiset.AddSub
import Mathlib.Data.Multiset.Count
import Foundation.FirstOrder.Basic
import Mettapedia.Logic.PLNWorldModel
import Mettapedia.Logic.PLNWorldModelCalculus
import Mettapedia.Logic.PLNWorldModelFOL

/-!
# Infinitary FOL (Countable `iAnd`/`iOr`) Instance for WM Calculus

This module adds a countably infinitary first-order query layer on top of
pointed first-order structures. Queries are generated by:

- base first-order sentences (`atom`)
- countable conjunction (`iAnd : (Nat → q) → q`)
- countable disjunction (`iOr : (Nat → q) → q`)

Satisfaction is relational and evidence is extracted by positive/negative
support counts over multisets of pointed structures.
-/

namespace Mettapedia.Logic.PLNWorldModelFOLInfinitary

open LO
open LO.FirstOrder
open Mettapedia.Logic.PLNWorldModel
open Mettapedia.Logic.EvidenceClass
open Mettapedia.Logic.EvidenceQuantale
open Mettapedia.Logic.PLNWorldModelFOL
open scoped ENNReal

universe u

abbrev BaseFOLQuery (L : Language.{u}) := Sentence L
abbrev PointedFOL (L : Language.{u}) := SmallStruc L
abbrev FOLInfState (L : Language.{u}) := Multiset (PointedFOL L)

/-- Countably infinitary FOL query fragment. -/
inductive FOLInfQuery (L : Language.{u}) where
  | atom : BaseFOLQuery L → FOLInfQuery L
  | iAnd : (Nat → FOLInfQuery L) → FOLInfQuery L
  | iOr : (Nat → FOLInfQuery L) → FOLInfQuery L

/-- Relational satisfaction for infinitary FOL queries. -/
inductive SatisfiesInf {L : Language.{u}} : PointedFOL L → FOLInfQuery L → Prop where
  | atom {S : PointedFOL L} {φ : BaseFOLQuery L} :
      Semantics.Models S φ → SatisfiesInf S (.atom φ)
  | iAnd {S : PointedFOL L} {F : Nat → FOLInfQuery L} :
      (∀ n, SatisfiesInf S (F n)) → SatisfiesInf S (.iAnd F)
  | iOr {S : PointedFOL L} {F : Nat → FOLInfQuery L} {n : Nat} :
      SatisfiesInf S (F n) → SatisfiesInf S (.iOr F)

theorem satisfiesInf_iAnd_iff {L : Language.{u}}
    (S : PointedFOL L) (F : Nat → FOLInfQuery L) :
    SatisfiesInf S (.iAnd F) ↔ ∀ n, SatisfiesInf S (F n) := by
  constructor
  · intro h
    cases h with
    | iAnd hall => exact hall
  · intro hall
    exact SatisfiesInf.iAnd hall

theorem satisfiesInf_iOr_iff {L : Language.{u}}
    (S : PointedFOL L) (F : Nat → FOLInfQuery L) :
    SatisfiesInf S (.iOr F) ↔ ∃ n, SatisfiesInf S (F n) := by
  constructor
  · intro h
    cases h with
    | iOr hs => exact ⟨_, hs⟩
  · intro h
    rcases h with ⟨n, hn⟩
    exact SatisfiesInf.iOr hn

instance {L : Language.{u}} : EvidenceType (FOLInfState L) where

/-- Evidence extraction for infinitary FOL queries by support/refutation counts. -/
noncomputable def folInfEvidence {L : Language.{u}}
    (W : FOLInfState L) (q : FOLInfQuery L) : Evidence := by
  classical
  exact
    ⟨(Multiset.countP (fun S => SatisfiesInf S q) W : ℝ≥0∞),
     (Multiset.countP (fun S => ¬ SatisfiesInf S q) W : ℝ≥0∞)⟩

theorem folInfEvidence_add {L : Language.{u}}
    (W₁ W₂ : FOLInfState L) (q : FOLInfQuery L) :
    folInfEvidence (W₁ + W₂) q = folInfEvidence W₁ q + folInfEvidence W₂ q := by
  classical
  apply Evidence.ext'
  · simp [folInfEvidence, Multiset.countP_add, Evidence.hplus_def]
  · simp [folInfEvidence, Multiset.countP_add, Evidence.hplus_def]

noncomputable instance {L : Language.{u}} : WorldModel (FOLInfState L) (FOLInfQuery L) where
  evidence := folInfEvidence
  evidence_add := folInfEvidence_add

theorem folInfEvidence_singleton_of_satisfies {L : Language.{u}}
    (S : PointedFOL L) (q : FOLInfQuery L) (h : SatisfiesInf S q) :
    folInfEvidence ({S} : FOLInfState L) q = ⟨1, 0⟩ := by
  classical
  ext <;> simp [folInfEvidence, ← Multiset.cons_zero, h]

theorem folInfEvidence_singleton_of_not_satisfies {L : Language.{u}}
    (S : PointedFOL L) (q : FOLInfQuery L) (h : ¬ SatisfiesInf S q) :
    folInfEvidence ({S} : FOLInfState L) q = ⟨0, 1⟩ := by
  classical
  ext <;> simp [folInfEvidence, ← Multiset.cons_zero, h]

theorem queryStrength_singleton_of_satisfies {L : Language.{u}}
    (S : PointedFOL L) (q : FOLInfQuery L) (h : SatisfiesInf S q) :
    WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
        ({S} : FOLInfState L) q = 1 := by
  change Evidence.toStrength (folInfEvidence ({S} : FOLInfState L) q) = 1
  rw [folInfEvidence_singleton_of_satisfies S q h]
  simp [Evidence.toStrength, Evidence.total]

theorem queryStrength_singleton_of_not_satisfies {L : Language.{u}}
    (S : PointedFOL L) (q : FOLInfQuery L) (h : ¬ SatisfiesInf S q) :
    WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
        ({S} : FOLInfState L) q = 0 := by
  change Evidence.toStrength (folInfEvidence ({S} : FOLInfState L) q) = 0
  rw [folInfEvidence_singleton_of_not_satisfies S q h]
  simp [Evidence.toStrength, Evidence.total]

theorem singleton_adequacy_strength_one {L : Language.{u}}
    (S : PointedFOL L) (q : FOLInfQuery L) :
    SatisfiesInf S q ↔
      WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
        ({S} : FOLInfState L) q = 1 := by
  constructor
  · intro h
    exact queryStrength_singleton_of_satisfies S q h
  · intro h
    by_cases hs : SatisfiesInf S q
    · exact hs
    · have h0 :
          WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
              ({S} : FOLInfState L) q = 0 :=
        queryStrength_singleton_of_not_satisfies S q hs
      have h01 : (0 : ℝ≥0∞) = 1 := by
        calc
          (0 : ℝ≥0∞) =
              WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
                ({S} : FOLInfState L) q := h0.symm
          _ = 1 := h
      exact False.elim (zero_ne_one h01)

def pointwiseImplies {L : Language.{u}} (q₁ q₂ : FOLInfQuery L) : Prop :=
  ∀ S : PointedFOL L, SatisfiesInf S q₁ → SatisfiesInf S q₂

def singletonStrengthLE {L : Language.{u}} (q₁ q₂ : FOLInfQuery L) : Prop :=
  ∀ S : PointedFOL L,
    WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
        ({S} : FOLInfState L) q₁ ≤
      WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
        ({S} : FOLInfState L) q₂

theorem pointwiseImplies_iff_singletonStrengthLE {L : Language.{u}}
    (q₁ q₂ : FOLInfQuery L) :
    pointwiseImplies q₁ q₂ ↔ singletonStrengthLE q₁ q₂ := by
  constructor
  · intro himp S
    by_cases hq₁ : SatisfiesInf S q₁
    · have hq₂ : SatisfiesInf S q₂ := himp S hq₁
      rw [queryStrength_singleton_of_satisfies S q₁ hq₁]
      rw [queryStrength_singleton_of_satisfies S q₂ hq₂]
    · rw [queryStrength_singleton_of_not_satisfies S q₁ hq₁]
      exact zero_le _
  · intro hle S hq₁
    by_contra hq₂
    have hsingleton := hle S
    have h1 :
        WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
            ({S} : FOLInfState L) q₁ = 1 :=
      queryStrength_singleton_of_satisfies S q₁ hq₁
    have h0 :
        WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L)
            ({S} : FOLInfState L) q₂ = 0 :=
      queryStrength_singleton_of_not_satisfies S q₂ hq₂
    have h10 : (1 : ℝ≥0∞) ≤ 0 := by
      have htmp := hsingleton
      rw [h1, h0] at htmp
      exact htmp
    exact not_le_of_gt (by simp : (0 : ℝ≥0∞) < 1) h10

private theorem countP_le_countP_of_imp {L : Language.{u}}
    (W : FOLInfState L)
    {p q : PointedFOL L → Prop}
    [DecidablePred p] [DecidablePred q]
    (himp : ∀ S, p S → q S) :
    Multiset.countP p W ≤ Multiset.countP q W := by
  induction W using Multiset.induction_on with
  | empty =>
      simp
  | @cons a W ih =>
      by_cases hp : p a
      · have hq : q a := himp a hp
        simpa [Multiset.countP_cons_of_pos, hp, hq] using Nat.succ_le_succ ih
      · by_cases hq : q a
        · have hstep : Multiset.countP p W ≤ Multiset.countP q W + 1 :=
            le_trans ih (Nat.le_succ _)
          simpa [Multiset.countP_cons_of_neg, hp, Multiset.countP_cons_of_pos, hq]
            using hstep
        · simpa [Multiset.countP_cons_of_neg, hp, hq] using ih

private theorem folInfEvidence_total {L : Language.{u}}
    (W : FOLInfState L) (q : FOLInfQuery L) :
    (folInfEvidence W q).total = (W.card : ℝ≥0∞) := by
  classical
  have hcardNat :
      W.card =
        Multiset.countP (fun S : PointedFOL L => SatisfiesInf S q) W +
          Multiset.countP (fun S : PointedFOL L => ¬ SatisfiesInf S q) W := by
    simpa using (Multiset.card_eq_countP_add_countP
      (p := fun S : PointedFOL L => SatisfiesInf S q) W)
  have hcard :
      (W.card : ℝ≥0∞) =
        (Multiset.countP (fun S : PointedFOL L => SatisfiesInf S q) W : ℝ≥0∞) +
          (Multiset.countP (fun S : PointedFOL L => ¬ SatisfiesInf S q) W : ℝ≥0∞) := by
    exact_mod_cast hcardNat
  unfold folInfEvidence Evidence.total
  simpa using hcard.symm

theorem queryStrength_le_of_pointwise {L : Language.{u}}
    (W : FOLInfState L) (q₁ q₂ : FOLInfQuery L)
    (himp : pointwiseImplies q₁ q₂) :
    WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L) W q₁ ≤
      WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L) W q₂ := by
  let p₁ : PointedFOL L → Prop := fun S => SatisfiesInf S q₁
  let p₂ : PointedFOL L → Prop := fun S => SatisfiesInf S q₂
  letI : DecidablePred p₁ := Classical.decPred p₁
  letI : DecidablePred p₂ := Classical.decPred p₂
  have hq₁ :
      WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L) W q₁ =
        if (W.card : ℝ≥0∞) = 0 then 0 else (Multiset.countP p₁ W : ℝ≥0∞) / (W.card : ℝ≥0∞) := by
    unfold WorldModel.queryStrength Evidence.toStrength
    change (if (folInfEvidence W q₁).total = 0 then 0
      else (folInfEvidence W q₁).pos / (folInfEvidence W q₁).total)
        = if (W.card : ℝ≥0∞) = 0 then 0 else (Multiset.countP p₁ W : ℝ≥0∞) / (W.card : ℝ≥0∞)
    rw [folInfEvidence_total (W := W) (q := q₁)]
    simp [folInfEvidence, p₁]
  have hq₂ :
      WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L) W q₂ =
        if (W.card : ℝ≥0∞) = 0 then 0 else (Multiset.countP p₂ W : ℝ≥0∞) / (W.card : ℝ≥0∞) := by
    unfold WorldModel.queryStrength Evidence.toStrength
    change (if (folInfEvidence W q₂).total = 0 then 0
      else (folInfEvidence W q₂).pos / (folInfEvidence W q₂).total)
        = if (W.card : ℝ≥0∞) = 0 then 0 else (Multiset.countP p₂ W : ℝ≥0∞) / (W.card : ℝ≥0∞)
    rw [folInfEvidence_total (W := W) (q := q₂)]
    simp [folInfEvidence, p₂]
  by_cases hcard : (W.card : ℝ≥0∞) = 0
  · rw [hq₁, hq₂, hcard]
    simp
  · rw [hq₁, hq₂]
    simp [hcard]
    have hcountNat :
        Multiset.countP p₁ W ≤ Multiset.countP p₂ W :=
      countP_le_countP_of_imp (W := W) (p := p₁) (q := p₂) (by
        intro S hp
        exact himp S (by simpa [p₁] using hp))
    have hcount :
        (Multiset.countP p₁ W : ℝ≥0∞) ≤
          (Multiset.countP p₂ W : ℝ≥0∞) := by
      exact_mod_cast hcountNat
    exact ENNReal.div_le_div_right hcount (W.card : ℝ≥0∞)

/-- Infinitary conjunction elimination at the pointwise level. -/
theorem pointwise_iAnd_to_component {L : Language.{u}}
    (F : Nat → FOLInfQuery L) (n : Nat) :
    pointwiseImplies (.iAnd F) (F n) := by
  intro S h
  exact (satisfiesInf_iAnd_iff S F).1 h n

/-- Infinitary disjunction introduction at the pointwise level. -/
theorem pointwise_component_to_iOr {L : Language.{u}}
    (F : Nat → FOLInfQuery L) (n : Nat) :
    pointwiseImplies (F n) (.iOr F) := by
  intro S h
  exact SatisfiesInf.iOr h

/-- WM inequality endpoint for countable conjunction elimination. -/
theorem queryStrength_le_iAnd_component {L : Language.{u}}
    (W : FOLInfState L) (F : Nat → FOLInfQuery L) (n : Nat) :
    WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L) W (.iAnd F) ≤
      WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L) W (F n) :=
  queryStrength_le_of_pointwise (W := W) (q₁ := .iAnd F) (q₂ := F n)
    (pointwise_iAnd_to_component (F := F) (n := n))

/-- WM inequality endpoint for countable disjunction introduction. -/
theorem queryStrength_le_iOr_of_component {L : Language.{u}}
    (W : FOLInfState L) (F : Nat → FOLInfQuery L) (n : Nat) :
    WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L) W (F n) ≤
      WorldModel.queryStrength (State := FOLInfState L) (Query := FOLInfQuery L) W (.iOr F) :=
  queryStrength_le_of_pointwise (W := W) (q₁ := F n) (q₂ := .iOr F)
    (pointwise_component_to_iOr (F := F) (n := n))

end Mettapedia.Logic.PLNWorldModelFOLInfinitary
