import Mettapedia.Logic.PLNWorldModelFixpointClosure
import Mettapedia.Logic.PLNTrailFreeDampedConvergence
import Mettapedia.Logic.PLNWorldModelFixpointPolicy

/-!
# WM Fixpoint Bridge to Damped SP/SPN Dynamics

Bridge the generic WM fixpoint closure operator to the Chapter-9 damped
trail-free dynamics:

- encode damped orbit transitions as a rule pool over `(time, state)` queries,
- show each orbit point is generated by `immediateIter`,
- lift to least fixpoint closure,
- expose one endpoint theorem from eventual-fresh SP/SPN convergence to closure.
-/

namespace Mettapedia.Logic.PLNWorldModelFixpointSPNBridge

open Mettapedia.Logic.EvidenceClass
open Mettapedia.Logic.EvidenceQuantale
open Mettapedia.Logic.PLNWorldModel
open Mettapedia.Logic.PLNWorldModelFixpointClosure
open Mettapedia.Logic.PLNTrailFreeDampedConvergence
open Mettapedia.Logic.PLNWorldModelFixpointPolicy
open scoped ENNReal

abbrev TVState := Mettapedia.Logic.PLNTrailFreeDampedConvergence.TVState
abbrev OrbitState := BinaryEvidence
abbrev OrbitQuery := Nat × TVState
abbrev PolicyWeightedState := Mettapedia.Logic.PLNWorldModelFixpointPolicy.WeightedState
abbrev PolicyModalQuery := Mettapedia.Logic.PLNWorldModelFixpointPolicy.ModalQuery

noncomputable instance : EvidenceType OrbitState := inferInstance

/-- World-model used for orbit-rule closure:
queries are tracked structurally, while evidence is state-only. -/
noncomputable instance : BinaryWorldModel OrbitState OrbitQuery where
  evidence := fun W _q => W
  evidence_add := by
    intro W₁ W₂ _q
    rfl

/-- One damped SP/SPN transition rule at time `n` and state `x`. -/
def orbitRule
    (freshAt : Nat → Bool) (freshState : TVState)
    (n : Nat) (x : TVState) :
    WMConsequenceRuleOn OrbitState OrbitQuery where
  side := fun _ => True
  premise := (n, x)
  conclusion := (n + 1, dampedSPNStep (freshAt n) freshState x)
  sound := by
    intro W _h
    change W.toStrength ≤ W.toStrength
    exact le_rfl

/-- Full damped-orbit rule pool over all time/state pairs. -/
def orbitRules
    (freshAt : Nat → Bool) (freshState : TVState) :
    RuleSet OrbitState OrbitQuery :=
  { r | ∃ n x, r = orbitRule freshAt freshState n x }

/-- Initial orbit seed query `(0, x0)`. -/
def orbitSeed (x0 : TVState) : Set OrbitQuery :=
  { (0, x0) }

/-- Every damped-orbit point is generated by the finite-step immediate iterator
at any WM state parameter. -/
theorem orbit_pair_mem_immediateIter_on_state
    (freshAt : Nat → Bool) (freshState x0 : TVState) (W : OrbitState) :
    ∀ n,
      (n, dampedOrbit freshAt freshState x0 n) ∈
        immediateIter (State := OrbitState) (Query := OrbitQuery)
          (orbitRules freshAt freshState) W (orbitSeed x0) n := by
  intro n
  induction n with
  | zero =>
      simp [orbitSeed, immediateIter, dampedOrbit]
  | succ n ih =>
      refine Or.inr ?_
      refine
        ⟨orbitRule freshAt freshState n (dampedOrbit freshAt freshState x0 n),
          ?_, trivial, ih, ?_⟩
      · exact ⟨n, dampedOrbit freshAt freshState x0 n, rfl⟩
      · simp [orbitRule, dampedOrbit]

/-- Base-state wrapper of `orbit_pair_mem_immediateIter_on_state`. -/
theorem orbit_pair_mem_immediateIter
    (freshAt : Nat → Bool) (freshState x0 : TVState) :
    ∀ n,
      (n, dampedOrbit freshAt freshState x0 n) ∈
        immediateIter (State := OrbitState) (Query := OrbitQuery)
          (orbitRules freshAt freshState) (0 : OrbitState) (orbitSeed x0) n := by
  intro n
  exact orbit_pair_mem_immediateIter_on_state freshAt freshState x0 (0 : OrbitState) n

/-- Orbit points are contained in least fixpoint closure of the orbit rule pool
at any WM state parameter. -/
theorem orbit_pair_mem_leastRuleClosure_on_state
    (freshAt : Nat → Bool) (freshState x0 : TVState) (W : OrbitState) (n : Nat) :
    (n, dampedOrbit freshAt freshState x0 n) ∈
      leastRuleClosure (State := OrbitState) (Query := OrbitQuery)
        (orbitRules freshAt freshState) W (orbitSeed x0) := by
  exact
    (immediateIter_subset_leastRuleClosure
      (State := OrbitState) (Query := OrbitQuery)
      (R := orbitRules freshAt freshState)
      (W := W)
      (seed := orbitSeed x0)
      n)
      (orbit_pair_mem_immediateIter_on_state freshAt freshState x0 W n)

/-- Base-state wrapper of `orbit_pair_mem_leastRuleClosure_on_state`. -/
theorem orbit_pair_mem_leastRuleClosure
    (freshAt : Nat → Bool) (freshState x0 : TVState) (n : Nat) :
    (n, dampedOrbit freshAt freshState x0 n) ∈
      leastRuleClosure (State := OrbitState) (Query := OrbitQuery)
        (orbitRules freshAt freshState) (0 : OrbitState) (orbitSeed x0) := by
  exact orbit_pair_mem_leastRuleClosure_on_state freshAt freshState x0 (0 : OrbitState) n

/-- Endpoint bridge:
eventual-fresh SP/SPN convergence yields eventual `(n, freshState)` membership
in the WM least-closure generated by orbit transition rules, at any WM state
parameter. -/
theorem dampedOrbit_eventualFresh_to_fixpointClosure_endpoint_on_state
    (freshAt : Nat → Bool) (freshState x0 : TVState)
    (W : OrbitState)
    (hFreshEventually : ∃ N, ∀ n, N ≤ n → freshAt n = true) :
    ∃ M, ∀ n, M ≤ n →
      (n, freshState) ∈
        leastRuleClosure (State := OrbitState) (Query := OrbitQuery)
          (orbitRules freshAt freshState) W (orbitSeed x0) := by
  rcases hFreshEventually with ⟨N, hFresh⟩
  refine ⟨N + 1, ?_⟩
  intro n hn
  have hEq :
      dampedOrbit freshAt freshState x0 n = freshState :=
    dampedOrbit_eq_freshState_of_eventual_fresh freshAt freshState x0 N hFresh n hn
  have hMem :
      (n, dampedOrbit freshAt freshState x0 n) ∈
        leastRuleClosure (State := OrbitState) (Query := OrbitQuery)
          (orbitRules freshAt freshState) W (orbitSeed x0) :=
    orbit_pair_mem_leastRuleClosure_on_state freshAt freshState x0 W n
  simpa [hEq] using hMem

/-- Base-state wrapper of
`dampedOrbit_eventualFresh_to_fixpointClosure_endpoint_on_state`. -/
theorem dampedOrbit_eventualFresh_to_fixpointClosure_endpoint
    (freshAt : Nat → Bool) (freshState x0 : TVState)
    (hFreshEventually : ∃ N, ∀ n, N ≤ n → freshAt n = true) :
    ∃ M, ∀ n, M ≤ n →
      (n, freshState) ∈
        leastRuleClosure (State := OrbitState) (Query := OrbitQuery)
          (orbitRules freshAt freshState) (0 : OrbitState) (orbitSeed x0) := by
  exact
    dampedOrbit_eventualFresh_to_fixpointClosure_endpoint_on_state
      freshAt freshState x0 (0 : OrbitState) hFreshEventually

/-- Policy-adapted orbit state extracted from overlap/trust revised weighted WM
states at a selected modal query witness. -/
noncomputable def policyOrbitState
    (trusted : String → Prop) [DecidablePred trusted]
    (W₁ W₂ : PolicyWeightedState) (qPolicy : PolicyModalQuery) : OrbitState :=
  BinaryWorldModel.evidence (State := PolicyWeightedState) (Query := PolicyModalQuery)
    (policyRevisedState trusted W₁ W₂) qPolicy

/-- Single policy-aware SP/SPN endpoint:
eventual-fresh convergence lifts directly to least-closure membership over the
overlap/trusted policy-adapted WM state. -/
theorem dampedOrbit_eventualFresh_to_fixpointClosure_endpoint_policy
    (trusted : String → Prop) [DecidablePred trusted]
    (W₁ W₂ : PolicyWeightedState) (qPolicy : PolicyModalQuery)
    (freshAt : Nat → Bool) (freshState x0 : TVState)
    (hFreshEventually : ∃ N, ∀ n, N ≤ n → freshAt n = true) :
    ∃ M, ∀ n, M ≤ n →
      (n, freshState) ∈
        leastRuleClosure (State := OrbitState) (Query := OrbitQuery)
          (orbitRules freshAt freshState)
          (policyOrbitState trusted W₁ W₂ qPolicy) (orbitSeed x0) := by
  exact
    dampedOrbit_eventualFresh_to_fixpointClosure_endpoint_on_state
      freshAt freshState x0
      (policyOrbitState trusted W₁ W₂ qPolicy)
      hFreshEventually

/-- Trusted-all + compatibility specialization of the policy-aware endpoint:
the policy state contracts to additive revision before orbit closure. -/
theorem dampedOrbit_eventualFresh_to_fixpointClosure_endpoint_policy_add_of_compatible_trustedAll
    (W₁ W₂ : PolicyWeightedState) (qPolicy : PolicyModalQuery)
    (hcompat : Mettapedia.Logic.PLNWorldModelKripkeWeightedOverlap.compatible W₁ W₂)
    (freshAt : Nat → Bool) (freshState x0 : TVState)
    (hFreshEventually : ∃ N, ∀ n, N ≤ n → freshAt n = true) :
    ∃ M, ∀ n, M ≤ n →
      (n, freshState) ∈
        leastRuleClosure (State := OrbitState) (Query := OrbitQuery)
          (orbitRules freshAt freshState)
          (BinaryWorldModel.evidence (State := PolicyWeightedState) (Query := PolicyModalQuery)
            (W₁ + W₂) qPolicy) (orbitSeed x0) := by
  rcases
    dampedOrbit_eventualFresh_to_fixpointClosure_endpoint_policy
      (trusted := trustedAll) (W₁ := W₁) (W₂ := W₂) (qPolicy := qPolicy)
      (freshAt := freshAt) (freshState := freshState) (x0 := x0) hFreshEventually with
    ⟨M, hM⟩
  refine ⟨M, ?_⟩
  intro n hn
  have hState :
      policyOrbitState trustedAll W₁ W₂ qPolicy =
        BinaryWorldModel.evidence (State := PolicyWeightedState) (Query := PolicyModalQuery)
          (W₁ + W₂) qPolicy := by
    simp [policyOrbitState,
      policyRevisedState_eq_add_of_compatible_trustedAll (hcompat := hcompat)]
  simpa [hState] using hM n hn

end Mettapedia.Logic.PLNWorldModelFixpointSPNBridge
