import Mettapedia.OSLF.MeTTaPure.Core
import Mettapedia.OSLF.MeTTaIL.Substitution
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Fintype.EquivFin

/-!
# MeTTa-Pure: Typing and Conversion (Locally Nameless)

Defines the **dependent typing judgment** `PureHasType Γ t A` and the
**definitional equality** `PureConv t₁ t₂` for MeTTa-Pure.

## Design Decisions

- **Russell-style**: `U0 : U1` — no separate Type/Kind judgment
- **Intensional**: `PureConv` is β only — no functional extensionality
- **Declarative**: no bidirectional checking yet (that's future work)
- **Locally nameless with cofinite quantification**: binder rules open with
  fresh `fvar x` and universally quantify over all sufficiently fresh names.
  This follows Aydemir et al., "Engineering Formal Metatheory" (POPL 2008).
- **No J-eliminator initially**: just `Refl`; J is a later extension

## Context Convention

Contexts are association lists mapping free variable names to their types:
  `Γ = [(xₙ, Aₙ), ..., (x₁, A₁), (x₀, A₀)]`
Most recently bound variable is at the head.

## References

- Aydemir et al., "Engineering Formal Metatheory" (POPL 2008)
- Martin-Löf, "Intuitionistic Type Theory" (1984)
- Adjedj et al., "Martin-Löf à la Coq" (2023, arXiv:2310.06376)
-/

namespace Mettapedia.OSLF.MeTTaPure.Typing

open Mettapedia.OSLF.MeTTaIL.Syntax
open Mettapedia.OSLF.MeTTaIL.Substitution
open Mettapedia.OSLF.MeTTaPure.Core

/-! ## Contexts -/

/-- A MeTTa-Pure context: an association list mapping free variable names
    to their types. Most recently bound at the head. -/
abbrev PureCtx := List (String × Pattern)

/-- Domain of a context (the set of bound variable names). -/
def ctxDom (Γ : PureCtx) : List String := Γ.map Prod.fst

/-! ## Definitional Equality (Conversion)

`PureConv t₁ t₂` is the reflexive-symmetric-transitive closure of the three
β-rules, plus congruence in all type/term formers.

This is intensional: no η, no functional extensionality, no UIP. -/

/-- Definitional equality for MeTTa-Pure.
    The relation is the PER generated by the three β-rules with
    congruence under all constructors. -/
inductive PureConv : Pattern → Pattern → Prop where
  -- Equivalence
  | refl (t : Pattern) : PureConv t t
  | symm : PureConv t₁ t₂ → PureConv t₂ t₁
  | trans : PureConv t₁ t₂ → PureConv t₂ t₃ → PureConv t₁ t₃

  -- β-rules
  | betaPi (body a : Pattern) :
      PureConv (mkApp (mkLam body) a) (openBVar 0 a body)
  | betaSigmaFst (a b : Pattern) :
      PureConv (mkFst (mkPair a b)) a
  | betaSigmaSnd (a b : Pattern) :
      PureConv (mkSnd (mkPair a b)) b

  -- Congruence: Pi (cofinite for codomain — under binder)
  | congPi (L : Finset String) :
      PureConv A₁ A₂ →
      (∀ x, x ∉ L → PureConv (openBVar 0 (.fvar x) B₁) (openBVar 0 (.fvar x) B₂)) →
      PureConv (mkPi A₁ B₁) (mkPi A₂ B₂)
  -- Congruence: Sigma (cofinite for codomain — under binder)
  | congSigma (L : Finset String) :
      PureConv A₁ A₂ →
      (∀ x, x ∉ L → PureConv (openBVar 0 (.fvar x) B₁) (openBVar 0 (.fvar x) B₂)) →
      PureConv (mkSigma A₁ B₁) (mkSigma A₂ B₂)
  -- Congruence: Id
  | congId : PureConv A₁ A₂ → PureConv a₁ a₂ → PureConv b₁ b₂ →
      PureConv (mkId A₁ a₁ b₁) (mkId A₂ a₂ b₂)
  -- Congruence: Lam (cofinite — under binder)
  | congLam (L : Finset String) :
      (∀ x, x ∉ L → PureConv (openBVar 0 (.fvar x) body₁) (openBVar 0 (.fvar x) body₂)) →
      PureConv (mkLam body₁) (mkLam body₂)
  -- Congruence: App
  | congApp : PureConv f₁ f₂ → PureConv a₁ a₂ →
      PureConv (mkApp f₁ a₁) (mkApp f₂ a₂)
  -- Congruence: Pair
  | congPair : PureConv a₁ a₂ → PureConv b₁ b₂ →
      PureConv (mkPair a₁ b₁) (mkPair a₂ b₂)
  -- Congruence: Fst
  | congFst : PureConv p₁ p₂ →
      PureConv (mkFst p₁) (mkFst p₂)
  -- Congruence: Snd
  | congSnd : PureConv p₁ p₂ →
      PureConv (mkSnd p₁) (mkSnd p₂)
  -- Congruence: Refl
  | congRefl : PureConv a₁ a₂ →
      PureConv (mkRefl a₁) (mkRefl a₂)
/-! ## Typing Judgment

`PureHasType Γ t A` — "in context Γ, term t has type A."

Uses **cofinite quantification** for binder rules: rather than picking a
specific fresh name, we require the body to type-check for ALL names
outside a finite "bad" set L. This is the standard locally nameless
technique that makes the substitution lemma provable.

Key property: terms in the typing judgment are **locally closed** —
no bare `bvar` at the top level. Under a binder, `bvar 0` is opened
with a fresh `fvar x`, and `x` is added to the context. -/

inductive PureHasType : PureCtx → Pattern → Pattern → Prop where
  /-- Universe formation: `U0 : U1` in any context. -/
  | u0_type (Γ : PureCtx) :
      PureHasType Γ u0 u1

  /-- Free variable: `fvar x : A` when `(x, A) ∈ Γ`. -/
  | fvar (Γ : PureCtx) (x : String) (A : Pattern)
      (hmem : (x, A) ∈ Γ) :
      PureHasType Γ (.fvar x) A

  /-- Π-formation: if `A : U` and for all fresh `x`, `B[x] : U` in
      context extended with `x : A`, then `Π(A, B) : U`. -/
  | pi_form (Γ : PureCtx) (L : Finset String) (A B : Pattern) (U : Pattern)
      (hA : PureHasType Γ A U)
      (hB : ∀ x, x ∉ L →
        PureHasType ((x, A) :: Γ) (openBVar 0 (.fvar x) B) U) :
      PureHasType Γ (mkPi A B) U

  /-- Π-introduction: `λ.body : Π(A, B)` when for all fresh `x`,
      `body[x] : B[x]` in extended context. -/
  | lam_intro (Γ : PureCtx) (L : Finset String)
      (A body B : Pattern) (U : Pattern)
      (hA : PureHasType Γ A U)
      (hBody : ∀ x, x ∉ L →
        PureHasType ((x, A) :: Γ)
          (openBVar 0 (.fvar x) body) (openBVar 0 (.fvar x) B)) :
      PureHasType Γ (mkLam body) (mkPi A B)

  /-- Π-elimination: if `f : Π(A, B)` and `a : A`, then `f a : B[a]`.
      The codomain witness `hB` records that `B` is well-formed — standard
      practice in DTT formalizations to support the subject reduction proof. -/
  | app (Γ : PureCtx) (L : Finset String) (f a A B : Pattern) (U : Pattern)
      (hf : PureHasType Γ f (mkPi A B))
      (ha : PureHasType Γ a A)
      (hB : ∀ x, x ∉ L →
        PureHasType ((x, A) :: Γ) (openBVar 0 (.fvar x) B) U) :
      PureHasType Γ (mkApp f a) (openBVar 0 a B)

  /-- Σ-formation: analogous to Π-formation. -/
  | sigma_form (Γ : PureCtx) (L : Finset String) (A B : Pattern) (U : Pattern)
      (hA : PureHasType Γ A U)
      (hB : ∀ x, x ∉ L →
        PureHasType ((x, A) :: Γ) (openBVar 0 (.fvar x) B) U) :
      PureHasType Γ (mkSigma A B) U

  /-- Σ-introduction: `(a, b) : Σ(A, B)` when `a : A`, `b : B[a]`, and `B` is
      well-formed. The codomain witness `hB` is standard practice in DTT
      formalizations to support subject reduction (cf. Adjedj et al. 2023). -/
  | pair_intro (Γ : PureCtx) (L : Finset String) (a b A B : Pattern) (U : Pattern)
      (ha : PureHasType Γ a A)
      (hb : PureHasType Γ b (openBVar 0 a B))
      (hB : ∀ x, x ∉ L →
        PureHasType ((x, A) :: Γ) (openBVar 0 (.fvar x) B) U) :
      PureHasType Γ (mkPair a b) (mkSigma A B)

  /-- Σ-elimination (fst): `fst p : A` when `p : Σ(A, B)`. -/
  | fst_elim (Γ : PureCtx) (L : Finset String) (p A B : Pattern) (U : Pattern)
      (hp : PureHasType Γ p (mkSigma A B))
      (hB : ∀ x, x ∉ L →
        PureHasType ((x, A) :: Γ) (openBVar 0 (.fvar x) B) U) :
      PureHasType Γ (mkFst p) A

  /-- Σ-elimination (snd): `snd p : B[fst p]` when `p : Σ(A, B)`. -/
  | snd_elim (Γ : PureCtx) (L : Finset String) (p A B : Pattern) (U : Pattern)
      (hp : PureHasType Γ p (mkSigma A B))
      (hB : ∀ x, x ∉ L →
        PureHasType ((x, A) :: Γ) (openBVar 0 (.fvar x) B) U) :
      PureHasType Γ (mkSnd p) (openBVar 0 (mkFst p) B)

  /-- Id-formation: `Id(A, a, b) : U` when `A : U`, `a : A`, `b : A`. -/
  | id_form (Γ : PureCtx) (A a b : Pattern) (U : Pattern)
      (hA : PureHasType Γ A U)
      (ha : PureHasType Γ a A)
      (hb : PureHasType Γ b A) :
      PureHasType Γ (mkId A a b) U

  /-- Id-introduction: `refl a : Id(A, a, a)` when `a : A`. -/
  | refl_intro (Γ : PureCtx) (a A : Pattern)
      (ha : PureHasType Γ a A) :
      PureHasType Γ (mkRefl a) (mkId A a a)

  /-- Conversion: change type along definitional equality. -/
  | conv (Γ : PureCtx) (t A B : Pattern)
      (ht : PureHasType Γ t A)
      (hconv : PureConv A B) :
      PureHasType Γ t B

/-! ## Concrete Typing Examples -/

/-- U0 : U1 in the empty context. -/
theorem u0_has_type_u1 : PureHasType [] u0 u1 :=
  .u0_type []

/-- The identity function λx.x has type Π(U0, U0).
    The body `.bvar 0` is opened with fresh `fvar x`, yielding `fvar x`,
    which has type U0 in context `[(x, U0)]`. -/
theorem identity_type : PureHasType [] (mkLam (.bvar 0)) (mkPi u0 u0) :=
  .lam_intro [] ∅ u0 (.bvar 0) u0 u1 (.u0_type [])
    (fun x _ => by
      simp only [openBVar, u0]
      exact .fvar [(x, .apply "U0" [])] x (.apply "U0" [])
        List.mem_cons_self)

/-- First projection λA.λB.A : Π(U0, Π(U0, U0)).
    Takes two type arguments and returns the first. -/
theorem fst_proj_type :
    PureHasType [] (mkLam (mkLam (.bvar 1))) (mkPi u0 (mkPi u0 u0)) := by
  apply PureHasType.lam_intro [] ∅ u0 (mkLam (.bvar 1)) (mkPi u0 u0) u1
    (.u0_type [])
  intro x _
  -- Reduce: openBVar 0 (fvar x) (mkLam (bvar 1)) = mkLam (fvar x)
  --         openBVar 0 (fvar x) (mkPi u0 u0) = mkPi u0 u0
  simp only [openBVar, mkLam, mkPi, u0, List.map]
  apply PureHasType.lam_intro _ ∅
    (.apply "U0" []) (.fvar x) (.apply "U0" []) (.apply "U1" [])
    (.u0_type _)
  intro y _
  simp only [openBVar]
  exact .fvar _ x (.apply "U0" [])
    (List.mem_cons_of_mem _ List.mem_cons_self)

/-! ## Summary

**0 sorries. 0 axioms.**

Defines:
- `PureConv` — intensional definitional equality (3 β-rules + congruence)
- `PureHasType` — dependent typing judgment (12 rules) with cofinite quantification
- Three concrete typing examples (U0 : U1, identity, first projection)

**Next**: `Reduction.lean` defines `PureReduces` and proves `PureReduces → PureConv`.
-/

end Mettapedia.OSLF.MeTTaPure.Typing
