import Mettapedia.GSLT.Logic.MinimalContext

/-!
# Context-Decorated Hennessy-Milner Logic

This file formalizes contexts, the labeled transition system, and
context-decorated HML from Meredith's "Computation, Causality, and
Consciousness" (2026), Part I, §5.

## Main Definitions

* `MinimalContext` — a context shape certified minimal by an MSL interface
* `ContextStep` — minimal-context-labeled transitions (LTS)
* `HMLFormula` — Context-decorated HML formulae (Definition 5.2)
* `HMLFormula.satisfies` — Satisfaction relation for HML

## References

- Meredith, "Computation, Causality, and Consciousness" (2026), §5
- Leifer & Milner, "Deriving bisimulation congruences" (2000)
-/

namespace Mettapedia.GSLT

/-! ## Context-Labeled Transitions -/

/-- A minimal-context-labeled transition relation: `P →^K Q` iff `K[P] →_S Q`. -/
def GSLT.contextStep (S : GSLT) [HasMinimalContexts S]
    (t : S.Term) (K : MinimalContext S) (t' : S.Term) : Prop :=
  S.Step (K.plug t) t'

/-! ## Context-Decorated HML

    Definition 5.2 (Meredith 2026): The formulae of context-decorated HML
    are generated by: ϕ, ψ ::= ⊤ | ⊥ | ϕ ∧ ψ | ¬ϕ | ⟨K⟩ϕ
-/

/-- Context-decorated Hennessy-Milner Logic formulae.

    Definition 5.2 (Meredith 2026):
    ϕ, ψ ::= ⊤ | ⊥ | ϕ ∧ ψ | ¬ϕ | ⟨K⟩ϕ

    where K ranges over minimal contexts of S. The modality ⟨K⟩ϕ means:
    "K[u] reduces in one step to some u' satisfying ϕ"
-/
inductive HMLFormula (S : GSLT) [HasMinimalContexts S] : Type _ where
  /-- Truth: always satisfied -/
  | top : HMLFormula S
  /-- Falsity: never satisfied -/
  | bot : HMLFormula S
  /-- Conjunction -/
  | conj : HMLFormula S → HMLFormula S → HMLFormula S
  /-- Negation -/
  | neg : HMLFormula S → HMLFormula S
  /-- Diamond modality: ⟨K⟩ϕ means K[u] →_S u' and u' ⊨ ϕ -/
  | diamond : MinimalContext S → HMLFormula S → HMLFormula S

namespace HMLFormula

variable {S : GSLT} [HasMinimalContexts S]

/-- Disjunction (derived) -/
def disj (ϕ ψ : HMLFormula S) : HMLFormula S := .neg (.conj (.neg ϕ) (.neg ψ))

/-- Implication (derived) -/
def imp (ϕ ψ : HMLFormula S) : HMLFormula S := disj (.neg ϕ) ψ

/-- Box modality [K]ϕ = ¬⟨K⟩¬ϕ: "for all K-successors, ϕ holds" -/
def box [HasMinimalContexts S] (K : MinimalContext S) (ϕ : HMLFormula S) :
    HMLFormula S := .neg (.diamond K (.neg ϕ))

/-- Satisfaction relation: u ⊨ ϕ

    Definition 5.2 (Meredith 2026):
    u ⊨ ⟨K⟩ϕ  iff  K[u] →_S u' in one step, and u' ⊨ ϕ
-/
def satisfies (S : GSLT) [HasMinimalContexts S] : S.Term → HMLFormula S → Prop
  | _, .top => True
  | _, .bot => False
  | t, .conj ϕ ψ => satisfies S t ϕ ∧ satisfies S t ψ
  | t, .neg ϕ => ¬ satisfies S t ϕ
  | t, .diamond K ϕ => ∃ t', S.Step (K.plug t) t' ∧ satisfies S t' ϕ

/-- Two terms are HML-equivalent if they satisfy the same formulae -/
def hmlEquiv (S : GSLT) [HasMinimalContexts S] (t u : S.Term) : Prop :=
  ∀ ϕ : HMLFormula S, satisfies S t ϕ ↔ satisfies S u ϕ

/-- HML equivalence is reflexive -/
theorem hmlEquiv_refl (S : GSLT) [HasMinimalContexts S] (t : S.Term) : hmlEquiv S t t :=
  fun _ => Iff.rfl

/-- HML equivalence is symmetric -/
theorem hmlEquiv_symm {S : GSLT} [HasMinimalContexts S]
    {t u : S.Term} (h : hmlEquiv S t u) : hmlEquiv S u t :=
  fun ϕ => (h ϕ).symm

/-- HML equivalence is transitive -/
theorem hmlEquiv_trans {S : GSLT} [HasMinimalContexts S] {t u v : S.Term}
    (h1 : hmlEquiv S t u) (h2 : hmlEquiv S u v) : hmlEquiv S t v :=
  fun ϕ => (h1 ϕ).trans (h2 ϕ)

/-- HML equivalence forms a setoid -/
def hmlSetoid (S : GSLT) [HasMinimalContexts S] : Setoid S.Term where
  r := hmlEquiv S
  iseqv := ⟨hmlEquiv_refl S, fun h => hmlEquiv_symm h, fun h1 h2 => hmlEquiv_trans h1 h2⟩

end HMLFormula

/-! ## Adequacy (Statement)

    Theorem 5.1 (Meredith 2026): For any GSLT S equipped with the
    Milner-Sewell-Leifer LTS:
    u ∼ v  ⟺  ∀ϕ ∈ HML(K), u ⊨ ϕ ↔ v ⊨ ϕ
-/

/-- Adequacy: bisimilarity implies HML equivalence (soundness direction) -/
def GSLT.adequacy_sound (S : GSLT) [HasMinimalContexts S] : Prop :=
  ∀ {t u : S.Term}, S.Bisimilar t u → HMLFormula.hmlEquiv S t u

/-- Adequacy: HML equivalence implies bisimilarity (completeness direction) -/
def GSLT.adequacy_complete (S : GSLT) [HasMinimalContexts S] : Prop :=
  ∀ {t u : S.Term}, HMLFormula.hmlEquiv S t u → S.Bisimilar t u

/-- Full adequacy: bisimilarity ↔ HML equivalence. Theorem 5.1 (Meredith 2026). -/
def GSLT.adequacy (S : GSLT) [HasMinimalContexts S] : Prop :=
  S.adequacy_sound ∧ S.adequacy_complete

/-! ## Summary

This file establishes:

1. **MinimalContext**: Explicit minimal-context interface for the MSL layer
2. **contextStep**: Minimal-context-labeled transitions (MSL construction)
3. **HMLFormula**: Context-decorated HML formulae (Definition 5.2)
4. **satisfies**: Satisfaction relation for HML
5. **hmlEquiv**: HML equivalence (proven to be an equivalence relation)
6. **adequacy**: Statement of the adequacy theorem (Theorem 5.1)

**Paper Coverage**: Definitions 5.1–5.2; Theorem 5.1 (statement)

**No sorry statements** — everything is fully proven or cleanly stated.

**Next**: `Dynamics/ExtendedHML.lean` (Definition 8.1) or `Causality/SyncTree.lean`
-/

end Mettapedia.GSLT
