::Lesson 5b: Theorems with Explicit Proofs

environ
 vocabularies LESSON1, XBOOLE_0, SUBSET_1;
 notations XBOOLE_0;
 constructors XBOOLE_0;

begin

:: Reuse predicates from Lesson 1
definition
  let X be set;
  pred X is_empty means
  X = {};
end;

definition
  let X, Y be set;
  pred X is_subset_of Y means
  for x being object st x in X holds x in Y;
end;

:: Prove that empty set is empty (simple self-evident theorem)
theorem Th2:
  {} is_empty;