environ
  vocabularies NUMBERS, NAT_1, FINSET_1, CARD_1, XBOOLE_0,
               SUBSET_1, TARSKI, XBOOLEAN;
  notations   TARSKI, XBOOLE_0, SUBSET_1, ORDINAL1, NUMBERS,
               NAT_1, CARD_1, FINSET_1, XBOOLEAN;
  constructors NAT_D, CARD_1, FINSET_1, XBOOLEAN, MARGREL1;
  registrations XBOOLE_0, SUBSET_1, FINSET_1, NAT_1, CARD_1;
  requirements SUBSET, BOOLE, NUMERALS, ARITHM;
  theorems     NAT_1, NAT_D, CARD_1, CARD_2, FINSET_1,
               XBOOLE_0, XBOOLE_1, MARGREL1, XBOOLEAN;

begin

reserve n for Nat;

definition
  let n be Nat;
  func q(n) -> Element of BOOLEAN equals
::>    *140,142,302
    TRUE if n is odd otherwise FALSE;
  coherence;
::>       *72
end;

end;
::>,216
::>
::> 72: Unexpected correctness condition
::> 140: Unknown variable
::> 142: Unknown locus
::> 216: Unexpected "end"
::> 302: Functor symbol expected
