environ

vocabularies
  FPARITY, XBOOLE_0, SUBSET_1, NUMBERS, NAT_1,
  CARD_1, CARD_2, XBOOLEAN, MARGREL1;
notations
  XBOOLE_0, SUBSET_1, NAT_1, INT_1, NAT_D,
::>                       *830          *830
  CARD_1, CARD_2, XBOOLEAN, MARGREL1;
constructors
  FPARITY, NAT_D, CARD_1, CARD_2, XBOOLEAN;
::>     *808
registrations
  XBOOLEAN;
requirements
  SUBSET, BOOLE, NUMERALS;
theorems
  FPARITY, NAT_D, CARD_1, CARD_2, XBOOLE_1, MARGREL1;
::>     *806
definitions
  FPARITY;
::>     *805

begin

reserve n for Nat;

theorem
  parity(n) = TRUE or parity(n) = FALSE
proof
  n mod 2 = 0 or n mod 2 = 1 by NAT_D:12;
  hence thesis;
end;

end;
::>
::> 805: Cannot find definitions file
::> 806: Cannot find theorems file
::> 808: Cannot find constructors file
::> 830: Nothing imported from notations
